import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0676-q0059", 676, "A 29 year old man presents to ED with a painful lump in his left groin. Which of the following structures can be used to differentiate between a direct and an indirect inguinal hernia:", ["Inguinal ligament 58% rove", "Inferior epigastric vessels", "Pubic symphysis 3%", "Femoral artery 2%"], "A 29-year-old man presents to the ED with a painful lump in his left groin. Which structure differentiates a direct from an indirect inguinal hernia?", ["Inguinal ligament", "Femoral canal", "Inferior epigastric vessels", "Pubic symphysis", "Femoral artery"], 2, "An indirect inguinal hernia passes through the deep inguinal ring lateral to the inferior epigastric vessels. A direct inguinal hernia passes through Hesselbach triangle medial to these vessels.", "Inferior epigastric vessels distinguish direct from indirect inguinal hernia.", "Direct is medial; indirect is lateral to the inferior epigastric vessels.", "↔️ DIRECT = MEDIAL; INDIRECT = LATERAL to epigastric vessels.", aid("Direct hernia is medial and indirect hernia is lateral to the inferior epigastric vessels.", "Direct medial, indirect lateral.", ["↔️", "🩸"], "Direction and vessel cues retain the hernia relation.", "NCBI Bookshelf: Open Inguinal Hernia Repair", "https://www.ncbi.nlm.nih.gov/books/NBK459309/"), "https://www.ncbi.nlm.nih.gov/books/NBK459309/", "NCBI states that direct and indirect inguinal hernias are medial and lateral, respectively, to the inferior epigastric vessels."),
  r("anatomy-anatomy-all-pdf-p0678-q0061", 678, "ww The lymphatic drainage of the liver primarily drains into:", ["Superior mesenteric lymph nodes 15%", "Inferior mesenteric lymph nodes 5%", "Coeliac lymph nodes", "Lumbar lymph nodes 3% (x) ateral aortic lymph nodes 5%"], "The lymphatic drainage of the liver primarily drains into which nodes?", ["Superior mesenteric lymph nodes", "Inferior mesenteric lymph nodes", "Coeliac lymph nodes", "Lumbar lymph nodes", "Lateral aortic lymph nodes"], 2, "Deep hepatic lymphatics drain through hepatic and hepatoduodenal-ligament nodes. The chain along the hepatic artery then reaches the coeliac nodes.", "Liver lymph reaches coeliac nodes through hepatic drainage pathways.", "Deep hepatic lymph follows the hepatic-artery chain to coeliac nodes.", "🧭 LIVER lymph follows the hepatic artery to the COELIAC nodes.", aid("Deep hepatic lymphatic drainage reaches the coeliac nodes via hepatic and hepatoduodenal-ligament nodes.", "Liver follows hepatic artery to coeliac.", ["🧭", "🫀"], "Organ and pathway cues retain hepatic lymphatic drainage.", "PMC: Abdominal lymph-node drainage", "https://pmc.ncbi.nlm.nih.gov/articles/PMC9748447/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC9748447/", "A peer-reviewed anatomy review describes deep hepatic drainage through hepatic and hepatoduodenal-ligament nodes to coeliac nodes."),
  r("anatomy-anatomy-all-pdf-p0680-q0063", 680, "ww The ilioinguinal nerve supplies skin over which of the following regions: (x) Posterolateral gluteal region as", ["Upper medial thigh", "Lateral thigh 4%", "Posteromedial gluteal region 12%", "Posterior thigh 2%"], "The ilioinguinal nerve supplies skin over which region?", ["Posterolateral gluteal region", "Upper medial thigh", "Lateral thigh", "Posteromedial gluteal region", "Posterior thigh"], 1, "The ilioinguinal nerve is derived mainly from L1 and supplies the anteromedial upper thigh and parts of the external genitalia.", "Ilioinguinal nerve supplies the upper medial thigh.", "Ilioinguinal sensory territory includes the upper anteromedial thigh.", "🦵 ILIOINGUINAL = INNER upper thigh.", aid("The ilioinguinal nerve supplies the anteromedial upper thigh and external genitalia.", "Ilioinguinal: inner upper thigh.", ["🦵", "⬅️"], "Thigh and medial-direction cues retain ilioinguinal sensation.", "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), "https://www.ncbi.nlm.nih.gov/books/NBK557605/", "NCBI assigns ilioinguinal cutaneous sensation to the anteromedial thigh and external genitalia."),
  r("anatomy-anatomy-all-pdf-p0681-q0064", 681, "ww The greater sac of the peritoneal cavity is divided into two compartments by which of the following structures:", ["Liver 1%", "Stomach 4%", "Duodenum 2%", "Mesentery"], "The greater sac of the peritoneal cavity is divided into two compartments by which structure?", ["Liver", "Stomach", "Transverse mesocolon", "Duodenum", "Mesentery"], 2, "The transverse mesocolon separates the peritoneal cavity into supramesocolic and inframesocolic compartments.", "Transverse mesocolon divides the greater sac into supracolic and infracolic compartments.", "Transverse mesocolon is the boundary between supramesocolic and inframesocolic spaces.", "➖ TRANSVERSE mesocolon splits ABOVE and BELOW.", aid("The transverse mesocolon divides the peritoneal cavity into supramesocolic and inframesocolic compartments.", "Transverse splits above from below.", ["➖", "⬆️", "⬇️"], "Transverse line and vertical-direction cues retain the compartments.", "PMC: Peritoneal cavity anatomy", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4584112/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC4584112/", "A peer-reviewed anatomy review states that the transverse mesocolon divides the peritoneal cavity into supramesocolic and inframesocolic compartments."),
  r("anatomy-anatomy-all-pdf-p0682-q0065", 682, "Which of the following areas of the prostate gland is the most commonly involved in prostatic hyperplasia:", ["Central zone", "Anterior lobe", "Isthmus"], "Which prostate zone is most commonly involved in benign prostatic hyperplasia?", ["Central zone", "Transitional zone", "Peripheral zone", "Anterior lobe", "Isthmus"], 1, "Benign prostatic hyperplasia typically arises in and expands the transition zone, which surrounds the prostatic urethra.", "BPH arises in the transition zone around the prostatic urethra.", "Transition zone expansion narrows the prostatic urethra in BPH.", "🔄 BPH TRANSITIONS around the urethra.", aid("Benign prostatic hyperplasia primarily expands the prostate transition zone around the urethra.", "BPH transitions around urethra.", ["🔄", "🚪"], "Transition and urethral-opening cues retain BPH location.", "NCBI Bookshelf: Prostate Imaging", "https://www.ncbi.nlm.nih.gov/books/NBK567721/"), "https://www.ncbi.nlm.nih.gov/books/NBK567721/", "NCBI identifies the transition zone as the typical site of benign prostatic hyperplasia."),
  r("anatomy-anatomy-all-pdf-p0683-q0066", 683, "ww The ilioinguinal nerve innervates which of the following muscles:", ["Internal and external oblique muscles 9%", "Internal oblique and transversus abdominis muscles (x) Transversus abdominis and rectus abdominis muscles 9%", "Psoas major and minor muscles 10%", "Quadratus lumborum 5%"], "The ilioinguinal nerve innervates which muscles?", ["Internal and external oblique muscles", "Internal oblique and transversus abdominis muscles", "Transversus abdominis and rectus abdominis muscles", "Psoas major and minor muscles", "Quadratus lumborum"], 1, "The L1 ilioinguinal nerve supplies the internal oblique and transversus abdominis muscles, as well as sensory branches to the anteromedial thigh and external genitalia.", "Ilioinguinal nerve supplies internal oblique and transversus abdominis.", "L1 ilioinguinal nerve supplies two abdominal-wall muscles: internal oblique and transversus abdominis.", "⚡ ILIOINGUINAL powers INTERNAL + TRANSVERSUS.", aid("The L1 ilioinguinal nerve supplies internal oblique and transversus abdominis.", "Ilioinguinal: internal plus transversus.", ["⚡", "➕"], "Nerve and paired-muscle cues retain the motor supply.", "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), "https://www.ncbi.nlm.nih.gov/books/NBK557605/", "NCBI identifies internal oblique and transversus abdominis as ilioinguinal motor targets."),
  r("anatomy-anatomy-all-pdf-p0684-q0001", 684, "The femoral nerve is formed from the anterior rami of:", ["L2-L4", "£1 - L2", "Li-L4 ac", "E2=L3.", "L3-L4"], "The femoral nerve is formed from which anterior rami?", ["L2–L4", "L1–L2", "L1–L4", "L2–L3", "L3–L4"], 0, "The femoral nerve is the largest lumbar-plexus branch and derives from the posterior divisions of ventral rami L2 to L4.", "Femoral nerve roots are L2–L4.", "Femoral nerve = posterior divisions of L2–L4.", "🦵 FEMORAL starts L2 to L4.", aid("The femoral nerve arises from posterior divisions of ventral rami L2–L4.", "Femoral: L2 to L4.", ["🦵", "2️⃣", "4️⃣"], "Leg and root-number cues retain femoral origin.", "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), "https://www.ncbi.nlm.nih.gov/books/NBK557605/", "NCBI identifies the femoral nerve as a posterior-division branch of L2-L4 ventral rami.")
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0677-q0060", page: 677, expectedStem: "ww The inferior vena cava lies posterior to which of the following parts of the duodenum:", expectedOptions: ["Second part (x) hird and fourth parts 1% (v’) First and third parts 20%", "First and second parts 6%", "Second and third parts 57%"], stem: "The inferior vena cava lies posterior to which parts of the duodenum?", options: ["Second part", "Third and fourth parts", "First and third parts", "First and second parts", "Second and third parts"], warning: "Source page reviewed, but external evidence identifies both the second and third duodenal parts as anterior to the inferior vena cava; the displayed key is not restored.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482390/", finding: "NCBI describes both the second and third duodenal parts as lying anterior to the IVC, which conflicts with the source key of first and third parts." },
  { id: "anatomy-anatomy-all-pdf-p0679-q0062", page: 679, expectedStem: "ww The rectus sheath encloses all of the following structures except the:", expectedOptions: ["Transversus abdominis muscle", "Pyramidalis muscle 1%", "Superior epigastric artery 8%", "Inferior epigastric artery"], stem: "The rectus sheath encloses all of the following structures except which?", options: ["Transversus abdominis muscle", "Pyramidalis muscle", "Lower thoracic intercostal nerves", "Superior epigastric artery", "Inferior epigastric artery"], warning: "Source page reviewed, but reported transversus-abdominis variation within the rectus sheath makes the unqualified source formulation insufficiently exact.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK537153/", finding: "NCBI describes the usual rectus-sheath contents but also notes published evidence of transversus abdominis muscle within the sheath near the costal margin." },
  { id: "anatomy-anatomy-all-pdf-p0689-q0002", page: 689, expectedStem: "On their descent the ureters cross anteriorly to which of the following important structures: The origin of the superior mesenteric artery The origin of the inferior mesenteric artery The inferior epigastric artery The bifurcation of the common iliac artery The termination of the abdominal aorta C< |e ] see", expectedOptions: [], stem: "On their descent, the ureters cross anteriorly to which important structure?", options: ["The origin of the superior mesenteric artery", "The origin of the inferior mesenteric artery", "The inferior epigastric artery", "The bifurcation of the common iliac artery", "The termination of the abdominal aorta"], warning: "Source page reviewed, but no marked answer is displayed; no correct option is inferred from the blue user selection.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK534788/", finding: "The original source page has no answer marker; its blue outline is a user selection and is not treated as a source key." }
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-24.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
