import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });

const restorations = [
  {
    id: "anatomy-anatomy-all-pdf-p0614-q0009", page: 614, expectedStem: "iv p ww Which of the following muscles lies adjacent to the lateral border of the quadratus lumborum muscle:", expectedOptions: ["Rectus abdominis muscle 3% ml (x) lliacus muscle 16%", "Psoas major muscle 34%", "Transversus abdominis muscle", "Psoas minor muscle 3%"],
    stem: "Which muscle lies adjacent to the lateral border of quadratus lumborum?", options: ["Rectus abdominis", "Iliacus", "Psoas major", "Transversus abdominis", "Psoas minor"], correctOption: 3,
    explanation: "Quadratus lumborum lies between psoas major medially and transversus abdominis laterally on the posterior abdominal wall.", learningNote: "Quadratus lumborum: psoas medial, transversus abdominis lateral.", highYieldNote: "Quadratus lumborum lies between medial psoas and lateral transversus abdominis.", mnemonic: "↔️ QL: Psoas in, Transversus out.",
    memoryAid: aid("Quadratus lumborum lies between psoas major medially and transversus abdominis laterally.", "QL: Psoas in, Transversus out.", ["↔️", "🧱"], "Direction arrows and wall cue fix the medial-lateral relations.", "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557605/", finding: "NCBI states that quadratus lumborum is present between medial psoas and lateral transversus abdominis."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0615-q0010", page: 615, expectedStem: "ww Which of the following nerves transmits the parasympathetic supply to the stomach:", expectedOptions: ["Greater thoracic splanchnic nerves 6%", "Lesser thoracic splanchnic nerves 7%", "Lumbar splanchnic nerves 5%", "Pelvic splanchnic nerves 2%"],
    stem: "Which nerves transmit parasympathetic supply to the stomach?", options: ["Greater thoracic splanchnic nerves", "Lesser thoracic splanchnic nerves", "Lumbar splanchnic nerves", "Pelvic splanchnic nerves", "Vagus nerves"], correctOption: 4,
    explanation: "The vagus nerve supplies parasympathetic innervation to the stomach through anterior and posterior vagal fibres, which give gastric branches along the lesser curvature.", learningNote: "Vagus nerves provide parasympathetic innervation to the stomach.", highYieldNote: "Anterior and posterior vagal fibres provide the stomach's parasympathetic supply.", mnemonic: "🧠➡️🍽️ Vagus is the stomach's parasympathetic route.",
    memoryAid: aid("The vagus supplies parasympathetic innervation to the stomach through anterior and posterior vagal fibres.", "Vagus is the stomach's parasympathetic route.", ["🧠", "🍽️"], "Brain-to-stomach cues link cranial vagal input to gastric parasympathetic supply.", "NCBI Bookshelf: Stomach", "https://www.ncbi.nlm.nih.gov/books/NBK482334/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482334/", finding: "NCBI states that the vagus supplies gastric parasympathetic innervation via anterior and posterior vagal fibres."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0616-q0011", page: 616, expectedStem: "ww The jejunum predominantly occupies which region of the abdomen:", expectedOptions: ["Left upper quadrant", "Left lower quadrant 8%", "Right lower quadrant 6%", "Suprapubic region 4%"],
    stem: "Which abdominal quadrant does the jejunum predominantly occupy?", options: ["Left upper quadrant", "Right upper quadrant", "Left lower quadrant", "Right lower quadrant", "Suprapubic region"], correctOption: 0,
    explanation: "The jejunum is located mainly in the left upper quadrant; the ileum generally lies more toward the right lower abdomen.", learningNote: "Jejunum mainly occupies the left upper quadrant.", highYieldNote: "The jejunum is located mainly in the left upper quadrant of the abdomen.", mnemonic: "⬆️⬅️ Jejunum goes upper-left.",
    memoryAid: aid("The jejunum is located mainly in the left upper quadrant.", "Jejunum goes upper-left.", ["⬆️", "⬅️"], "Upward and left arrows cue the predominant quadrant.", "NCBI Bookshelf: Physiology, Small Bowel", "https://www.ncbi.nlm.nih.gov/books/NBK532263/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532263/", finding: "NCBI states that the jejunum is located mainly in the left upper quadrant."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0617-q0012", page: 617, expectedStem: "ww A 64 year old man is brought to ED with profuse haematemesis. Endoscopy shows oesophageal varices which are most likely the result of anastomosis of the left gastric vein with which of the following vessels:", expectedOptions: ["Abdominal aorta", "Azygos system of veins", "Inferior mesenteric vein 2%", "Superior mesenteric vein 8%"],
    stem: "A man has oesophageal varices from left gastric vein anastomosis. Which vessels form the systemic side of this collateral?", options: ["Abdominal aorta", "Azygos system of veins", "Inferior mesenteric vein", "Superior mesenteric vein", "Portal vein"], correctOption: 1,
    explanation: "The left gastric vein, a portal tributary, anastomoses with oesophageal veins that drain to the azygos system. Portal hypertension can dilate this portosystemic route into oesophageal varices.", learningNote: "Left gastric vein communicates with oesophageal veins draining to azygos.", highYieldNote: "Left gastric vein anastomoses with oesophageal veins that drain to the azygos system.", mnemonic: "⬅️🍽️ Left gastric climbs to azygos.",
    memoryAid: aid("Left gastric vein anastomoses with oesophageal veins draining to the azygos system.", "Left gastric climbs to azygos.", ["⬅️", "⬆️"], "Left and upward arrows cue left-gastric flow toward thoracic systemic drainage.", "Sharma and Rameshbabu: Portal Collaterals", "https://europepmc.org/articles/PMC3940321"), sourceUrl: "https://europepmc.org/articles/PMC3940321", finding: "A peer-reviewed review states that the left gastric vein anastomoses with oesophageal veins, which drain into the azygos vein."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0618-q0013", page: 618, expectedStem: "ww The superficial inguinal ring is an ‘opening’ in which of the following structures:", expectedOptions: ["External oblique aponeurosis", "Internal oblique aponeurosis 5%", "Transversus abdominis aponeurosis 5%", "Rectus abdominis aponeurosis 2%", "Transversalis fascia 1%"],
    stem: "The superficial inguinal ring is an opening in which structure?", options: ["External oblique aponeurosis", "Internal oblique aponeurosis", "Transversus abdominis aponeurosis", "Rectus abdominis aponeurosis", "Transversalis fascia"], correctOption: 0,
    explanation: "The superficial inguinal ring is the terminal opening of the inguinal canal. It is triangular and formed by fibres of the external oblique aponeurosis.", learningNote: "Superficial inguinal ring: opening in external oblique aponeurosis.", highYieldNote: "The superficial inguinal ring is a triangular opening formed by external oblique fibres.", mnemonic: "🔺 Superficial ring = External oblique triangle.",
    memoryAid: aid("The superficial inguinal ring is a triangular opening in the external oblique aponeurosis.", "Superficial ring = External oblique triangle.", ["🔺", "🚪"], "Triangle and doorway cues retain the ring's shape and aponeurotic wall.", "NCBI Bookshelf: Inguinal Region", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470204/", finding: "NCBI identifies the superficial ring as a triangular structure formed by fibres of the external oblique."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0619-q0014", page: 619, expectedStem: "ww The supraduodenal region of the common bile duct:", expectedOptions: ["lies superior to the cystic duct. 5%", "lies in the free margin of the greater omentum. 7%", "lies to the left of the hepatic artery proper. 9%", "lies anterior to the portal vein.", "empties into the major duodenal papilla. 58%"],
    stem: "Which statement about the supraduodenal region of the common bile duct is correct?", options: ["It lies superior to the cystic duct.", "It lies in the free margin of the greater omentum.", "It lies to the left of the hepatic artery proper.", "It lies anterior to the portal vein.", "It empties into the major duodenal papilla."], correctOption: 3,
    explanation: "The supraduodenal common bile duct lies in the hepatoduodenal ligament. The portal vein lies posterior to the common bile duct, while the proper hepatic artery lies to its left.", learningNote: "In the portal triad, common bile duct is anterior to portal vein and right of proper hepatic artery.", highYieldNote: "The portal vein lies posterior to the common bile duct in the hepatoduodenal ligament.", mnemonic: "🔙 Portal vein stays behind the bile duct.",
    memoryAid: aid("In the hepatoduodenal ligament, the portal vein lies posterior to the common bile duct.", "Portal vein stays behind the bile duct.", ["🔙", "🟢"], "Backward arrow and bile cue fix the portal-triad anterior-posterior relation.", "NCBI Bookshelf: Portal Venous System", "https://www.ncbi.nlm.nih.gov/books/NBK554589/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554589/", finding: "NCBI states that the portal vein travels posterior to the proper hepatic artery and common bile duct."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0620-q0015", page: 620, expectedStem: "The abdominal aorta bifurcates into the right and left common iliac arteries at which of the following vertebral levels:", expectedOptions: ["u", "(i", "L5"],
    stem: "At which vertebral level does the abdominal aorta bifurcate into the common iliac arteries?", options: ["L1", "L2", "L3", "L4", "L5"], correctOption: 3,
    explanation: "The abdominal aorta ends by bifurcating into the right and left common iliac arteries at the level of L4.", learningNote: "Abdominal aortic bifurcation: L4.", highYieldNote: "The abdominal aorta bifurcates into the common iliac arteries at L4.", mnemonic: "4️⃣ AORTA divides at L4.",
    memoryAid: aid("The abdominal aorta bifurcates into right and left common iliac arteries at L4.", "Aorta divides at L4.", ["4️⃣", "🔀"], "Four and split cues retain the vertebral level and arterial bifurcation.", "NCBI Bookshelf: Aorta", "https://www.ncbi.nlm.nih.gov/books/NBK537319/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK537319/", finding: "NCBI states that the abdominal aorta terminates by bifurcating into common iliac arteries at L4."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0621-q0016", page: 621, expectedStem: "ww Regarding the rectus abdominis muscle, which of the following statements is INCORRECT:", expectedOptions: ["It originates from the pubic crest, pubic tubercle and pubic symphysis. 8%", "It inserts onto the costal cartilages of ribs 5 - 7 and to the xiphoid process. 12%", "Itis separated in the midline by the linea alba. 6%", "The free lower border of its aponeurosis forms the inguinal ligament.", "Itis intersected along it length by tendinous intersections. 7%"],
    stem: "Regarding rectus abdominis, which statement is incorrect?", options: ["It originates from the pubic crest, pubic tubercle, and pubic symphysis.", "It inserts onto the costal cartilages of ribs 5–7 and the xiphoid process.", "It is separated in the midline by the linea alba.", "The free lower border of its aponeurosis forms the inguinal ligament.", "It is intersected along its length by tendinous intersections."], correctOption: 3,
    explanation: "The incorrect statement assigns formation of the inguinal ligament to rectus abdominis. The inguinal ligament is the thickened inferior border of the external oblique aponeurosis.", learningNote: "Inguinal ligament comes from external oblique aponeurosis, not rectus abdominis.", highYieldNote: "The inguinal ligament is formed by the inferior border of the external oblique aponeurosis, not rectus abdominis.", mnemonic: "🚫 Rectus does not make the groin ligament.",
    memoryAid: aid("Inguinal ligament is a thickened inferior part of external oblique aponeurosis, not rectus abdominis.", "Rectus does not make the groin ligament.", ["🚫", "🏹"], "Exclusion and groin cues distinguish rectus from external oblique.", "NCBI Bookshelf: Inguinal Region", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470204/", finding: "NCBI identifies the inguinal ligament as a thickened inferior portion of the external oblique aponeurosis."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0622-q0017", page: 622, expectedStem: "ww The quadrate lobe of the liver lies between which of the following structures:", expectedOptions: ["Ligamentum teres and gallbladder", "Ligamentum venosum and gallbladder 7% (x) Ligamentum teres and inferior vena cava 8%", "Ligamentum venosum and inferior vena cava 56%", "Gallbladder and inferior vena cava 4%"],
    stem: "The quadrate lobe of the liver lies between which structures?", options: ["Ligamentum teres and gallbladder", "Ligamentum venosum and gallbladder", "Ligamentum teres and inferior vena cava", "Ligamentum venosum and inferior vena cava", "Gallbladder and inferior vena cava"], correctOption: 0,
    explanation: "The quadrate lobe lies on the inferior surface of the liver, lateral to the round ligament and closely associated with the gallbladder. It is between the gallbladder fossa and the fissure for ligamentum teres.", learningNote: "Quadrate lobe lies between gallbladder and ligamentum teres fissure.", highYieldNote: "The quadrate lobe lies between the gallbladder and the fissure for ligamentum teres.", mnemonic: "🟫 Quadrate sits by the gallbladder and round ligament.",
    memoryAid: aid("The quadrate lobe lies between the gallbladder and fissure for ligamentum teres.", "Quadrate sits by the gallbladder and round ligament.", ["🟫", "🟢"], "Lobe and gallbladder cues retain the inferior-surface relation.", "NCBI Bookshelf: Liver", "https://www.ncbi.nlm.nih.gov/books/NBK500014/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK500014/", finding: "NCBI places the quadrate lobe lateral to the round ligament and closely associated with the gallbladder."
  },
  {
    id: "anatomy-anatomy-all-pdf-p0623-q0018", page: 623, expectedStem: "ww The obturator nerve is formed from the anterior rami of:", expectedOptions: ["i2-L4", "Ey - 12 5%", "L1-L4 3%", "E2SLS 7%", "L3-L4 ey"],
    stem: "The obturator nerve is formed from the anterior rami of which spinal nerves?", options: ["L2–L4", "L1–L2", "L1–L4", "L2–L3", "L3–L4"], correctOption: 0,
    explanation: "The obturator nerve arises from the lumbar plexus and has specific spinal roots L2 through L4. It supplies medial-thigh adductor muscles and sensory fibres to the medial thigh.", learningNote: "Obturator nerve roots: L2–L4.", highYieldNote: "The obturator nerve arises from L2–L4 spinal roots of the lumbar plexus.", mnemonic: "2️⃣3️⃣4️⃣ OBTURATOR opens L2–L4.",
    memoryAid: aid("The obturator nerve arises from L2 through L4 spinal roots.", "OBTURATOR opens L2–L4.", ["2️⃣", "3️⃣", "4️⃣"], "Sequential root-number cues retain the three lumbar levels.", "NCBI Bookshelf: Thigh Nerves", "https://www.ncbi.nlm.nih.gov/sites/books/NBK482225/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/sites/books/NBK482225/", finding: "NCBI identifies L2 through L4 as the specific spinal nerve roots of the obturator nerve."
  }
];
const restrictions = [];

function parseDrafts(source) { const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = source.indexOf(prefix); const arrayStart = start + prefix.length; const end = source.indexOf("];", arrayStart); if (start < 0 || end < 0) throw new Error("OCR draft export not found"); return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) }; }
function assertSnapshot(draft, item) { if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`); if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`); if (!["ocr_draft", "needs_review", "needs_image"].includes(draft.status)) throw new Error(`Unexpected status for ${item.id}`); }

const source = await readFile(bankPath, "utf8"); const parsed = parseDrafts(source); const byId = new Map(parsed.drafts.map((item) => [item.id, item])); const applied = [], restricted = [];
for (const item of restorations) { const draft = byId.get(item.id); assertSnapshot(draft, item); const before = { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, warnings: draft.warnings ?? [] }; Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); applied.push({ id: item.id, sourcePage: item.page, before, after: { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, warnings: draft.warnings }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
for (const item of restrictions) { const draft = byId.get(item.id); assertSnapshot(draft, item); const before = { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, warnings: draft.warnings ?? [], highYieldNote: draft.highYieldNote, mnemonic: draft.mnemonic, memoryAid: draft.memoryAid }; Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.explanation, learningNote: "", status: "needs_review", askable: false, needsImage: false, highYieldNote: undefined, mnemonic: undefined, memoryAid: undefined, warnings: [item.warning] }); restricted.push({ id: item.id, sourcePage: item.page, before, after: { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, warnings: draft.warnings }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`); await mkdir(auditDir, { recursive: true }); await writeFile(path.join(auditDir, "applied-anatomy-batch-19.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`); console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
