import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0866-q0046", 866, "ww The gallbladder is located on which of the following aspects of the liver:", ["Right lobe", "Left lobe 4%", "Quadrate lobe 7% CJ", "Diaphragmatic surface 4%"], "The gallbladder is located on which of the following aspects of the liver:", ["Right lobe", "Left lobe", "Quadrate lobe", "Caudate lobe", "Diaphragmatic surface"], 0, "The gallbladder lies in a fossa on the visceral surface of the liver between segments IV and V, at the quadrate-lobe and right-lobe boundary.", "Gallbladder fossa lies on the visceral surface at the right-lobe and quadrate-lobe boundary.", "Gallbladder fossa: visceral liver surface between quadrate and right lobes.", "🟢 GALLBLADDER in the RIGHT-side liver fossa.", aid("The gallbladder lies in a fossa on the visceral liver surface between the quadrate and right lobes.", "Gallbladder in the right-side fossa.", ["🟢", "➡️"], "Gallbladder and direction cues retain the liver-surface relation.", "NCBI Bookshelf: Gallbladder", "https://www.ncbi.nlm.nih.gov/books/NBK459288/"), "https://www.ncbi.nlm.nih.gov/books/NBK459288/", "NCBI places the gallbladder in a visceral liver-surface fossa between segments IV and V."),
  r("anatomy-anatomy-all-pdf-p0869-q0047", 869, "wv Control of bile and pancreatic fluid entering the duodenum is regulated by the:", ["Ampulla of Vater", "Major duodenal papilla 3%", "External biliary sphincter 2%", "Internal biliary sphincter 0%", "Sphincter of Oddi"], "Control of bile and pancreatic fluid entering the duodenum is regulated by the:", ["Ampulla of Vater", "Major duodenal papilla", "External biliary sphincter", "Internal biliary sphincter", "Sphincter of Oddi"], 4, "The sphincter of Oddi is the smooth-muscle valve around the hepatopancreatic ampulla that regulates the delivery of bile and pancreatic secretions into the duodenum.", "Sphincter of Oddi regulates bile and pancreatic juice entering the duodenum.", "Oddi is the gate for bile and pancreatic juice entering the duodenum.", "🚪 ODDI opens the bile-and-pancreas gate.", aid("The sphincter of Oddi regulates bile and pancreatic-secretory flow through the ampulla into the duodenum.", "Oddi opens the bile-and-pancreas gate.", ["🚪", "🟡"], "Gate and bile cues retain the regulatory sphincter.", "NCBI Bookshelf: Sphincter of Oddi", "https://www.ncbi.nlm.nih.gov/books/NBK551515/"), "https://www.ncbi.nlm.nih.gov/books/NBK551515/", "NCBI defines the sphincter of Oddi as the valve regulating bile and pancreatic secretions into the duodenum."),
  r("anatomy-anatomy-all-pdf-p0877-q0049", 877, "The infracolic compartment is divided into right and left spaces by which of the following structures:", ["Jejunum", "lleum", "Sigmoid mesocolon"], "The infracolic compartment is divided into right and left spaces by which of the following structures:", ["Jejunum", "Ileum", "Mesentery", "Transverse mesocolon", "Sigmoid mesocolon"], 2, "The root of the small-bowel mesentery runs obliquely across the posterior abdominal wall and divides the infracolic compartment into right and left infracolic spaces.", "Root of mesentery divides infracolic compartment into right and left spaces.", "Infracolic right and left spaces are divided by the mesenteric root.", "↙️ MESENTERY makes two infracolic lanes.", aid("The root of the small-bowel mesentery divides the infracolic compartment into right and left spaces.", "Mesentery makes two infracolic lanes.", ["↙️", "↔️"], "Diagonal and split cues retain the compartment division.", "PMC: Imaging of Infracolic and Pelvic Compartment", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6590000/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC6590000/", "Peer-reviewed anatomy review states that small-bowel mesentery subdivides the infracolic compartment into right and left spaces."),
  r("anatomy-anatomy-all-pdf-p0881-q0050", 881, "The stomach receives its blood supply primarily from which of the following arteries:", ["Inferior mesenteric artery Renal artery 0%", "Suprarenal artery"], "The stomach receives its blood supply primarily from which of the following arteries:", ["Superior mesenteric artery", "Inferior mesenteric artery", "Coeliac trunk", "Renal artery", "Suprarenal artery"], 2, "The stomach is a foregut organ. Its arterial supply arises from coeliac-trunk branches, including left gastric, splenic, and common hepatic branches.", "Stomach is foregut, so its arterial supply arises from the coeliac trunk.", "Foregut stomach receives coeliac-trunk branches.", "🌳 COELIAC trunk feeds the FOREGUT stomach.", aid("The stomach receives arterial branches from the coeliac trunk, the main foregut artery.", "Coeliac trunk feeds the foregut stomach.", ["🌳", "🍽️"], "Tree and stomach cues retain the arterial origin.", "NCBI Bookshelf: Celiac Trunk", "https://www.ncbi.nlm.nih.gov/books/NBK459241/"), "https://www.ncbi.nlm.nih.gov/books/NBK459241/", "NCBI identifies the coeliac trunk as the primary arterial supply to foregut organs including the stomach."),
  r("anatomy-anatomy-all-pdf-p0886-q0051", 886, "Visceral afferent fibres from the ascending colon and proximal transverse colon travel to which of the following spinal cord segments:", ["T6-18", "T8- 110 N%", "110 - T11", "Lie 58% (x) L3-L4 2%"], "Visceral afferent fibres from the ascending colon and proximal transverse colon travel to which of the following spinal cord segments:", ["T6 - T8", "T8 - T10", "T10 - T11", "L1 - L2", "L3 - L4"], 2, "The ascending colon and proximal two-thirds of the transverse colon are midgut derivatives. Their sympathetic pathway uses the lesser splanchnic nerve, which arises from T10 to T11 and carries visceral afferent fibres.", "Proximal colon is midgut: lesser splanchnic T10–T11.", "Ascending and proximal transverse colon: midgut pathway through T10–T11 lesser splanchnic nerves.", "🔟1️⃣1️⃣ LESSER splanchnic serves MIDGUT.", aid("Midgut visceral afferents from proximal colon travel with the lesser splanchnic nerve arising at T10 to T11.", "T10 to T11 lesser splanchnic serves midgut.", ["🔟", "1️⃣1️⃣"], "Segment-number cues retain the proximal-colon pathway.", "NCBI Bookshelf: Splanchnic Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK560504/"), "https://www.ncbi.nlm.nih.gov/books/NBK560504/", "NCBI identifies T10–T11 lesser splanchnic origin, visceral-afferent carriage, and midgut plexus distribution; ascending and proximal transverse colon are midgut."),
  r("anatomy-anatomy-all-pdf-p0891-q0052", 891, "The lateral cutaneous nerve of the thigh is formed from the anterior rami of:", ["u", "LI-L2 a", "L2", "L3-L4"], "The lateral cutaneous nerve of the thigh is formed from the anterior rami of:", ["L1", "L1 - L2", "L2", "L2 - L3", "L3 - L4"], 3, "The lateral femoral cutaneous nerve is a purely sensory lumbar-plexus nerve that typically arises from L2 and L3 ventral rami and supplies the anterolateral thigh.", "Lateral femoral cutaneous nerve: L2–L3.", "Lateral femoral cutaneous nerve is L2–L3 and sensory to the anterolateral thigh.", "2️⃣3️⃣ LATERAL thigh nerve = L2–L3.", aid("The lateral femoral cutaneous nerve typically arises from L2 and L3 ventral rami.", "Lateral thigh equals L2 to L3.", ["2️⃣", "3️⃣"], "Segment-number cues retain the nerve roots.", "NCBI Bookshelf: Lateral Femoral Cutaneous Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK532301/"), "https://www.ncbi.nlm.nih.gov/books/NBK532301/", "NCBI states that the lateral femoral cutaneous nerve typically arises from L2 and L3 ventral rami."),
  r("anatomy-anatomy-all-pdf-p0895-q0053", 895, "ww Regarding the large intestine, which of the following parts is not described correctly:", ["Caecum - Intraperitoneal", "Ascending colon - Retroperitoneal 6%", "Transverse colon - Intraperitoneal 5%", "Descending colon - Retroperitoneal 3%", "Sigmoid colon - Retroperitoneal"], "Regarding the large intestine, which of the following parts is not described correctly:", ["Caecum - Intraperitoneal", "Ascending colon - Retroperitoneal", "Transverse colon - Intraperitoneal", "Descending colon - Retroperitoneal", "Sigmoid colon - Retroperitoneal"], 4, "The cecum, transverse colon, and sigmoid colon are intraperitoneal. The ascending and descending colons are secondarily retroperitoneal, so ‘sigmoid colon—retroperitoneal’ is incorrect.", "Sigmoid colon is intraperitoneal, unlike ascending and descending colon.", "Cecum, transverse, and sigmoid are intraperitoneal; ascending and descending are retroperitoneal.", "🔁 SIGMOID is mobile in PERITONEUM.", aid("The sigmoid colon is intraperitoneal; ascending and descending colon are retroperitoneal.", "Sigmoid stays mobile in peritoneum.", ["🔁", "🫧"], "Loop and peritoneal-space cues retain the relation.", "NCBI Bookshelf: Large Intestine", "https://www.ncbi.nlm.nih.gov/books/NBK470577/"), "https://www.ncbi.nlm.nih.gov/books/NBK470577/", "NCBI classifies the cecum, transverse colon, and sigmoid colon as intraperitoneal and right and left colon as retroperitoneal."),
  r("anatomy-anatomy-all-pdf-p0900-q0054", 900, "The ilioinguinal nerve supplies skin over which of the following regions:", ["Posterolateral gluteal region", "Lateral thigh", "Posteromedial gluteal region (x) Posterior thigh 2%"], "The ilioinguinal nerve supplies skin over which of the following regions:", ["Posterolateral gluteal region", "Upper medial thigh", "Lateral thigh", "Posteromedial gluteal region", "Posterior thigh"], 1, "The ilioinguinal nerve arises from L1 and supplies skin over the upper medial thigh as well as portions of the external genitalia and inguinal region.", "Ilioinguinal nerve supplies upper medial thigh and external genitalia.", "Ilioinguinal: L1 to upper medial thigh, inguinal region, and external genitalia.", "1️⃣ ILIOINGUINAL = INNER upper thigh.", aid("The ilioinguinal nerve supplies cutaneous sensation over the upper medial thigh, inguinal region, and external genitalia.", "Ilioinguinal is L1 to the inner upper thigh.", ["1️⃣", "⬆️"], "L1 and upper-direction cues retain the sensory field.", "NCBI Bookshelf: Anterolateral Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK556034/"), "https://www.ncbi.nlm.nih.gov/books/NBK556034/", "NCBI identifies ilioinguinal supply to the medial thigh, inguinal region, and external genitalia."),
  r("anatomy-anatomy-all-pdf-p0904-q0055", 904, "Which of the following parts of the pancreas is intraperitoneal:", ["Head 12%", "Neck", "Body", "Uncinate process 4%"], "Which of the following parts of the pancreas is intraperitoneal:", ["Head", "Neck", "Body", "Uncinate process", "Tail"], 4, "Most of the pancreas is retroperitoneal. Its tail lies within the splenorenal ligament and is the intraperitoneal pancreatic portion.", "Pancreatic tail lies in splenorenal ligament and is intraperitoneal.", "Pancreatic tail is the intraperitoneal portion within the splenorenal ligament.", "🟢 TAIL travels in the SPLENORENAL peritoneal fold.", aid("The pancreatic tail lies in the splenorenal ligament and is the intraperitoneal portion of the pancreas.", "Tail travels in the splenorenal fold.", ["🟢", "🧵"], "Tail and ligament-fold cues retain the peritoneal relation.", "IMAIOS: Splenorenal Ligament", "https://www.imaios.com/en/e-anatomy/anatomical-structures/splenorenal-ligament-1541221084"), "https://www.imaios.com/en/e-anatomy/anatomical-structures/splenorenal-ligament-1541221084", "IMAIOS defines the splenorenal ligament as containing the pancreatic tail, the only intraperitoneal pancreatic portion."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0872-q0048", page: 872, expectedStem: "The blood supply to the pancreas is primarily from which of the following arteries:", expectedOptions: ["Left gastric artery", "Common hepatic artery", "Superior mesenteric artery Inferior mesenteric artery 1%"], stem: "The blood supply to the pancreas is primarily from which of the following arteries:", options: ["Left gastric artery", "Common hepatic artery", "Splenic artery", "Superior mesenteric artery", "Inferior mesenteric artery"], warning: "Source page reviewed, but external anatomy evidence describes arterial supply from splenic, superior mesenteric, and common-hepatic branches; the exact whole-pancreas ‘primarily splenic artery’ formulation is not corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532912/", finding: "NCBI records pancreatic arterial supply from splenic, superior mesenteric, and common-hepatic branches, without corroborating the exact whole-organ primary-splenic formulation." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-29.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
