import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const snapshotPath = path.join(root, "docs", "audit", "anatomy-all-pdf-batch-42-ocr-records.json");
const artifactPath = path.join(root, "docs", "audit", "applied-anatomy-batch-42.json");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel: "Source-confirmed anatomy fact", sourceLabel, sourceUrl });

const restorations = [
  { id: "anatomy-anatomy-all-pdf-p1283-q0180", page: 1283, expectedStem: "ww Which of the following is NOT an anatomical feature that prevents against gastric reflux:", expectedOptions: ["The diaphragmatic pinchcock effect on the oesophagus 4%", "Intra-abdominal pressure which maintains the oesophagus in a state of collapse when empty 15%", "The angle of His formed at the junction of the oesophagus and gastric fundus 6%", "Gastric mucosal rosette-like folds at the gastro-oesophageal junction 10%", "The striated lower oesophageal sphincter muscle"], stem: "Which of the following is NOT an anatomical feature that prevents against gastric reflux:", options: ["The diaphragmatic pinchcock effect on the oesophagus", "Intra-abdominal pressure which maintains the oesophagus in a state of collapse when empty", "The angle of His formed at the junction of the oesophagus and gastric fundus", "Gastric mucosal rosette-like folds at the gastro-oesophageal junction", "The striated lower oesophageal sphincter muscle"], correctOption: 4, fact: "The lower oesophageal sphincter is a smooth-muscle high-pressure zone rather than a distinct striated skeletal-muscle sphincter.", mnemonic: "Lower oesophageal sphincter: smooth pressure zone, not striated muscle.", memoryAid: aid("The lower oesophageal sphincter is a physiological high-pressure zone formed by smooth muscle; the source's striated-muscle option is the exception.", "Lower oesophageal sphincter: smooth pressure zone, not striated muscle.", ["🚫", "💪", "⬇️"], "NCBI Bookshelf: Physiology, Lower Esophageal Sphincter", "https://www.ncbi.nlm.nih.gov/books/NBK557452/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557452/", finding: "NCBI describes the lower oesophageal sphincter as a physiological high-pressure zone; this supports the source key identifying a striated lower sphincter as the exception." },
  { id: "anatomy-anatomy-all-pdf-p1284-q0001", page: 1284, expectedStem: "A70 year old undergoes radical prostatectomy for prostate cancer. Postoperatively he complains of urinary incontinence due to paralysis of the external urethral sphincter. Which of the following nerves was most likely injured during surgery:", expectedOptions: ["Genitofemoral nerve 14%", "Pudendal nerve", "Coccygeal nerve 2% ee", "lliohypogastric nerve 4%"], stem: "A 70 year old undergoes radical prostatectomy for prostate cancer. Postoperatively he complains of urinary incontinence due to paralysis of the external urethral sphincter. Which of the following nerves was most likely injured during surgery:", options: ["Genitofemoral nerve", "Pudendal nerve", "Coccygeal nerve", "Ilioinguinal nerve", "Iliohypogastric nerve"], correctOption: 1, fact: "The pudendal nerve supplies the voluntary external urethral sphincter through somatic motor fibres from S2–S4.", mnemonic: "Pudendal keeps the external sphincter under voluntary control.", memoryAid: aid("Pudendal motor fibres supply the external urethral sphincter; the source key is pudendal nerve.", "Pudendal keeps the external sphincter under voluntary control.", ["🩺", "🔒", "S2–S4"], "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557605/", finding: "The source key is pudendal nerve; the restored options repair OCR loss and preserve the source's five-option order." },
  { id: "anatomy-anatomy-all-pdf-p1286-q0003", page: 1286, expectedStem: "The iliohypogastric nerve is formed from the anterior rami of:", expectedOptions: ["et 4885 Ec a", "L4 1%"], stem: "The iliohypogastric nerve is formed from the anterior rami of:", options: ["L1", "L1 - L2", "L2", "L2 - L3", "L4"], correctOption: 0, fact: "The source key is L1. Anatomical references describe the iliohypogastric nerve as commonly arising from L1, with a T12 contribution or other variation in some individuals.", mnemonic: "Iliohypogastric: think L1, with T12 variation.", memoryAid: aid("The examination key is L1; anatomical descriptions may include T12–L1 contributions, so this is not an exclusive universal rule.", "Iliohypogastric: think L1, with T12 variation.", ["1️⃣", "🧠", "↕️"], "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557605/", finding: "NCBI gives a T12–L1 origin and documents variation; the displayed source key is L1 and is retained with a variation caveat." },
  { id: "anatomy-anatomy-all-pdf-p1287-q0004", page: 1287, expectedStem: "Which of the following best describes the regions of the abdomen that the liver normally occupies:", expectedOptions: ["Left hypochondrium and epigastric region 1%", "Right hypochondrium and right flank 6%", "Right hypochondrium and umbilical region", "Right hypochondrium, epigastric region and left hypochondrium"], stem: "Which of the following best describes the regions of the abdomen that the liver normally occupies:", options: ["Left hypochondrium and epigastric region", "Right hypochondrium and right flank", "Right hypochondrium and umbilical region", "Right hypochondrium, epigastric region and left hypochondrium", "Right hypochondrium, epigastric region and umbilicus"], correctOption: 3, fact: "The liver normally occupies the right hypochondrium and epigastric region and extends into the left hypochondrium.", mnemonic: "Liver: right upper, crosses epigastrium, reaches left.", memoryAid: aid("The liver spans the right hypochondrium and epigastrium and extends into the left hypochondrium.", "Liver: right upper, crosses epigastrium, reaches left.", ["🫀", "➡️", "⬅️"], "NCBI Bookshelf: Anatomy, Abdomen and Pelvis: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553104/", finding: "NCBI's nine-region summary lists the liver in the right hypochondrium and epigastrium; the source explanation and key add extension into the left hypochondrium." },
  { id: "anatomy-anatomy-all-pdf-p1288-q0005", page: 1288, expectedStem: "ww A patient with known inflammatory bowel disease presents to ED complaining of severe abdominal pain and diarrhoea. Imaging shows a flare up primarily affecting the rectum. Which of the following nerves is most likely responsible for transmission of pain from the rectum:", expectedOptions: ["Pelvic splanchnic nerves", "Lumbar splanchnic nerves", "Sacral splanchnic nerves 9%", "Vagus nerves 1%"], stem: "A patient with known inflammatory bowel disease presents to ED complaining of severe abdominal pain and diarrhoea. Imaging shows a flare up primarily affecting the rectum. Which of the following nerves is most likely responsible for transmission of pain from the rectum:", options: ["Pelvic splanchnic nerves", "Lumbar splanchnic nerves", "Sacral splanchnic nerves", "Vagus nerves", "Pudendal nerves"], correctOption: 0, fact: "For the source's intended hindgut visceral-afferent formulation, pelvic splanchnic nerves carry visceral afferents from the rectum and also provide parasympathetic supply; the exact pathway can vary with rectal level and pain type.", mnemonic: "Pelvic splanchnics: S2–S4 to hindgut and pelvic viscera.", memoryAid: aid("Pelvic splanchnic nerves carry visceral afferents from the rectum and parasympathetic fibres to hindgut/pelvic organs; do not read this as an exclusive route for every rectal pain fibre.", "Pelvic splanchnics: S2–S4 to hindgut and pelvic viscera.", ["🧠", "S2–S4", "🫃"], "NCBI Bookshelf: Anatomy, Abdomen and Pelvis, Splanchnic Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK560504/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK560504/", finding: "NCBI states that pelvic splanchnic nerves carry visceral afferents and supply the rectum; the caveat preserves level-dependent nuance." },
  { id: "anatomy-anatomy-all-pdf-p1289-q0006", page: 1289, expectedStem: "ww A19 year old male is brought to ED having sustained a handlebar injury with blunt trauma to his upper abdomen whilst riding his scooter. Which of the following is the most commonly injured organ:", expectedOptions: ["Pancreas 8%", "Transverse colon 5%", "Spleen", "Duodenum", "Kidney 1%"], stem: "A 19 year old male is brought to ED having sustained a handlebar injury with blunt trauma to his upper abdomen whilst riding his scooter. Which of the following is the most commonly injured organ:", options: ["Pancreas", "Transverse colon", "Spleen", "Duodenum", "Kidney"], correctOption: 2, fact: "The spleen is the most frequently injured visceral organ in blunt abdominal trauma; the source explanation also recognises the liver, and the single-best-answer key is spleen because liver is not an option.", mnemonic: "Blunt abdomen: spleen bleeds readily.", memoryAid: aid("The spleen is highly vascular and is the most frequently injured visceral organ in blunt abdominal trauma; this option set excludes liver.", "Blunt abdomen: spleen bleeds readily.", ["🩸", "🛴", "⬅️"], "NCBI Bookshelf: Splenic Rupture", "https://www.ncbi.nlm.nih.gov/books/NBK525951/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK525951/", finding: "NCBI identifies the spleen as the most frequently injured visceral organ in blunt abdominal trauma; the source explanation also names liver." },
  { id: "anatomy-anatomy-all-pdf-p1293-q0007", page: 1293, expectedStem: "w Which of the following lies immediately medial to the second part of the duodenum:", expectedOptions: ["Transverse colon 2%", "Spleen 1%", "Right kidney 3%", "Head of the pancreas", "Stomach 3%"], stem: "Which of the following lies immediately medial to the second part of the duodenum:", options: ["Transverse colon", "Spleen", "Right kidney", "Head of the pancreas", "Stomach"], correctOption: 3, fact: "The head of the pancreas lies immediately medial to the second part of the duodenum.", mnemonic: "D2 hugs the pancreatic head.", memoryAid: aid("The descending second part of the duodenum lies lateral to the pancreatic head, which is therefore immediately medial to it.", "D2 hugs the pancreatic head.", ["2️⃣", "🫂", "🟡"], "NCBI Bookshelf: Anatomy, Abdomen and Pelvis: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553104/", finding: "NCBI lists the pancreatic head and second to fourth duodenal parts among retroperitoneal abdominal structures; the source explanation states D2 lies lateral to the pancreatic head." },
  { id: "anatomy-anatomy-all-pdf-p1294-q0008", page: 1294, expectedStem: "A 64 year old man with known liver cirrhosis secondary to chronic alcohol abuse presents to ED vomiting profuse bright red blood. Endoscopy demonstrates ruptured oesophageal varices. Which of the following veins forms a portosystemic anastomosis with caval veins to form the varices:", expectedOptions: ["Right gastric vein 10%", "Splenic vein 6%", "Left gastric vein", "Left gastro-omental vein 2%"], stem: "A 64 year old man with known liver cirrhosis secondary to chronic alcohol abuse presents to ED vomiting profuse bright red blood. Endoscopy demonstrates ruptured oesophageal varices. Which of the following veins forms a portosystemic anastomosis with caval veins to form the varices:", options: ["Right gastric vein", "Splenic vein", "Left gastric vein", "Left hepatic vein", "Left gastro-omental vein"], correctOption: 2, fact: "The left gastric vein anastomoses with oesophageal veins that drain to the azygos system, forming the portal-systemic collateral pathway involved in oesophageal varices.", mnemonic: "Left gastric meets oesophageal veins, then azygos.", memoryAid: aid("Portal left gastric vein connects with oesophageal veins and the caval azygos system at the gastro-oesophageal junction.", "Left gastric meets oesophageal veins, then azygos.", ["🩸", "🔗", "⬆️"], "PMC: Collateral Pathways in Portal Hypertension", "https://pmc.ncbi.nlm.nih.gov/articles/PMC3940321/"), sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3940321/", finding: "The PMC review directly describes left gastric vein anastomosis with oesophageal veins draining to the azygos vein." },
  { id: "anatomy-anatomy-all-pdf-p1297-q0009", page: 1297, expectedStem: "iv p ww Which of the following muscles lies adjacent to the lateral border of the quadratus lumborum muscle:", expectedOptions: ["Rectus abdominis muscle 3% ml (x) lliacus muscle 16%", "Psoas major muscle 34%", "Transversus abdominis muscle", "Psoas minor muscle 3%"], stem: "Which of the following muscles lies adjacent to the lateral border of the quadratus lumborum muscle:", options: ["Rectus abdominis muscle", "Iliacus muscle", "Psoas major muscle", "Transversus abdominis muscle", "Psoas minor muscle"], correctOption: 3, fact: "The transversus abdominis muscle lies along the lateral border of quadratus lumborum; psoas major overlaps it medially.", mnemonic: "Quadratus: psoas medial, transversus lateral.", memoryAid: aid("Quadratus lumborum lies between medial psoas and lateral transversus abdominis.", "Quadratus: psoas medial, transversus lateral.", ["◀️", "⬛", "▶️"], "NCBI Bookshelf: Posterior Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK557605/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557605/", finding: "NCBI states that quadratus lumborum is between medial psoas and lateral transversus abdominis; the stale OCR key 2 is corrected to source-displayed key 3." },
  { id: "anatomy-anatomy-all-pdf-p1298-q0010", page: 1298, expectedStem: "ww Which of the following nerves transmits the parasympathetic supply to the stomach:", expectedOptions: ["Greater thoracic splanchnic nerves 6%", "Lesser thoracic splanchnic nerves 7%", "Lumbar splanchnic nerves 5%", "Pelvic splanchnic nerves 2%"], stem: "Which of the following nerves transmits the parasympathetic supply to the stomach:", options: ["Greater thoracic splanchnic nerves", "Lesser thoracic splanchnic nerves", "Lumbar splanchnic nerves", "Pelvic splanchnic nerves", "Vagus nerves"], correctOption: 4, fact: "The parasympathetic supply to the stomach is carried by the vagus nerve.", mnemonic: "Vagus visits the foregut.", memoryAid: aid("The vagus nerve provides parasympathetic innervation to the stomach as a foregut organ.", "Vagus visits the foregut.", ["🧠", "🍽️", "⬇️"], "NCBI Bookshelf: Anatomy, Abdomen and Pelvis: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553104/", finding: "NCBI states that the vagus nerve parasympathetically innervates the foregut, including the stomach; the missing fifth option and displayed key are restored." }
];

const parse = (text) => { const token = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = text.indexOf(token) + token.length; const end = text.indexOf("];", start); if (start < token.length || end < 0) throw new Error("OCR draft export not found"); return { start, end, drafts: JSON.parse(text.slice(start, end + 1)) }; };
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const record = (draft) => ({ stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [], explanation: draft.explanation ?? "", learningNote: draft.learningNote ?? "", highYieldNote: draft.highYieldNote ?? "", mnemonic: draft.mnemonic ?? "", memoryAid: draft.memoryAid ?? null });
const check = (live, snapshot, item) => { if (!live || !snapshot || live.id !== item.id || snapshot.id !== item.id || live.sourcePage !== item.page || snapshot.sourcePage !== item.page || live.stem !== item.expectedStem || snapshot.stem !== item.expectedStem || !same(live.options, item.expectedOptions) || !same(snapshot.options, item.expectedOptions)) throw new Error(`Immutable literal drift check failed: ${item.id}`); };

const text = await readFile(bankPath, "utf8");
const parsed = parse(text);
const snapshots = new Map(JSON.parse(await readFile(snapshotPath, "utf8")).records.map((item) => [item.id, item]));
const live = new Map(parsed.drafts.map((item) => [item.id, item]));
const applied = [];
for (const item of restorations) { const draft = live.get(item.id); check(draft, snapshots.get(item.id), item); const before = record(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.fact, learningNote: item.fact, highYieldNote: item.fact, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); delete draft.approved; applied.push({ id: item.id, sourcePage: item.page, before, after: record(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${text.slice(0, parsed.start)}${JSON.stringify(parsed.drafts)}${text.slice(parsed.end + 1)}`);
await mkdir(path.dirname(artifactPath), { recursive: true });
await writeFile(artifactPath, `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted: [], automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.length, restricted: 0, automaticApproval: false }, null, 2));
