import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const snapshotPath = path.join(root, "docs", "audit", "anatomy-all-pdf-batch-40-ocr-records.json");
const artifactPath = path.join(root, "docs", "audit", "applied-anatomy-batch-40.json");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel: "Source-confirmed anatomy fact", sourceLabel, sourceUrl });
const restorations = [
  { id: "anatomy-anatomy-all-pdf-p1241-q0158", page: 1241, expectedStem: "ww The oesophagus passes through the diaphragm at which vertebral level:", expectedOptions: ["T8 6%", "19 2% () HO 86%", "™m 3%", "112 3%"], stem: "The oesophagus passes through the diaphragm at which vertebral level:", options: ["T8", "T9", "T10", "T11", "T12"], correctOption: 2, fact: "The oesophagus traverses the oesophageal hiatus in the diaphragm at approximately T10.", mnemonic: "IVC 8, oesophagus 10, aorta 12.", memoryAid: aid("The oesophageal hiatus is at approximately T10.", "IVC 8, oesophagus 10, aorta 12.", ["8️⃣", "🔟", "1️⃣2️⃣"], "NCBI Bookshelf: Anatomy, Thorax, Esophagus", "https://www.ncbi.nlm.nih.gov/books/NBK482513/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482513/", finding: "NCBI states that the oesophagus passes through the oesophageal hiatus at approximately T10." },
  { id: "anatomy-anatomy-all-pdf-p1244-q0159", page: 1244, expectedStem: "ww A direct inguinal hernia is due to weakness in which of the following layers:", expectedOptions: ["External oblique aponeurosis 14%", "Transversalis fascia", "Internal oblique muscle 5%", "Lacunar ligament 1%"], stem: "A direct inguinal hernia is due to weakness in which of the following layers:", options: ["External oblique aponeurosis", "Transversalis fascia", "Transversus abdominis muscle", "Internal oblique muscle", "Lacunar ligament"], correctOption: 1, fact: "A direct inguinal hernia passes through acquired weakness in the posterior wall of the inguinal canal, where transversalis fascia is the key layer.", mnemonic: "Direct goes through a defective posterior wall.", memoryAid: aid("Direct inguinal hernia reflects posterior-wall weakness, particularly at transversalis fascia.", "Direct goes through a defective posterior wall.", ["➡️", "🧱"], "NCBI Bookshelf: Inguinal Region", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470204/", finding: "NCBI describes direct hernia through posterior inguinal-canal wall weakness and identifies the transversalis layer in the posterior wall." },
  { id: "anatomy-anatomy-all-pdf-p1246-q0160", page: 1246, expectedStem: "ww The following structures are all found in the spermatic cord EXCEPT for the:", expectedOptions: ["Pampiniform plexus of veins 6%", "Cremasteric artery 5%", "Remnants of the processus vaginalis 6%", "Pudendal nerve", "Testicular artery 6%"], stem: "The following structures are all found in the spermatic cord EXCEPT for the:", options: ["Pampiniform plexus of veins", "Cremasteric artery", "Remnants of the processus vaginalis", "Pudendal nerve", "Testicular artery"], correctOption: 3, fact: "The pudendal nerve is an S2–S4 perineal nerve rather than a spermatic-cord content.", mnemonic: "Pudendal is perineal, not corded.", memoryAid: aid("The pudendal nerve arises from S2–S4 and runs through the perineum, not within the spermatic cord.", "Pudendal is perineal, not corded.", ["S2️⃣", "S4️⃣"], "NCBI Bookshelf: Pudendal Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK554736/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554736/", finding: "NCBI describes the pudendal nerve as an S2-S4 nerve that exits the pelvis and runs through the pudendal canal." },
  { id: "anatomy-anatomy-all-pdf-p1249-q0161", page: 1249, expectedStem: "wy A565 year old woman presents to ED complaining of abdominal pain and profuse vomiting. Imaging shows part of the bowel is being compressed between the abdominal aorta and the superior mesenteric artery. Which part of the bowel is most likely being affected:", expectedOptions: ["First part of the duodenum 17% (/) Third part of the duodenum 48%", "lleum 4%", "Jejunum 7%"], stem: "A 55 year old woman presents to ED complaining of abdominal pain and profuse vomiting. Imaging shows part of the bowel is being compressed between the abdominal aorta and the superior mesenteric artery. Which part of the bowel is most likely being affected:", options: ["First part of the duodenum", "Second part of the duodenum", "Third part of the duodenum", "Ileum", "Jejunum"], correctOption: 2, fact: "Superior mesenteric artery syndrome compresses the third part of the duodenum between the aorta posteriorly and the superior mesenteric artery anteriorly.", mnemonic: "SMA squeezes D3 against the aorta.", memoryAid: aid("The third duodenum lies in the aortomesenteric angle and is compressed in SMA syndrome.", "SMA squeezes D3 against the aorta.", ["3️⃣", "🗜️"], "NCBI Bookshelf: Superior Mesenteric Artery Syndrome", "https://www.ncbi.nlm.nih.gov/books/NBK482209/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482209/", finding: "NCBI states that SMA syndrome compresses the third part of the duodenum between the aorta and SMA." },
  { id: "anatomy-anatomy-all-pdf-p1250-q0162", page: 1250, expectedStem: "The inferior vena cava leaves the abdomen at which of the following vertebral levels:", expectedOptions: ["T6 16%", "T10 49%", "u 2%"], stem: "The inferior vena cava leaves the abdomen at which of the following vertebral levels:", options: ["T6", "T8", "T10", "T12", "L1"], correctOption: 1, fact: "The inferior vena cava passes through the central tendon of the diaphragm at approximately T8.", mnemonic: "IVC at 8, oesophagus at 10, aorta at 12.", memoryAid: aid("The IVC crosses the diaphragm through the caval opening at approximately T8.", "IVC at 8, oesophagus at 10, aorta at 12.", ["8️⃣", "🫀"], "NCBI Bookshelf: Inferior Vena Cava", "https://www.ncbi.nlm.nih.gov/books/NBK482353/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482353/", finding: "NCBI states that the IVC passes through the central diaphragm tendon around T8." },
  { id: "anatomy-anatomy-all-pdf-p1254-q0163", page: 1254, expectedStem: "Abdomen A75 year old man presents to ED complaining of abdominal pain radiating to his back, anorexia and weight loss. Imaging shows a large tumour of the neck of the pancreas. Which of the following structures is most likely compressed by the tumour:", expectedOptions: ["Inferior mesenteric artery 7h", "Ureter", "Coeliac trunk 7h"], stem: "A 75 year old man presents to ED complaining of abdominal pain radiating to his back, anorexia and weight loss. Imaging shows a large tumour of the neck of the pancreas. Which of the following structures is most likely compressed by the tumour:", options: ["Inferior mesenteric artery", "Portal vein", "First part of the duodenum", "Ureter", "Coeliac trunk"], correctOption: 1, fact: "The portal vein forms posterior to the pancreatic neck from the splenic and superior mesenteric veins, making it vulnerable to a neck mass.", mnemonic: "Portal vein sits behind the pancreatic neck.", memoryAid: aid("The portal vein forms behind the neck of the pancreas from the splenic and superior mesenteric veins.", "Portal vein sits behind the pancreatic neck.", ["🔙", "🩸"], "PMC: Portal Venous System and Its Tributaries", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4062210/"), sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4062210/", finding: "A peer-reviewed review states that the portal vein forms behind the neck of the pancreas." },
  { id: "anatomy-anatomy-all-pdf-p1255-q0164", page: 1255, expectedStem: "Abdomen The following structures are all found in the spermatic cord except for the:", expectedOptions: ["Ductus deferens Branch of the inferior vesical artery 16% Cremasteric vein 2% Branch of the genitofemoral nerve Th"], stem: "The following structures are all found in the spermatic cord except for the:", options: ["Ductus deferens", "Branch of the inferior vesical artery", "Cremasteric vein", "Branch of the genitofemoral nerve", "Inferior epigastric artery"], correctOption: 4, fact: "The spermatic cord contains the ductus deferens, vessels, and nerves; the deferential artery comes from the inferior vesical artery, while the inferior epigastric artery itself is not a cord content.", mnemonic: "Cord carries branches, not the inferior epigastric trunk.", memoryAid: aid("The spermatic cord contains the ductus deferens, vessels, and nerves; the inferior epigastric artery is not itself a cord content.", "Cord carries branches, not the inferior epigastric trunk.", ["🧵", "❌"], "NCBI Bookshelf: Acute Scrotum Pain", "https://www.ncbi.nlm.nih.gov/books/NBK470335/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470335/", finding: "NCBI identifies deferential and cremasteric arterial branches and describes vascular structures, vas deferens, and nerves within the spermatic cord." },
  { id: "anatomy-anatomy-all-pdf-p1258-q0167", page: 1258, expectedStem: "Abdomen The sacrospinous ligament spans between which of the following structures:", expectedOptions: ["The anterior superior iliac spine to the sacrum and coccyx (x) jac spine to the sacrum and coccyx 20%", "The ischial tuberosity to the sacrum and coccyx \"1%", "The pubic arch to the sacrum and coccyx"], stem: "The sacrospinous ligament spans between which of the following structures:", options: ["The anterior superior iliac spine to the sacrum and coccyx", "The posterior superior iliac spine to the sacrum and coccyx", "The ischial tuberosity to the sacrum and coccyx", "The ischial spine to the sacrum and coccyx", "The pubic arch to the sacrum and coccyx"], correctOption: 3, fact: "The sacrospinous ligament has a broad attachment to the lower sacrum and upper coccyx and narrows to the ischial spine.", mnemonic: "SacroSPINOUS reaches the ischial SPINE.", memoryAid: aid("The sacrospinous ligament attaches between the lower sacrum and upper coccyx and the ischial spine.", "SacroSPINOUS reaches the ischial SPINE.", ["📍", "🦴"], "NCBI Bookshelf: Pelvic Ligaments", "https://www.ncbi.nlm.nih.gov/books/NBK493215/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK493215/", finding: "NCBI states that the sacrospinous ligament attaches from the lower sacrum and upper coccyx to the ischial spine." }
];
const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p1256-q0165", page: 1256, expectedStem: "Abdomen The quadratus |umborum muscle is innervated by which of the following:", expectedOptions: ["lliohypogastric nerve", "Anterior rami of L2 - L4", "Anterior rami of T9 - 712"], stem: "The quadratus lumborum muscle is innervated by which of the following:", options: ["Iliohypogastric nerve", "Ilioinguinal nerve", "Anterior rami of L2 - L4", "Anterior rami of T9 - T12", "Anterior rami of T12 - L4"], warning: "Source page reviewed, but authoritative anatomy names the 12th thoracic intercostal, iliohypogastric, and ilioinguinal nerves rather than uniquely corroborating the source's broad T12-L4 range; no answer is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK535407/", finding: "NCBI names the 12th thoracic intercostal, iliohypogastric, and ilioinguinal nerves for quadratus lumborum innervation." },
  { id: "anatomy-anatomy-all-pdf-p1257-q0166", page: 1257, expectedStem: "Abdomen Visceral afferent fibres from the pancreas travel to which of the following spinal cord levels:", expectedOptions: ["11-12", "T4-16 oe", "q0= 112 @)"], stem: "Visceral afferent fibres from the pancreas travel to which of the following spinal cord levels:", options: ["T1 - T2", "T4 - T6", "T6 - T10", "T10 - T12", "T12 - L2"], warning: "Source page reviewed, but a pancreas-specialist reference places pancreatic spinal afferent neuron cell bodies at T6-L2, conflicting with the source's unqualified T6-T10 visceral-afferent range; no answer is inferred.", sourceUrl: "https://pancreapedia.org/reviews/neural-control-of-pancreas", finding: "Pancreapedia reports pancreatic spinal afferent neuron cell bodies in T6-L2 dorsal root ganglia." }
];
const parse = (text) => { const token = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = text.indexOf(token) + token.length; const end = text.indexOf("];", start); if (start < token.length || end < 0) throw new Error("OCR draft export not found"); return { start, end, drafts: JSON.parse(text.slice(start, end + 1)) }; };
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const record = (draft) => ({ stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [], explanation: draft.explanation ?? "", learningNote: draft.learningNote ?? "", highYieldNote: draft.highYieldNote ?? "", mnemonic: draft.mnemonic ?? "", memoryAid: draft.memoryAid ?? null });
const check = (live, snapshot, item) => { if (!live || !snapshot || live.id !== item.id || snapshot.id !== item.id || live.sourcePage !== item.page || snapshot.sourcePage !== item.page || live.stem !== item.expectedStem || snapshot.stem !== item.expectedStem || !same(live.options, item.expectedOptions) || !same(snapshot.options, item.expectedOptions)) throw new Error(`Immutable literal drift check failed: ${item.id}`); };
const text = await readFile(bankPath, "utf8"); const parsed = parse(text); const snapshots = new Map(JSON.parse(await readFile(snapshotPath, "utf8")).records.map((item) => [item.id, item])); const live = new Map(parsed.drafts.map((item) => [item.id, item])); const applied = []; const restricted = [];
for (const item of restorations) { const draft = live.get(item.id); check(draft, snapshots.get(item.id), item); const before = record(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.fact, learningNote: item.fact, highYieldNote: item.fact, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); delete draft.approved; applied.push({ id: item.id, sourcePage: item.page, before, after: record(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
for (const item of restrictions) { const draft = live.get(item.id); check(draft, snapshots.get(item.id), item); const before = record(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] }); delete draft.memoryAid; delete draft.approved; restricted.push({ id: item.id, sourcePage: item.page, before, after: record(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${text.slice(0, parsed.start)}${JSON.stringify(parsed.drafts)}${text.slice(parsed.end + 1)}`); await mkdir(path.dirname(artifactPath), { recursive: true }); await writeFile(artifactPath, `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`); console.log(JSON.stringify({ restored: applied.length, restricted: restricted.length, automaticApproval: false }, null, 2));
