import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });
const x = (id, page, expectedStem, expectedOptions, stem, options, explanation, warning, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, explanation, warning, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0638-q0030", 638, "ww The abdominal aorta terminates as which of the following:", ["Internal and external iliac arteries", "External iliac and femoral artery 2%", "Right and left common iliac arteries", "Superior and inferior epigastric arteries 0%", "Internal iliac and femoral artery 2%"], "The abdominal aorta terminates as which arteries?", ["Internal and external iliac arteries", "External iliac and femoral artery", "Right and left common iliac arteries", "Superior and inferior epigastric arteries", "Internal iliac and femoral artery"], 2, "The abdominal aorta bifurcates at approximately L4 into the right and left common iliac arteries. Each common iliac artery subsequently divides into internal and external iliac arteries.", "Aorta ends as right and left common iliac arteries.", "The abdominal aorta becomes the right and left common iliac arteries at L4.", "🔀 AORTA splits into two COMMON iliacs.", aid("The abdominal aorta bifurcates into the right and left common iliac arteries.", "Aorta splits into two common iliacs.", ["🔀", "2️⃣"], "Split and two cues retain the terminal bifurcation.", "NCBI Bookshelf: Posterior Abdominal Wall Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK532972/"), "https://www.ncbi.nlm.nih.gov/books/NBK532972/", "NCBI states that the abdominal aorta bifurcates at L4 into right and left common iliac arteries."),
  r("anatomy-anatomy-all-pdf-p0639-q0031", 639, "ww A79 year old patient, with a history of AF, presents to ED complaining of sudden onset severe abdominal pain. Imaging shows occlusion of the superior mesenteric artery. Which of the following structures is most likely affected:", ["Stomach 1% (x) First part of the duodenum 10%", "Jejunum and ileum", "Splenic flexure 7%", "Rectum 1%"], "A patient with atrial fibrillation has sudden severe abdominal pain and superior mesenteric artery occlusion. Which structures are most likely affected?", ["Stomach", "First part of the duodenum", "Jejunum and ileum", "Splenic flexure", "Rectum"], 2, "The superior mesenteric artery supplies the midgut and gives jejunal and ileal branches. Occlusion can therefore cause ischaemia of the jejunum and ileum.", "SMA occlusion threatens jejunum and ileum.", "Jejunal and ileal branches arise from the superior mesenteric artery.", "🩸 SMA feeds JEJUNUM + ILEUM.", aid("The superior mesenteric artery gives jejunal and ileal branches that supply the small bowel.", "SMA feeds jejunum and ileum.", ["🩸", "〰️"], "Blood and bowel-loop cues retain the vascular territory.", "NCBI Bookshelf: Superior Mesenteric Artery", "https://www.ncbi.nlm.nih.gov/books/NBK519560/"), "https://www.ncbi.nlm.nih.gov/books/NBK519560/", "NCBI describes jejunal and ileal branches arising from the superior mesenteric artery."),
  r("anatomy-anatomy-all-pdf-p0640-q0032", 640, "wy Posteriorly the spleen lies in the region of which of the following:", ["Ribs 7 and 8 2%", "Ribs 8 - 10 5% (v Ribs 9-11 35%", "Ribs 10 - 12", "Below the costal margin 2%"], "Posteriorly, the spleen lies in the region of which ribs?", ["Ribs 7 and 8", "Ribs 8–10", "Ribs 9–11", "Ribs 10–12", "Below the costal margin"], 2, "The spleen lies in the left hypochondrium between the diaphragm and gastric fundus and typically spans the ninth to 11th ribs.", "Spleen projects beneath left ribs 9–11.", "The normal spleen typically spans ribs 9–11.", "🩻 9️⃣–1️⃣1️⃣ protect the SPLEEN.", aid("The spleen typically spans the ninth through 11th ribs.", "Nine to eleven protect the spleen.", ["🩻", "9️⃣", "1️⃣1️⃣"], "Radiograph and rib-number cues retain the surface projection.", "NCBI Bookshelf: Spleen", "https://www.ncbi.nlm.nih.gov/books/NBK482235/"), "https://www.ncbi.nlm.nih.gov/books/NBK482235/", "NCBI states that the spleen typically spans ribs nine through 11."),
  r("anatomy-anatomy-all-pdf-p0641-q0033", 641, "wy The ductus deferens is derived from which of the following structures:", ["Tunica vaginalis 17%", "Ejaculatory ducts 4%", "Seminal vesicle 8% (/) Epididymis fe", "Rete testis 3%"], "The ductus deferens continues from which structure?", ["Tunica vaginalis", "Ejaculatory ducts", "Seminal vesicle", "Epididymis", "Rete testis"], 3, "The ductus deferens begins as a continuation of the tail of the epididymis and transports sperm toward the ejaculatory duct.", "Ductus deferens starts at the epididymal tail.", "The ductus deferens begins as a continuation of the tail of the epididymis.", "➡️ EPIDIDYMIS tail becomes the DUCTUS.", aid("The ductus deferens begins as a continuation of the epididymal tail.", "Epididymis tail becomes the ductus.", ["➡️", "🔚"], "Direction and tail-end cues retain the anatomical continuity.", "NCBI Bookshelf: Testes", "https://www.ncbi.nlm.nih.gov/books/NBK470201/"), "https://www.ncbi.nlm.nih.gov/books/NBK470201/", "NCBI states that ductus deferens begins as a continuation of the epididymal tail."),
  r("anatomy-anatomy-all-pdf-p0643-q0034", 643, "hd A patient presents following a fall. Imaging shows damage to the L1 nerve root. Which of the following muscles are most likely to be affected:", ["Transversus abdominis and rectus abdominis muscles 5%", "Rectus abdominis and external oblique muscles 55%", "Gluteus medius and minimus muscles 71%", "Transversus abdominis and internal oblique muscles", "Internal and external oblique muscles"], "A patient has damage involving the L1-derived ilioinguinal nerve. Which muscles are most likely affected?", ["Transversus abdominis and rectus abdominis muscles", "Rectus abdominis and external oblique muscles", "Gluteus medius and minimus muscles", "Transversus abdominis and internal oblique muscles", "Internal and external oblique muscles"], 3, "The ilioinguinal nerve is derived from L1 and provides motor innervation to transversus abdominis and internal oblique.", "Ilioinguinal from L1 supplies internal oblique and transversus abdominis.", "L1-derived ilioinguinal nerve motor supply includes internal oblique and transversus abdominis.", "1️⃣L1 = INNER oblique + TRANSVERSUS.", aid("The ilioinguinal nerve provides motor innervation to internal oblique and transversus abdominis.", "L1 means inner oblique plus transversus.", ["1️⃣", "💪"], "L1 and muscle cues retain the motor pair.", "NCBI Bookshelf: Ilioinguinal Neuralgia", "https://www.ncbi.nlm.nih.gov/books/NBK538256/"), "https://www.ncbi.nlm.nih.gov/books/NBK538256/", "NCBI identifies motor innervation of internal oblique and transversus abdominis by the ilioinguinal nerve."),
  r("anatomy-anatomy-all-pdf-p0647-q0036", 647, "The kidneys extend between which of the following vertebral levels:", ["19-112 os", "12-1", "LIES 9%", "m2-13", "L2-L5 ig"], "The kidneys normally extend between which vertebral levels?", ["T9–T12", "T12–L1", "L1–L3", "T12–L3", "L2–L5"], 3, "The kidneys are paired retroperitoneal organs positioned between T12 and L3. The right kidney is typically slightly lower because of the liver.", "Normal renal level: T12 to L3.", "Both kidneys are normally positioned between the transverse processes of T12 and L3.", "🫘 T12➡️L3 marks kidney territory.", aid("The kidneys normally lie between T12 and L3.", "Twelve to three marks kidney territory.", ["🫘", "🔢"], "Kidney bean and number cues retain the vertebral range.", "NCBI Bookshelf: Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385/"), "https://www.ncbi.nlm.nih.gov/books/NBK482385/", "NCBI places normal kidneys between T12 and L3."),
  r("anatomy-anatomy-all-pdf-p0649-q0038", 649, "ww Regarding the uterine tubes, which of the following statements is CORRECT:", ["The uterine tubes open into the peritoneal cavity lateral to the ovaries.", "Each uterine tube is approximately 5 cm long. 4%", "The opening of the uterine tube is formed by the ampulla. 56%", "The infundibulum is the narrowest part of the uterine tube. 9%", "Ectopic pregnancies occur most commonly in the isthmus of the uterine tube. 8%"], "Regarding the uterine tubes, which statement is correct?", ["The uterine tubes open into the peritoneal cavity lateral to the ovaries.", "Each uterine tube is approximately 5 cm long.", "The opening of the uterine tube is formed by the ampulla.", "The infundibulum is the narrowest part of the uterine tube.", "Ectopic pregnancies occur most commonly in the isthmus of the uterine tube."], 0, "The lateral infundibulum of the uterine tube ends in an abdominal ostium that opens into the peritoneal cavity near the ovary. Fimbriae help capture the released oocyte.", "Infundibulum opens into peritoneal cavity near ovary.", "The distal infundibulum ends at an abdominal ostium opening into the peritoneal cavity near the ovary.", "🫧➡️🥚 Tube opens into PERITONEUM by ovary.", aid("The infundibulum ends at an abdominal ostium opening into the peritoneal cavity near the ovary.", "Tube opens into peritoneum by ovary.", ["🫧", "🥚"], "Peritoneal-cavity and oocyte cues retain the lateral opening.", "NCBI Bookshelf: Fallopian Tube", "https://www.ncbi.nlm.nih.gov/books/NBK547660/"), "https://www.ncbi.nlm.nih.gov/books/NBK547660/", "NCBI describes infundibular abdominal ostium opening into the peritoneal cavity near the ovary.")
];
const restrictions = [
  x("anatomy-anatomy-all-pdf-p0634-q0029", 634, "ww Which of the following structures is NOT a posterior relation of the transverse colon:", ["Second part of duodenum 7%", "Head of pancreas 7% (x) pper end of mesentery 8%", "Duodenojejunal flexure 57% (/) spleen 21%"], "Which structure is NOT a posterior relation of the transverse colon?", ["Second part of duodenum", "Head of pancreas", "Upper end of mesentery", "Duodenojejunal flexure", "Spleen"], "The source page marks the spleen. The reviewed external source does not provide the exact posterior-relation list needed to validate this unique exclusion, so the record is excluded from answer learning.", "Source page reviewed, but external evidence does not uniquely corroborate the exact posterior-relation exclusion. This record remains excluded from answer learning.", "https://www.ncbi.nlm.nih.gov/books/NBK470577/", "NCBI large-intestine anatomy does not furnish the source's exact posterior-relation list."),
  x("anatomy-anatomy-all-pdf-p0644-q0035", 644, "ww The cutaneous supply of the scrotum is derived primarily from which of the following spinal nerve roots.", ["m0 - 11 6%", "L2-L4 9%", "$1-S4 12%", "i4,s2-s3 se"], "The cutaneous supply of the scrotum is derived primarily from which spinal nerve roots?", ["T10–L1", "L5, S1", "L2–L4", "S1–S4", "L1, S2–S3"], "The source page marks L1, S2–S3. NCBI identifies four contributing nerves and gives L1–L2 for anterior genitofemoral supply, so the exact selected root combination is not sufficiently corroborated.", "Source page reviewed, but the exact L1, S2–S3 scrotal root combination is not externally corroborated. This record remains excluded from answer learning.", "https://www.ncbi.nlm.nih.gov/books/NBK549893/", "NCBI lists four scrotal contributors and L1-L2 anterior genitofemoral supply, not the exact marked root set."),
  x("anatomy-anatomy-all-pdf-p0648-q0037", 648, "ww The body of the pancreas lies at which of the following vertebral levels:", ["112 ms", "e 26%", "L3 3%"], "The body of the pancreas lies at which vertebral level?", ["T11", "T12", "L1", "L2", "L3"], "The source page marks L1. NCBI describes the pancreas spanning L1–L2 and specifically states that the pancreatic body passes over L2. This record is therefore excluded from answer learning.", "Source page reviewed, but external evidence conflicts with the isolated L1 pancreatic-body key. This record remains excluded from answer learning.", "https://www.ncbi.nlm.nih.gov/books/NBK532912/", "NCBI describes pancreatic body passing over L2 while pancreas overall crosses L1-L2.")
];
function parse(source) { const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = source.indexOf(prefix); const a = start + prefix.length; const e = source.indexOf("];", a); if (start < 0 || e < 0) throw new Error("OCR draft export not found"); return { a, e, drafts: JSON.parse(source.slice(a, e + 1)) }; }
function guard(draft, item) { if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`); if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`); }
const source = await readFile(bankPath, "utf8"); const parsed = parse(source); const byId = new Map(parsed.drafts.map((d) => [d.id, d])); const applied = [], restricted = [];
for (const item of restorations) { const d = byId.get(item.id); guard(d, item); const before = { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings ?? [] }; Object.assign(d, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); applied.push({ id: item.id, sourcePage: item.page, before, after: { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
for (const item of restrictions) { const d = byId.get(item.id); guard(d, item); const before = { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings ?? [], highYieldNote: d.highYieldNote, mnemonic: d.mnemonic, memoryAid: d.memoryAid }; Object.assign(d, { stem: item.stem, options: item.options, correctOption: null, explanation: item.explanation, learningNote: "", status: "needs_review", askable: false, needsImage: false, highYieldNote: undefined, mnemonic: undefined, memoryAid: undefined, warnings: [item.warning] }); restricted.push({ id: item.id, sourcePage: item.page, before, after: { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${source.slice(0, parsed.a)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.e + 1)}`); await mkdir(auditDir, { recursive: true }); await writeFile(path.join(auditDir, "applied-anatomy-batch-21.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`); console.log(JSON.stringify({ restored: applied.map((v) => v.id), restricted: restricted.map((v) => v.id), automaticApproval: false }, null, 2));
