/** Guarded Anatomy Batch 03 restoration; no record is approved by this script. */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";

const restorations = [
  { id: "anatomy-anatomy-all-pdf-p0093-q0022", page: 93, expectedStem: "wy Which of the following is the functional unit of the liver:", expectedOptions: ["Hepatocyte 22%", "Lobule", "Portal triad 55%", "Lobe 0%"], stem: "Which of the following is the functional unit of the liver?", options: ["Hepatocyte", "Lobule", "Portal triad", "Lobe", "Acinus"], correctOption: 1, explanation: "Hepatocytes are arranged into lobules, the functional units of the liver. A central vein lies at the centre of each classic lobule.", learningNote: "A liver lobule is a microscopic structural unit: central vein in the centre, portal tracts at the periphery.", highYieldNote: "The classic hepatic lobule is a functional unit of the liver, organised around a central vein.", mnemonic: "🧱 Liver lobule: a tiny liver building block around a central vein.", memoryAid: { coreFact: "The hepatic lobule is a functional unit of the liver.", mnemonic: "Liver lobule: a tiny building block around a central vein.", emojiCues: ["🧱", "🎯"], cueLabel: "A building block and centre target cue a lobule around its central vein.", sourceLabel: "NCBI Bookshelf: Liver", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK500014/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK500014/", finding: "Hepatocytes are arranged into lobules, the functional units of the liver." },
  { id: "anatomy-anatomy-all-pdf-p0099-q0023", page: 99, expectedStem: "A70 year old undergoes radical prostatectomy for prostate cancer. Postoperatively he complains of urinary incontinence due to paralysis of the external urethral sphincter. Which of the following nerves was most likely injured during surgery:", expectedOptions: ["Genitofemoral nerve", "Coccygeal nerve Cie", "lliohypogastric nerve"], stem: "A 70-year-old man undergoes radical prostatectomy for prostate cancer. Postoperatively, he has urinary incontinence due to paralysis of the external urethral sphincter. Which nerve was most likely injured?", options: ["Genitofemoral nerve", "Pudendal nerve", "Coccygeal nerve", "Ilioinguinal nerve", "Iliohypogastric nerve"], correctOption: 1, explanation: "The pudendal nerve arises from S2-S4. Its deep perineal branch innervates the external urethral sphincter and supports voluntary micturition.", learningNote: "External urethral sphincter = somatic pudendal supply, chiefly through the deep perineal branch.", highYieldNote: "Pudendal nerve S2-S4 supplies the external urethral sphincter through its deep perineal branch.", mnemonic: "🚻 Pudendal S2-S4 keeps the external sphincter shut.", memoryAid: { coreFact: "The pudendal deep perineal branch innervates the external urethral sphincter.", mnemonic: "Pudendal S2-S4 keeps the external sphincter shut.", emojiCues: ["🚻", "2️⃣3️⃣4️⃣"], cueLabel: "A toilet and S2-S4 sequence cue pudendal sphincter control.", sourceLabel: "NCBI Bookshelf: Pudendal Nerve", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554736/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554736/", finding: "The deep perineal branch innervates the external urethral sphincter." },
  { id: "anatomy-anatomy-all-pdf-p0104-q0024", page: 104, expectedStem: "w The abdominal aorta bifurcates into its terminal branches at which of the following vertebral levels:", expectedOptions: ["112 1%", "(Les 8%"], stem: "The abdominal aorta bifurcates into its terminal branches at which vertebral level?", options: ["T12", "L1", "L2", "L3", "L4"], correctOption: 4, explanation: "The abdominal aorta bifurcates at L4 into the right and left common iliac arteries.", learningNote: "Aortic bifurcation is a useful L4 landmark; it lies near the lower umbilical level on the anterior abdominal wall.", highYieldNote: "Abdominal aorta: bifurcation into common iliac arteries at L4.", mnemonic: "4️⃣ Aorta splits at L4: four points to two iliacs.", memoryAid: { coreFact: "The abdominal aorta bifurcates at L4.", mnemonic: "Aorta splits at L4.", emojiCues: ["4️⃣", "🔀"], cueLabel: "Four and a split arrow cue L4 aortic bifurcation.", sourceLabel: "NCBI Bookshelf: Posterior Abdominal Wall Arteries", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532972/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532972/", finding: "The abdominal aorta bifurcates at L4." },
  { id: "anatomy-anatomy-all-pdf-p0108-q0025", page: 108, expectedStem: "A 49 year old female patient undergoes surgery for uterine cancer. Whilst attempting to ligate the uterine artery, the surgeon accidentally ligates the structure that the uterine artery crosses anteriorly as it passes from the internal iliac artery to the uterus. Which of the following structures has most likely been injured:", expectedOptions: ["Ovarian artery", "Ovarian ligament", "Fallopian tube", "Round ligament of uterus"], stem: "A 49-year-old woman undergoes surgery for uterine cancer. During uterine-artery ligation, the surgeon injures the structure that the artery crosses anteriorly. Which structure was injured?", options: ["Ovarian artery", "Ovarian ligament", "Ureter", "Uterine tube", "Round ligament of uterus"], correctOption: 2, explanation: "The uterine artery crosses the ureter near the cervix, approximately 1 cm lateral to the internal os. This relation is remembered as water under the bridge.", learningNote: "Identify the structure at risk during uterine-artery ligation: the ureter passes beneath the uterine artery.", highYieldNote: "Ureter runs beneath the uterine artery near the cervix: water under the bridge.", mnemonic: "💧 Water (ureter) runs under the bridge (uterine artery).", memoryAid: { coreFact: "The uterine artery crosses anterior to the ureter near the cervix.", mnemonic: "Water runs under the bridge.", emojiCues: ["💧", "🌉"], cueLabel: "Water and a bridge cue the ureter beneath the uterine artery.", sourceLabel: "NCBI Bookshelf: Physiology, Uterus", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557575/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557575/", finding: "The uterine artery crosses the ureter 1 cm lateral to the internal os." },
  { id: "anatomy-anatomy-all-pdf-p0112-q0026", page: 112, expectedStem: "Sensation to the skin over the penis is primarily supplied by which of the following nerves:", expectedOptions: ["Coccygeal nerve", "llioinguinal nerve", "lliohypogastric nerve"], stem: "Sensation from the skin of the penile shaft and glans is primarily supplied by which nerve?", options: ["Genitofemoral nerve", "Pudendal nerve", "Coccygeal nerve", "Ilioinguinal nerve", "Iliohypogastric nerve"], correctOption: 1, explanation: "The dorsal nerve of the penis is the terminal, solely cutaneous branch of the pudendal nerve. It relays somatic sensation from the shaft, prepuce, and glans.", learningNote: "Distinguish the dorsal penile nerve from ilioinguinal supply to the penile root and anterior scrotal skin.", highYieldNote: "Dorsal nerve of penis is a cutaneous terminal branch of the pudendal nerve, supplying shaft and glans sensation.", mnemonic: "👆 Dorsal penis sensation follows the pudendal path.", memoryAid: { coreFact: "The dorsal nerve of the penis is a cutaneous branch of the pudendal nerve.", mnemonic: "Dorsal penis sensation follows the pudendal path.", emojiCues: ["👆", "🧠"], cueLabel: "A pointing hand and sensory cue indicate dorsal penile sensation.", sourceLabel: "NCBI Bookshelf: Pudendal Nerve", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554736/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK554736/", finding: "The dorsal nerve is a solely cutaneous pudendal branch supplying shaft and glans." },
  { id: "anatomy-anatomy-all-pdf-p0119-q0029", page: 119, expectedStem: "ww The rectus sheath is formed by which of the following:", expectedOptions: ["the thoracolumbar fascia 1%", "the aponeuroses of the external and internal oblique 8%", "the aponeuroses of the external oblique, internal oblique and transversus abdominis", "the transversalis fascia 5%", "the tendinous intersections of the rectus abdominis 5%"], stem: "The rectus sheath is formed by which structures?", options: ["Thoracolumbar fascia", "Aponeuroses of external and internal oblique only", "Aponeuroses of external oblique, internal oblique, and transversus abdominis", "Transversalis fascia", "Tendinous intersections of rectus abdominis"], correctOption: 2, explanation: "The fascial coverings of external oblique, internal oblique, and transversus abdominis comprise the rectus sheath. The anterior and posterior layers differ above and below the arcuate line.", learningNote: "Below the arcuate line, all three lateral abdominal-wall aponeuroses pass anterior to rectus abdominis; posteriorly, transversalis fascia remains.", highYieldNote: "Rectus sheath comes from EO, IO, and transversus abdominis aponeuroses; the layer arrangement changes at the arcuate line.", mnemonic: "🧥 Rectus wears a 3-layer coat: EO, IO, TA.", memoryAid: { coreFact: "External oblique, internal oblique, and transversus abdominis fascial coverings comprise the rectus sheath.", mnemonic: "Rectus wears a 3-layer coat: EO, IO, TA.", emojiCues: ["🧥", "3️⃣"], cueLabel: "A coat and three cue the three aponeurotic layers.", sourceLabel: "NCBI Bookshelf: Rectus Sheath", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK537153/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK537153/", finding: "The three lateral abdominal-wall fascial coverings comprise the rectus sheath." },
  { id: "anatomy-anatomy-all-pdf-p0122-q0030", page: 122, expectedStem: "A75 year old man presents to ED in acute urinary retention. On examination you note the prostate feels hard and craggy. You suspect prostate cancer. Which structure is most likely affected: (x) Anterior lobe of prostate 2%", expectedOptions: ["Fibromuscular zone of prostate", "Lateral lobe of prostate", "Transitional zone of prostate"], stem: "A 75-year-old man presents with acute urinary retention. On examination, his prostate feels hard and irregular; prostate cancer is suspected. Which structure is most likely affected?", options: ["Anterior lobe of prostate", "Fibromuscular zone of prostate", "Lateral lobe of prostate", "Posterior lobe of prostate", "Transitional zone of prostate"], correctOption: 3, explanation: "This question uses traditional lobar terminology, in which the posterior lobe is palpated on rectal examination. In contemporary zonal terminology, most prostate carcinomas arise in the peripheral zone, while BPH tends to involve the transitional zone.", learningNote: "Avoid mixing prostate classification systems: posterior lobe is historical lobar terminology; peripheral zone is the contemporary zone commonly involved by carcinoma.", highYieldNote: "Most prostate carcinomas arise in the peripheral zone; this source question labels the palpable posterior region as the posterior lobe.", mnemonic: "🎯 Prostate cancer: think peripheral zone, posteriorly palpable.", memoryAid: { coreFact: "Most prostate carcinomas arise in the peripheral zone; historical questions may call the palpable posterior region the posterior lobe.", mnemonic: "Cancer is peripheral and posteriorly palpable.", emojiCues: ["🎯", "🔙"], cueLabel: "A target and back arrow cue peripheral posterior disease.", sourceLabel: "NCBI Bookshelf: Prostate", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK540987/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK540987/", finding: "Most carcinomas develop in the peripheral zone; BPH tends to appear in the transitional zone." },
  { id: "anatomy-anatomy-all-pdf-p0134-q0033", page: 134, expectedStem: "ww The gallbladder occupies which of the following regions of the abdomen:", expectedOptions: ["Left hypochondrium 1%", "Right hypochondrium", "Right hypochondrium and right flank 4%", "Right hypochondrium and epigastric region 17%", "Epigastric region and umbilicus 1%"], stem: "The gallbladder occupies which abdominal region?", options: ["Left hypochondrium", "Right hypochondrium", "Right hypochondrium and right flank", "Right hypochondrium and epigastric region", "Epigastric and umbilical regions"], correctOption: 1, explanation: "The gallbladder lies in the right hypochondrium with the liver.", learningNote: "In the nine-region abdominal scheme, the gallbladder is in the right hypochondrium.", highYieldNote: "Gallbladder location: right hypochondrium, on the liver’s undersurface.", mnemonic: "➡️ Gallbladder stays right, under the liver.", memoryAid: { coreFact: "The gallbladder lies in the right hypochondrium.", mnemonic: "Gallbladder stays right, under the liver.", emojiCues: ["➡️", "🟢"], cueLabel: "A right arrow and green marker cue the gallbladder’s right hypochondrial position.", sourceLabel: "NCBI Bookshelf: Abdomen", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553104/" }, sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553104/", finding: "The gallbladder is located in the right hypochondrium." },
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0126-q0031", page: 126, warning: "Source page reviewed, but mechanism-specific handlebar trauma evidence does not support a universal spleen answer. Remains unresolved and excluded from answer learning." },
  { id: "anatomy-anatomy-all-pdf-p0130-q0032", page: 130, warning: "Source page reviewed, but authoritative anatomy places the deep inguinal ring above the midpoint of the inguinal ligament rather than the source-marked mid-inguinal point. Remains unresolved and excluded from answer learning." },
];

const source = await readFile(bankPath, "utf8");
const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
const start = source.indexOf(prefix); const arrayStart = start + prefix.length; const end = source.indexOf("];", arrayStart);
if (start < 0 || end < 0) throw new Error("OCR draft export not found");
const drafts = JSON.parse(source.slice(arrayStart, end + 1)); const byId = new Map(drafts.map((item) => [item.id, item]));
const applied = [], restricted = [];
for (const item of restorations) {
  const draft = byId.get(item.id);
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing restoration.`);
  if (!["ocr_draft", "needs_review"].includes(draft.status)) throw new Error(`Unexpected status for ${item.id}`);
  const before = { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable };
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}
for (const item of restrictions) {
  const draft = byId.get(item.id);
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  const before = { status: draft.status, askable: draft.askable, warnings: draft.warnings ?? [] };
  Object.assign(draft, { status: "needs_review", askable: false, warnings: [...new Set([...(draft.warnings ?? []), item.warning])] });
  restricted.push({ id: item.id, sourcePage: item.page, before, after: { status: draft.status, askable: draft.askable, warnings: draft.warnings } });
}
await writeFile(bankPath, `${source.slice(0, arrayStart)}${JSON.stringify(drafts)}${source.slice(end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-03.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
