import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0952-q0066", 952, "ww A 21 year old man presents to ED complaining of a scrotal lump. Imaging demonstrates a testicular tumour. The lymphatic drainage of the testis is to which of the following:", ["Internal iliac nodes 53%", "External iliac nodes 1%", "Superficial inguinal nodes 5%", "Deep inguinal nodes", "Para-aortic nodes"], "A 21 year old man presents to ED complaining of a scrotal lump. Imaging demonstrates a testicular tumour. The lymphatic drainage of the testis is to which of the following:", ["Internal iliac nodes", "External iliac nodes", "Superficial inguinal nodes", "Deep inguinal nodes", "Para-aortic nodes"], 4, "Testicular lymphatics follow the testicular vessels to the para-aortic, also called lumbar-aortic, lymph nodes; this differs from scrotal lymphatic drainage to superficial inguinal nodes.", "Testes drain to para-aortic nodes, whereas scrotum drains to superficial inguinal nodes.", "Testis: para-aortic drainage; scrotum: superficial inguinal drainage.", "⬆️ TESTES travel back to PARA-AORTIC nodes.", aid("Testicular lymphatics drain to para-aortic lymph nodes because the testes develop on the posterior abdominal wall.", "Testes travel back to the aorta.", ["⬆️", "🫀"], "Upward and aortic cues retain the posterior-abdominal drainage route.", "NCBI Bookshelf: Testicular Lymphatic Drainage", "https://www.ncbi.nlm.nih.gov/books/NBK557720/"), "https://www.ncbi.nlm.nih.gov/books/NBK557720/", "NCBI identifies para-aortic nodes as the principal lymphatic drainage of the testes."),
  r("anatomy-anatomy-all-pdf-p0960-q0068", 960, "w The retroduodenal region of the common bile duct:", ["lies left of the gastroduodenal artery. 3% (x) lies posterior to the portal vein. 4%", "lies posterior to the first part of the duodenum", "empties directly into the major duodenal papilla. 4%", "lies posterior to the second part of the duodenum. 62%"], "The retroduodenal region of the common bile duct:", ["lies left of the gastroduodenal artery.", "lies posterior to the portal vein.", "lies posterior to the first part of the duodenum.", "empties directly into the major duodenal papilla.", "lies posterior to the second part of the duodenum."], 2, "The retroduodenal segment of the common bile duct passes posterior to the first part of the duodenum before continuing in its pancreatic relation.", "Retroduodenal CBD passes behind the first part of the duodenum.", "CBD retroduodenal segment: posterior to D1.", "↩️ CBD goes BEHIND D1.", aid("The retroduodenal common bile duct passes posterior to the first part of the duodenum.", "Retro-duodenal means behind D1.", ["↩️", "1️⃣"], "Behind and one cues retain the retroduodenal relation.", "PMC: Biliary Anatomy", "https://pmc.ncbi.nlm.nih.gov/articles/PMC8354732/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC8354732/", "Peer-reviewed biliary anatomy states that the common bile duct courses posterior to the first portion of the duodenum."),
  r("anatomy-anatomy-all-pdf-p0963-q0069", 963, "ww Which of the following structures is NOT retroperitoneal:", ["Rectum 6%", "Ureters 4%", "Tail of pancreas", "Kidneys 1%"], "Which of the following structures is NOT retroperitoneal:", ["Rectum", "Inferior vena cava", "Ureters", "Tail of pancreas", "Kidneys"], 3, "The pancreatic tail reaches the splenic hilum in the splenorenal ligament and is the intraperitoneal exception among these options.", "Pancreatic tail lies in the splenorenal ligament and is not retroperitoneal.", "Pancreatic tail is the intraperitoneal exception.", "🟣 PANCREATIC TAIL reaches the SPLEEN.", aid("The pancreatic tail reaches the splenic hilum within the splenorenal ligament, unlike the retroperitoneal pancreatic body and head.", "Tail travels to spleen.", ["🟣", "➡️"], "Pancreatic and direction cues retain the splenic-hilum relation.", "PMC: Surgical Anatomy of Pancreatic Tail", "https://pmc.ncbi.nlm.nih.gov/articles/PMC9986191/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC9986191/", "Peer-reviewed surgical anatomy places the pancreatic tail at the splenic hilum in the splenorenal ligament."),
  r("anatomy-anatomy-all-pdf-p0971-q0071", 971, "ww In men, the internal urethral sphincter surrounds which of the following structures:", ["Preprostatic urethra", "Membranous urethra 60%", "Spongy urethra 3%", "Distal ureter 1%"], "In men, the internal urethral sphincter surrounds which of the following structures:", ["Preprostatic urethra", "Prostatic urethra", "Membranous urethra", "Spongy urethra", "Distal ureter"], 0, "The small preprostatic urethral segment at the bladder outlet is surrounded by the vesical, or internal urethral, sphincter.", "Internal urethral sphincter surrounds the preprostatic urethra.", "Preprostatic urethra sits at the bladder neck within the internal sphincter.", "🚪 PREPROSTATIC is at the BLADDER door.", aid("The preprostatic urethra is the short segment at the bladder outlet and is surrounded by the vesical/internal urethral sphincter.", "Preprostatic means before the prostate, at the bladder door.", ["🚪", "⬇️"], "Door and downward-flow cues retain the bladder-outlet location.", "PMC: Male Urethral Topographical Anatomy", "https://pmc.ncbi.nlm.nih.gov/articles/PMC11365459/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC11365459/", "Cadaveric anatomy identifies the preprostatic urethral segment as surrounded by the bladder/internal urethral sphincter."),
  r("anatomy-anatomy-all-pdf-p0979-q0073", 979, "A 21 year old female presents to ED complaining of acute severe pelvic pain. She reports she has not had a period for 6 weeks which is not normal for her. A urine pregnancy test is positive. Which of the following is the most common site of an ectopic pregnancy:", ["Cervix (x) The mesentery 1%", "Vagina", "Ovaries"], "A 21 year old female presents to ED complaining of acute severe pelvic pain. She reports she has not had a period for 6 weeks which is not normal for her. A urine pregnancy test is positive. Which of the following is the most common site of an ectopic pregnancy:", ["Cervix", "Uterine tubes", "The mesentery", "Vagina", "Ovaries"], 1, "Most ectopic pregnancies implant in a uterine tube; within the tube, the ampulla is the most frequent site.", "Most ectopic pregnancies are tubal, usually ampullary.", "Ectopic pregnancy: uterine tube, usually ampulla.", "🧪 ECTOPIC usually stops in the TUBE.", aid("Most ectopic pregnancies are tubal; the ampulla is the usual site within the uterine tube.", "Ectopic embryo enters the tube, usually the ampulla.", ["🧪", "➡️"], "Test and direction cues retain the tubal implantation site.", "NCBI Bookshelf: Ectopic Pregnancy", "https://www.ncbi.nlm.nih.gov/books/NBK539860/"), "https://www.ncbi.nlm.nih.gov/books/NBK539860/", "NCBI states that most ectopic pregnancies are tubal and the ampulla is the most frequent tubal location."),
  r("anatomy-anatomy-all-pdf-p0982-q0074", 982, "Irritation of the central part of the diaphragmatic peritoneum is typically referred to:", ["The jaw a", "The epigastric region The periumbilical region 4% (x) The flanks 1%"], "Irritation of the central part of the diaphragmatic peritoneum is typically referred to:", ["The jaw", "The shoulder tip", "The epigastric region", "The periumbilical region", "The flanks"], 1, "The phrenic nerve supplies central diaphragmatic sensation through C3–C5 roots, so diaphragmatic pain is referred to the shoulder tip.", "Central diaphragm irritation refers to the shoulder tip via phrenic C3–C5.", "Central diaphragm: phrenic C3–C5 referral to the shoulder tip.", "3️⃣4️⃣5️⃣ PHRENIC points to the SHOULDER.", aid("Central diaphragmatic peritoneal sensation travels through the phrenic nerve from C3 to C5 and refers pain to the shoulder tip.", "C3, 4, 5: shoulder referral stays alive.", ["3️⃣", "4️⃣", "5️⃣"], "Root-number cues retain the phrenic referral pattern.", "NCBI Bookshelf: Phrenic Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK513325/"), "https://www.ncbi.nlm.nih.gov/books/NBK513325/", "NCBI describes C3–C5 phrenic sensory supply to the central diaphragm and shoulder-tip referral of diaphragmatic pain."),
  r("anatomy-anatomy-all-pdf-p0985-q0075", 985, "The bladder receives its efferent parasympathetic fibres derived from spinal cord segments:", ["L4-L5", "$1-S2", "L4-S2"], "The bladder receives its efferent parasympathetic fibres derived from spinal cord segments:", ["L4 - L5", "S3 - S4", "S2 - S4", "S1 - S2", "L4 - S2"], 2, "Pelvic splanchnic parasympathetic fibres arise from S2–S4 and promote micturition by contracting detrusor muscle and relaxing the internal urethral sphincter.", "Bladder parasympathetic supply is pelvic splanchnic S2–S4.", "S2–S4 pelvic splanchnics contract detrusor for voiding.", "2️⃣3️⃣4️⃣ S2–S4 makes the DETRUSOR POUR.", aid("Pelvic splanchnic parasympathetic fibres from S2 to S4 contract the detrusor and facilitate voiding.", "S2 to S4 sends urine to the floor.", ["2️⃣", "3️⃣", "4️⃣"], "Sacral-number cues retain the pelvic-splanchnic outflow.", "NCBI Bookshelf: Bladder", "https://www.ncbi.nlm.nih.gov/books/NBK531465/"), "https://www.ncbi.nlm.nih.gov/books/NBK531465/", "NCBI states that pelvic splanchnic parasympathetic fibres arise from S2–S4 and contract the detrusor for voiding."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0955-q0067", page: 955, expectedStem: "ww The ilioinguinal nerve is formed from the anterior rami of:", expectedOptions: ["u", "{4 =L2 61%", "L2 1% SE", "L4 1%"], stem: "The ilioinguinal nerve is formed from the anterior rami of:", options: ["L1", "L1 - L2", "L2", "L2 - L3", "L4"], warning: "Source page reviewed, but authoritative sources describe a documented T12–L1 contribution as well as the standard L1 origin; the source's single-level formulation is not uniquely corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK538256/", finding: "NCBI describes ilioinguinal root contribution from T12 and L1, whereas the source question offers only a single-level standard formulation." },
  { id: "anatomy-anatomy-all-pdf-p0966-q0070", page: 966, expectedStem: "Which of the following structures is NOT a posterior relation of the transverse colon:", expectedOptions: ["Second part of duodenum", "Upper end of mesentery", "Duodenojejunal flexure"], stem: "Which of the following structures is NOT a posterior relation of the transverse colon:", options: ["Second part of duodenum", "Head of pancreas", "Upper end of mesentery", "Duodenojejunal flexure", "Spleen"], warning: "Source page reviewed, but no authoritative source reviewed provides a complete posterior-relation list sufficient to test all source options exactly; no correct option is inferred.", sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2821589/", finding: "Peer-reviewed peritoneal anatomy confirms relevant transverse-mesocolon connections but does not corroborate the complete source option set as an exact posterior-relation list." },
  { id: "anatomy-anatomy-all-pdf-p0975-q0072", page: 975, expectedStem: "A 26 year old woman is brought to ED following a road traffic accident. Focussed assessment for sonography in trauma (FAST) on the supine patient demonstrates free intraperitoneal fluid. Which of the following spaces is most likely to be affected:", expectedOptions: ["Vesicouterine recess", "Left paracolic gutter", "Subphrenic recess"], stem: "A 26 year old woman is brought to ED following a road traffic accident. Focussed assessment for sonography in trauma (FAST) on the supine patient demonstrates free intraperitoneal fluid. Which of the following spaces is most likely to be affected:", options: ["Hepatorenal recess", "Vesicouterine recess", "Rectouterine recess", "Left paracolic gutter", "Subphrenic recess"], warning: "Source page reviewed, but authoritative FAST references support more than one dependent recess in a supine woman when no view or fluid volume is specified; no correct option is inferred.", sourceUrl: "https://www.acep.org/sonoguide/basic/fast", finding: "ACEP identifies the pouch of Douglas as a dependent peritoneal site in a supine woman, while NCBI identifies the hepatorenal recess in the RUQ FAST view; the broad stem is non-unique." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  delete draft.approved;
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  delete draft.approved;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-31.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
