import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const snapshotPath = path.join(root, "docs", "audit", "anatomy-all-pdf-batch-41-ocr-records.json");
const artifactPath = path.join(root, "docs", "audit", "applied-anatomy-batch-41.json");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel: "Source-confirmed anatomy fact", sourceLabel, sourceUrl });

const restorations = [
  { id: "anatomy-anatomy-all-pdf-p1262-q0169", page: 1262, expectedStem: "Which of the following best describes the location of the omental bursa:", expectedOptions: ["Inferior to the transverse mesocolon", "To the right of the oblique attachment of the mesentery", "Posterior to the pancreas", "Anterior to the stomach and liver"], stem: "Which of the following best describes the location of the omental bursa:", options: ["Inferior to the transverse mesocolon", "To the right of the oblique attachment of the mesentery", "Posterior to the stomach and liver", "Posterior to the pancreas", "Anterior to the stomach and liver"], correctOption: 2, fact: "The omental bursa, or lesser sac, lies posterior to the stomach and liver and anterior to the pancreas.", mnemonic: "Lesser sac: stomach in front, pancreas behind.", memoryAid: aid("The omental bursa is posterior to the stomach and liver and anterior to the pancreas.", "Lesser sac: stomach in front, pancreas behind.", ["🔙", "🍽️", "🫀"], "NCBI Bookshelf: Stomach Anatomy", "https://www.ncbi.nlm.nih.gov/books/NBK482334/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482334/", finding: "NCBI describes the lesser sac behind the stomach and in front of the pancreas; the source-page key is posterior to the stomach and liver." },
  { id: "anatomy-anatomy-all-pdf-p1263-q0170", page: 1263, expectedStem: "The abdominal aorta terminates as which of the following:", expectedOptions: ["Internal and external iliac arteries 13%", "External iliac and femoral artery 2%", "Right and left common iliac arteries", "Superior and inferior epigastric arteries", "Internal iliac and femoral artery 2%"], stem: "The abdominal aorta terminates as which of the following:", options: ["Internal and external iliac arteries", "External iliac and femoral artery", "Right and left common iliac arteries", "Superior and inferior epigastric arteries", "Internal iliac and femoral artery"], correctOption: 2, fact: "The abdominal aorta terminates by bifurcating into the right and left common iliac arteries.", mnemonic: "Aorta divides into two common iliacs.", memoryAid: aid("The abdominal aorta ends at its bifurcation into the two common iliac arteries.", "Aorta divides into two common iliacs.", ["🩸", "↔️"], "NCBI Bookshelf: Abdominal Aorta", "https://www.ncbi.nlm.nih.gov/books/NBK537319/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK537319/", finding: "NCBI states that the abdominal aorta terminates as the right and left common iliac arteries." },
  { id: "anatomy-anatomy-all-pdf-p1264-q0171", page: 1264, expectedStem: "The genitofemoral nerve supplies skin over which of the following regions:", expectedOptions: ["Posterolateral gluteal region 4%", "Lateral thigh 1%", "Upper medial thigh 25%", "Upper anterior thigh", "Posteromedial gluteal region 71%"], stem: "The genitofemoral nerve supplies skin over which of the following regions:", options: ["Posterolateral gluteal region", "Lateral thigh", "Upper medial thigh", "Upper anterior thigh", "Posteromedial gluteal region"], correctOption: 3, fact: "The femoral branch of the genitofemoral nerve supplies sensation to skin over the upper anterior thigh.", mnemonic: "Genitofemoral: femoral branch fronts the upper thigh.", memoryAid: aid("The femoral branch of the genitofemoral nerve supplies the upper anterior thigh.", "Genitofemoral: femoral branch fronts the upper thigh.", ["🦵", "⬆️", "↗️"], "NCBI Bookshelf: Genitofemoral Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK430733/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK430733/", finding: "NCBI identifies the upper anterior thigh as the cutaneous territory of the femoral branch." },
  { id: "anatomy-anatomy-all-pdf-p1265-q0172", page: 1265, expectedStem: "ww The lymph drainage of the anal canal above the pectinate line is initially to the:", expectedOptions: ["Internal iliac nodes", "External iliac nodes 5%", "Superficial inguinal nodes 9%", "Deep inguinal nodes 10%"], stem: "The lymph drainage of the anal canal above the pectinate line is initially to the:", options: ["Internal iliac nodes", "External iliac nodes", "Superficial inguinal nodes", "Deep inguinal nodes"], correctOption: 0, fact: "Lymph from the anal canal above the pectinate line initially drains to the internal iliac nodes.", mnemonic: "Above the line, go internal; below it, go superficial groin.", memoryAid: aid("Above the pectinate line, anal-canal lymph drains initially to internal iliac nodes.", "Above the line, go internal; below it, go superficial groin.", ["⬆️", "🟣", "🦵"], "NCBI Bookshelf: Anal Canal", "https://www.ncbi.nlm.nih.gov/books/NBK551682/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK551682/", finding: "NCBI supports internal-iliac drainage for the anal canal above the pectinate line." },
  { id: "anatomy-anatomy-all-pdf-p1266-q0173", page: 1266, expectedStem: "wy The iliohypogastric nerve innervates which of the following muscles:", expectedOptions: ["External and internal oblique muscles 10%", "Internal oblique and transversus abdominis muscles", "Transversus abdominis and rectus abdominus muscles 1%", "Psoas major and iliacus", "Quadratus lumborum 7h"], stem: "The iliohypogastric nerve innervates which of the following muscles:", options: ["External and internal oblique muscles", "Internal oblique and transversus abdominis muscles", "Transversus abdominis and rectus abdominis muscles", "Psoas major and iliacus", "Quadratus lumborum"], correctOption: 1, fact: "The iliohypogastric nerve supplies motor innervation to the internal oblique and transversus abdominis muscles.", mnemonic: "Iliohypogastric works the inner oblique and transverse layers.", memoryAid: aid("The iliohypogastric nerve innervates internal oblique and transversus abdominis.", "Iliohypogastric works the inner oblique and transverse layers.", ["💪", "↔️", "🧱"], "NCBI Bookshelf: Anterolateral Abdominal Wall", "https://www.ncbi.nlm.nih.gov/books/NBK459392/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK459392/", finding: "NCBI states that the iliohypogastric nerve supplies internal oblique and transversus abdominis." },
  { id: "anatomy-anatomy-all-pdf-p1267-q0174", page: 1267, expectedStem: "ww Regarding the rectus abdominis muscle, which of the following statements is INCORRECT:", expectedOptions: ["It originates from the pubic crest, pubic tubercle and pubic symphysis. 8%", "It inserts onto the costal cartilages of ribs 5 - 7 and to the xiphoid process. 12% (x) It is separated in the midline by the linea alba. 6%", "The free lower border of its aponeurosis forms the inguinal ligament.", "It is intersected along it length by tendinous intersections. 7%"], stem: "Regarding the rectus abdominis muscle, which of the following statements is INCORRECT:", options: ["It originates from the pubic crest, pubic tubercle and pubic symphysis.", "It inserts onto the costal cartilages of ribs 5 - 7 and to the xiphoid process.", "It is separated in the midline by the linea alba.", "The free lower border of its aponeurosis forms the inguinal ligament.", "It is intersected along its length by tendinous intersections."], correctOption: 3, fact: "The incorrect statement is that the free lower border of the rectus abdominis aponeurosis forms the inguinal ligament; the inguinal ligament is formed by the free lower border of the external-oblique aponeurosis.", mnemonic: "Inguinal ligament: external oblique, not rectus.", memoryAid: aid("The inguinal ligament is the free lower border of the external-oblique aponeurosis, not the rectus sheath.", "Inguinal ligament: external oblique, not rectus.", ["🧱", "⬇️", "❌"], "NCBI Bookshelf: Abdominal Wall", "https://www.ncbi.nlm.nih.gov/books/NBK551649/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK551649/", finding: "NCBI identifies the inguinal ligament as the inferior free border of the external-oblique aponeurosis." },
  { id: "anatomy-anatomy-all-pdf-p1269-q0176", page: 1269, expectedStem: "ww Regarding the female urethra, which of the following statements is CORRECT:", expectedOptions: ["The urethra is longer in women than it is in men. 1%", "The urethra begins at the apex of the bladder. 10%", "The urethra opens in the vestibule that lies between the labia minora.", "The inferior aspect of the urethra is bound to the posterior surface of the vagina. 4%", "The internal urethral sphincter surrounds the urethra as it passes through the pelvic floor. 13%"], stem: "Regarding the female urethra, which of the following statements is CORRECT:", options: ["The urethra is longer in women than it is in men.", "The urethra begins at the apex of the bladder.", "The urethra opens in the vestibule that lies between the labia minora.", "The inferior aspect of the urethra is bound to the posterior surface of the vagina.", "The internal urethral sphincter surrounds the urethra as it passes through the pelvic floor."], correctOption: 2, fact: "The female urethra opens into the vestibule between the labia minora.", mnemonic: "Female urethra: short, anterior, vestibular opening.", memoryAid: aid("The female urethral opening is in the vestibule between the labia minora.", "Female urethra: short, anterior, vestibular opening.", ["♀️", "🚪", "↔️"], "NCBI Bookshelf: Female External Genitalia", "https://www.ncbi.nlm.nih.gov/books/NBK547703/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK547703/", finding: "NCBI identifies the urethral opening within the vestibule between the labia minora." },
  { id: "anatomy-anatomy-all-pdf-p1279-q0179", page: 1279, expectedStem: "ww Which of the following areas of the prostate gland is most commonly involved in carcinomatous transformation:", expectedOptions: ["Central zone 6%", "Peripheral zone", "Anterior fibromuscular stroma 1%", "Isthmus 52%"], stem: "Which of the following areas of the prostate gland is most commonly involved in carcinomatous transformation:", options: ["Transitional zone", "Central zone", "Peripheral zone", "Anterior fibromuscular stroma", "Isthmus"], correctOption: 2, fact: "The peripheral zone is the prostate region most commonly involved by carcinoma.", mnemonic: "Peripheral prostate, palpable and commonly cancerous.", memoryAid: aid("Most prostate cancers arise in the peripheral zone, which is accessible on digital rectal examination.", "Peripheral prostate, palpable and commonly cancerous.", ["🎯", "🧭", "🩺"], "NCBI Bookshelf: Prostate Cancer", "https://www.ncbi.nlm.nih.gov/books/NBK470550/"), sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470550/", finding: "NCBI states that prostate cancer is most commonly found in the peripheral zone." }
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p1268-q0175", page: 1268, expectedStem: "ww A50 year old man complains of lumps in his groin and is found to have painless superficial inguinal lymphadenopathy. Lymph node biopsy demonstrates malignant cells, which of the following sites is most likely the primary source of carcinoma:", expectedOptions: ["Prostate 13%", "Bladder ae", "Anal canal", "Sigmoid colon 3%"], stem: "A 50 year old man complains of lumps in his groin and is found to have painless superficial inguinal lymphadenopathy. Lymph node biopsy demonstrates malignant cells, which of the following sites is most likely the primary source of carcinoma:", options: ["Prostate", "Bladder", "Anal canal", "Sigmoid colon"], warning: "Source page reviewed, but superficial inguinal drainage depends on the lesion being below the pectinate line; the stem's unqualified anal-canal wording is not uniquely supported, so no answer is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK557639/", finding: "NCBI states that superficial inguinal nodes drain the anal canal below the pectinate line, while the source stem omits that level qualifier." },
  { id: "anatomy-anatomy-all-pdf-p1276-q0178", page: 1276, expectedStem: "ww A 29 year old patient, with a known ovarian cyst presents to ED complaining of worsening pelvic pain and pain in the medial thigh region. Irritation of which of the following structures is responsible for the pain in the medial thigh region:", expectedOptions: ["Genitofemoral nerve 28%", "Obturator nerve", "Pudendal nerve 4%", "Sacral plexus 3%", "Ovarian plexus 3%"], stem: "A 29 year old patient, with a known ovarian cyst presents to ED complaining of worsening pelvic pain and pain in the medial thigh region. Irritation of which of the following structures is responsible for the pain in the medial thigh region:", options: ["Genitofemoral nerve", "Obturator nerve", "Pudendal nerve", "Sacral plexus", "Ovarian plexus"], warning: "Source page reviewed, but available evidence confirms obturator sensory territory and pelvic pathology as possible causes without uniquely establishing the source's specific ovarian-cyst causal formulation; no answer is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK551640/", finding: "NCBI confirms obturator medial-thigh sensation; a peer-reviewed case report documents pelvic pathology causing obturator-distribution pain, but does not directly establish this exact ovarian-cyst mechanism." }
];

const parse = (text) => { const token = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = text.indexOf(token) + token.length; const end = text.indexOf("];", start); if (start < token.length || end < 0) throw new Error("OCR draft export not found"); return { start, end, drafts: JSON.parse(text.slice(start, end + 1)) }; };
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const record = (draft) => ({ stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [], explanation: draft.explanation ?? "", learningNote: draft.learningNote ?? "", highYieldNote: draft.highYieldNote ?? "", mnemonic: draft.mnemonic ?? "", memoryAid: draft.memoryAid ?? null });
const check = (live, snapshot, item) => { if (!live || !snapshot || live.id !== item.id || snapshot.id !== item.id || live.sourcePage !== item.page || snapshot.sourcePage !== item.page || live.stem !== item.expectedStem || snapshot.stem !== item.expectedStem || !same(live.options, item.expectedOptions) || !same(snapshot.options, item.expectedOptions)) throw new Error(`Immutable literal drift check failed: ${item.id}`); };

const text = await readFile(bankPath, "utf8");
const parsed = parse(text);
const snapshots = new Map(JSON.parse(await readFile(snapshotPath, "utf8")).records.map((item) => [item.id, item]));
const live = new Map(parsed.drafts.map((item) => [item.id, item]));
const applied = [];
const restricted = [];
for (const item of restorations) { const draft = live.get(item.id); check(draft, snapshots.get(item.id), item); const before = record(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.fact, learningNote: item.fact, highYieldNote: item.fact, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); delete draft.approved; applied.push({ id: item.id, sourcePage: item.page, before, after: record(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
for (const item of restrictions) { const draft = live.get(item.id); check(draft, snapshots.get(item.id), item); const before = record(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] }); delete draft.memoryAid; delete draft.approved; restricted.push({ id: item.id, sourcePage: item.page, before, after: record(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${text.slice(0, parsed.start)}${JSON.stringify(parsed.drafts)}${text.slice(parsed.end + 1)}`);
await mkdir(path.dirname(artifactPath), { recursive: true });
await writeFile(artifactPath, `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.length, restricted: restricted.length, automaticApproval: false }, null, 2));
