import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0826-q0036", 826, "The pre-aortic lymph nodes receive lymph from all of the following structures EXCEPT for the:", ["Pancreas", "Spleen", "Sigmoid colon"], "The pre-aortic lymph nodes receive lymph from all of the following structures except the:", ["Kidneys", "Pancreas", "Spleen", "Sigmoid colon", "Appendix"], 0, "Pre-aortic lymph nodes receive lymph from abdominal GI viscera including pancreas, spleen, sigmoid colon, and appendix. Kidneys drain to the lateral aortic (para-aortic) nodes.", "Kidneys drain to para-aortic rather than pre-aortic nodes.", "Pre-aortic nodes drain GI viscera; kidneys drain to para-aortic nodes.", "🫘 KIDNEYS keep to the PARA-aortic lane.", aid("Kidneys drain to the para-aortic lymph nodes; pre-aortic nodes receive drainage from GI viscera and accessory organs.", "Kidneys keep to the para-aortic lane.", ["🫘", "➡️"], "Kidney and direction cues retain the nodal pathway.", "NCBI Bookshelf: Posterior Abdominal Wall Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK532972/"), "https://www.ncbi.nlm.nih.gov/books/NBK532972/", "NCBI distinguishes pre-aortic visceral drainage from para-aortic renal drainage."),
  r("anatomy-anatomy-all-pdf-p0829-q0037", 829, "The quadrate and caudate lobes of the liver are separated by which of the following structures:", ["Ligamentum venosum", "Gallbladder", "Inferior vena cava"], "The quadrate and caudate lobes of the liver are separated by which structure?", ["Ligamentum venosum", "Ligamentum teres", "Gallbladder", "Inferior vena cava", "Porta hepatis"], 4, "The porta hepatis is the transverse fissure between the caudate lobe posteriorly and the quadrate lobe anteriorly on the visceral liver surface.", "Porta hepatis lies between caudate and quadrate lobes.", "Porta hepatis forms the transverse fissure between caudate and quadrate lobes.", "🚪 PORTA is the liver gate between CAUDATE and QUADRATE.", aid("The porta hepatis is the transverse fissure between the caudate and quadrate lobes on the visceral liver surface.", "Porta is the gate between caudate and quadrate.", ["🚪", "🟫"], "Gate and liver cues retain the fissure relation.", "NCBI Bookshelf: Liver", "https://www.ncbi.nlm.nih.gov/books/NBK500014/"), "https://www.ncbi.nlm.nih.gov/books/NBK500014/", "NCBI places the porta hepatis between the caudate and quadrate lobe boundaries."),
  r("anatomy-anatomy-all-pdf-p0836-q0038", 836, "The superficial inguinal ring is located at which of the following sites:", ["Just superior to the midpoint of the inguinal ligament (x) Superior to a point midway between the anterior superior iliac spine and the pubic symphysis 13%", "Superior to a point midway between the anterior superior iliac spine and the pubic tubercle", "Immediately lateral to the inferior epigastric vessels"], "The superficial inguinal ring is located at which site?", ["Just superior to the midpoint of the inguinal ligament", "Superior to a point midway between the anterior superior iliac spine and the pubic symphysis", "Superior to a point midway between the anterior superior iliac spine and the pubic tubercle", "Just superior to the pubic tubercle", "Immediately lateral to the inferior epigastric vessels"], 3, "The superficial inguinal ring is the terminal opening of the inguinal canal in the external oblique aponeurosis, just superior to the pubic tubercle.", "Superficial ring lies just superior to pubic tubercle.", "Superficial inguinal ring lies just superior to the pubic tubercle.", "🔔 SUPERFICIAL ring sits just ABOVE the PUBIC tubercle.", aid("The superficial inguinal ring is the terminal opening of the inguinal canal and lies just superior to the pubic tubercle.", "Superficial ring sits above pubic tubercle.", ["🔔", "⬆️"], "Ring and upward cues retain the surface landmark.", "NCBI Bookshelf: Inguinal Region", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), "https://www.ncbi.nlm.nih.gov/books/NBK470204/", "NCBI explicitly locates the superficial inguinal ring just superior to the pubic tubercle."),
  r("anatomy-anatomy-all-pdf-p0844-q0040", 844, "ww The anterior abdominal wall muscles are innervated by:", ["The anterior rami of L1 - L3 6%", "The anterior rami of T7 - T12 and L1", "The anterior rami of T12 and L1 - L4 15%", "The phrenic nerve 1%", "The anterior rami of T7 - T10 6%"], "The anterior abdominal wall muscles are innervated by which nerves?", ["The anterior rami of L1 - L3", "The anterior rami of T7 - T12 and L1", "The anterior rami of T12 and L1 - L4", "The phrenic nerve", "The anterior rami of T7 - T10"], 1, "The abdominal-wall muscles receive segmental innervation through thoracoabdominal nerves T7 to T12 and L1 branches, including iliohypogastric and ilioinguinal nerves.", "Anterior abdominal wall: T7–T12 plus L1.", "Thoracoabdominal T7–T12 plus L1 innervate the abdominal wall.", "7️⃣➡️1️⃣ T7–T12 plus L1 wrap the abdominal wall.", aid("Thoracoabdominal nerves T7 to T12 and L1 branches supply the abdominal-wall muscles.", "T7 to T12 plus L1 make the wall run.", ["7️⃣", "1️⃣"], "Segment-number cues retain the motor supply.", "NCBI Bookshelf: Anterolateral Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK556034/"), "https://www.ncbi.nlm.nih.gov/books/NBK556034/", "NCBI identifies T7–T12 thoracoabdominal nerves and L1 branches as the abdominal-wall supply."),
  r("anatomy-anatomy-all-pdf-p0847-q0041", 847, "Regarding the appendix, which of the following statements is CORRECT:", ["The appendix has a highly variable attachment site to the caecum.", "The appendix is a retroperitoneal structure. (x) The surface projection of the base of the appendix is called Murphy's point. 71%", "The subcaecal position is the most common position of the appendix."], "Regarding the appendix, which statement is correct?", ["The psoas sign may be positive in retrocaecal appendicitis.", "The appendix has a highly variable attachment site to the caecum.", "The appendix is a retroperitoneal structure.", "The surface projection of the base of the appendix is called Murphy's point.", "The subcaecal position is the most common position of the appendix."], 0, "A retrocaecal appendix can irritate iliopsoas. Extending the right hip stretches the muscle and can elicit the psoas sign in appendicitis.", "Retrocaecal appendix can cause a psoas sign on hip extension.", "Hip extension stretches iliopsoas and can cause a psoas sign with retrocaecal appendicitis.", "🦵 EXTEND the hip: retrocaecal appendix can trigger PSOAS pain.", aid("A retrocaecal appendix can cause a psoas sign because right-hip extension stretches the adjacent iliopsoas muscle.", "Hip extension stretches the psoas beside a retrocaecal appendix.", ["🦵", "⚠️"], "Hip and warning cues retain the examination sign.", "NCBI Bookshelf: Appendix", "https://www.ncbi.nlm.nih.gov/books/NBK459205/"), "https://www.ncbi.nlm.nih.gov/books/NBK459205/", "NCBI describes pain on right-hip extension from a retrocecal appendix as the psoas sign."),
  r("anatomy-anatomy-all-pdf-p0850-q0042", 850, "Ld The arterial supply to the colon is derived predominantly from which of the following:", ["Lumbar arteries 1%", "Superior and inferior mesenteric arteries", "Renal artery 0%", "Common iliac artery 1%"], "The arterial supply to the colon is derived predominantly from which arteries?", ["Coeliac trunk", "Lumbar arteries", "Superior and inferior mesenteric arteries", "Renal artery", "Common iliac artery"], 2, "The superior mesenteric artery supplies the proximal colon and the inferior mesenteric artery supplies the distal colon, with collateral connections at the mesenteric border.", "SMA supplies proximal colon; IMA supplies distal colon.", "The colon receives its major arterial supply from the superior and inferior mesenteric arteries.", "⬆️ SMA up-colon, ⬇️ IMA down-colon.", aid("The superior mesenteric artery supplies proximal colon and the inferior mesenteric artery supplies distal colon.", "SMA up-colon, IMA down-colon.", ["⬆️", "⬇️"], "Direction cues retain proximal and distal mesenteric supply.", "NCBI Bookshelf: Gastrointestinal Circulation", "https://www.ncbi.nlm.nih.gov/books/NBK53099/"), "https://www.ncbi.nlm.nih.gov/books/NBK53099/", "NCBI identifies SMA supply to proximal colon and IMA supply to distal colon."),
  r("anatomy-anatomy-all-pdf-p0855-q0043", 855, "Which of the following is a retroperitoneal structure: Sigmoid colon 1% lleum 2% Liver 1%", [], "Which of the following is a retroperitoneal structure?", ["Sigmoid colon", "Second part of duodenum", "Ileum", "Liver", "Spleen"], 1, "The second, third, and fourth parts of the duodenum are secondarily retroperitoneal. The second part is therefore the correct option.", "Duodenum parts 2–4 are retroperitoneal.", "Duodenal parts 2–4 are retroperitoneal; the second part is a standard example.", "2️⃣–4️⃣ DUODENUM hugs the posterior wall.", aid("Duodenal parts 2 to 4 are secondarily retroperitoneal; the second part is therefore retroperitoneal.", "Duodenum 2 to 4 hugs the posterior wall.", ["2️⃣", "🧱"], "Number and wall cues retain the peritoneal relation.", "NCBI Bookshelf: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), "https://www.ncbi.nlm.nih.gov/books/NBK553104/", "NCBI lists duodenal parts 2 to 4 as retroperitoneal structures."),
  r("anatomy-anatomy-all-pdf-p0858-q0044", 858, "A 65 year old man presents to ED complaining of abdominal pain and weight loss. Imaging shows a tumour anterior to the inferior vena cava. Which of the following structures is most likely to be compressed by this tumour:", ["Cisterna chyli 6%", "Third part of the duodenum", "Right kidney 54% (x) Ascending colon 2%", "Right sympathetic trunk 4%"], "A 65-year-old man presents to the ED with abdominal pain and weight loss. Imaging shows a tumour anterior to the inferior vena cava. Which structure is most likely to be compressed by this tumour?", ["Cisterna chyli", "Third part of the duodenum", "Right kidney", "Ascending colon", "Right sympathetic trunk"], 1, "The third part of the duodenum crosses from right to left anterior to both the abdominal aorta and inferior vena cava, making it vulnerable to anterior IVC masses.", "Third duodenum crosses anterior to IVC and aorta.", "The third part of the duodenum passes anterior to the IVC and aorta.", "3️⃣ DUODENUM crosses in FRONT of IVC and AORTA.", aid("The third part of the duodenum courses anterior to the inferior vena cava and abdominal aorta.", "Third duodenum crosses in front of both great vessels.", ["3️⃣", "➡️"], "Part number and crossing cues retain the relation.", "NCBI Bookshelf: Duodenum", "https://www.ncbi.nlm.nih.gov/books/NBK482390/"), "https://www.ncbi.nlm.nih.gov/books/NBK482390/", "NCBI states that the third duodenal segment courses anterior to the aorta and IVC."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0840-q0039", page: 840, expectedStem: "The abdominal aorta lies posterior to which of the following parts of the duodenum:", expectedOptions: ["First part", "First and second parts", "Second and third parts"], stem: "The abdominal aorta lies posterior to which parts of the duodenum?", options: ["First part", "Second part", "First and second parts", "Second and third parts", "Third and fourth parts"], warning: "Source page reviewed, but external evidence explicitly confirms the third-part relation only and does not corroborate the exact combined third-and-fourth formulation; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482390/", finding: "NCBI states that the third part passes anterior to the aorta and IVC, but does not corroborate the exact combined third-and-fourth keyed formulation." },
  { id: "anatomy-anatomy-all-pdf-p0862-q0045", page: 862, expectedStem: "ww The ilioinguinal nerve innervates which of the following muscles:", expectedOptions: ["Internal and external oblique muscles 9%", "Internal oblique and transversus abdominis muscles", "Transversus abdominis and rectus abdominis muscles 8%", "Psoas major and minor muscles 10%", "Quadratus lumborum 5%"], stem: "The ilioinguinal nerve innervates which muscles?", options: ["Internal and external oblique muscles", "Internal oblique and transversus abdominis muscles", "Transversus abdominis and rectus abdominis muscles", "Psoas major and minor muscles", "Quadratus lumborum"], warning: "Source page reviewed, but external evidence also records external-oblique motor contribution, so the exact isolated two-muscle formulation is not corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK556034/", finding: "NCBI records ilioinguinal motor contribution to transversus abdominis, internal oblique, and external oblique, conflicting with the exact isolated source key." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-28.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
