import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0650-q0039", 650, "Ad A79 year old man presents to ED complaining of fever and left sided abdominal and back pain. Imaging reveals a large perinephric abscess. Which of the following most likely describes the fluid location:", ["Between the renal cortex and the renal capsule", "Between the renal capsule and the perinephric fat 31%", "Between the renal capsule and the renal fascia", "Between the renal fascia and the paranephric fat 13%", "Within the paranephric fat 3%"], "A 79-year-old man has a large perinephric abscess. Which description best identifies the fluid location?", ["Between the renal cortex and the renal capsule", "Between the renal capsule and the perinephric fat", "Between the renal capsule and the renal fascia", "Between the renal fascia and the paranephric fat", "Within the paranephric fat"], 2, "A perinephric abscess lies in the perinephric space, external to the renal capsule and internal to the renal fascia (Gerota fascia).", "Perinephric space lies between capsule and renal fascia.", "Perinephric fluid occupies the space between the renal capsule and renal fascia.", "🫘 Capsule INSIDE, fascia OUTSIDE.", aid("The perinephric space lies between the renal capsule and renal fascia.", "Capsule inside, fascia outside.", ["🫘", "⬅️", "➡️"], "Inside and outside cues retain the perinephric boundaries.", "NCBI Bookshelf: Perinephric Abscess", "https://www.ncbi.nlm.nih.gov/books/NBK536936/"), "https://www.ncbi.nlm.nih.gov/books/NBK536936/", "NCBI describes a perinephric abscess in the compartment defined by the renal capsule and Gerota fascia."),
  r("anatomy-anatomy-all-pdf-p0651-q0040", 651, "we A patient is brought to ED following abdominal trauma. Your consultant performs a FAST scan in the department and identifies fluid in Morison's pouch. Where is Morison's pouch located:", ["Left perinepatic space", "Left subphrenic space 7%", "Right subphrenic space 14%", "Right subhepatic space", "Left infracolic space 2%"], "A trauma FAST scan identifies fluid in Morison's pouch. Where is Morison's pouch located?", ["Left perihepatic space", "Left subphrenic space", "Right subphrenic space", "Right subhepatic space", "Left infracolic space"], 3, "Morison's pouch is the right hepatorenal recess, a dependent space between the liver and right kidney in the right subhepatic region.", "Morison pouch is the right hepatorenal recess.", "Morison's pouch is the right subhepatic hepatorenal recess.", "🫗 Liver + right kidney = MORISON pouch.", aid("Morison's pouch is the right hepatorenal recess in the right subhepatic space.", "Liver and right kidney make Morison's pouch.", ["🫗", "🫁", "🫘"], "Fluid, liver, and kidney cues retain the FAST location.", "NCBI Bookshelf: Focused Assessment With Sonography for Trauma", "https://www.ncbi.nlm.nih.gov/books/NBK470479/"), "https://www.ncbi.nlm.nih.gov/books/NBK470479/", "NCBI identifies Morrison pouch as the hepatorenal recess assessed during FAST."),
  r("anatomy-anatomy-all-pdf-p0652-q0041", 652, "ww The renal artery is derived from which of the following blood vessels:", ["Abdominal aorta", "Coeliac trunk 5% (x) Superior mesenteric artery 3%", "Inferior mesenteric artery 1%", "Superior epigastric artery 1%"], "The renal artery is derived from which blood vessel?", ["Abdominal aorta", "Coeliac trunk", "Superior mesenteric artery", "Inferior mesenteric artery", "Superior epigastric artery"], 0, "Each renal artery arises directly from the lateral aspect of the abdominal aorta, usually just inferior to the superior mesenteric artery origin.", "Renal arteries arise directly from the abdominal aorta.", "The renal arteries arise directly from the abdominal aorta.", "🫘 Renal arteries leave the AORTA.", aid("Each renal artery arises directly from the abdominal aorta.", "Kidneys receive from the aorta.", ["🫘", "🩸"], "Kidney and blood-vessel cues retain the origin.", "NCBI Bookshelf: Posterior Abdominal Wall Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK532972/"), "https://www.ncbi.nlm.nih.gov/books/NBK532972/", "NCBI states that renal arteries arise from the aorta."),
  r("anatomy-anatomy-all-pdf-p0653-q0042", 653, "A 54 year old man presents to ED complaining of abdominal pain radiating to his back. Imaging shows a tumour at the neck of the pancreas. Which of the following structures would first receive metastatic cells from this tumour: Spleen 5%", ["Stomach", "Duodenum", "Spine"], "A man has a tumour at the neck of the pancreas. Which structure would first receive metastatic cells through venous drainage?", ["Spleen", "Stomach", "Duodenum", "Liver", "Spine"], 3, "Venous drainage from the pancreas enters the portal system, which carries blood to the liver. The liver is therefore the first listed organ to receive hematogenous metastatic cells.", "Pancreatic venous drainage reaches the liver through the portal system.", "Portal venous drainage makes the liver the first listed hematogenous destination for pancreatic tumour cells.", "🩸 PANCREAS → portal vein → LIVER.", aid("Pancreatic venous drainage enters the portal system and reaches the liver.", "Pancreas portals to liver.", ["🩸", "➡️", "🫁"], "Flow and liver cues retain the portal destination.", "NCBI Bookshelf: Portal Venous System", "https://www.ncbi.nlm.nih.gov/books/NBK554589/"), "https://www.ncbi.nlm.nih.gov/books/NBK554589/", "NCBI describes portal-system drainage from the pancreas to the liver."),
  r("anatomy-anatomy-all-pdf-p0654-q0043", 654, "ww The lateral femoral cutaneous nerve innervates which of the following:", ["Skin over the genitalia (v’) skin over the lateral thigh 91%", "Skin over the medial thigh 4%", "Skin over the posterior thigh 1%", "Skin over the lateral leg 3%"], "The lateral femoral cutaneous nerve innervates which skin territory?", ["Skin over the genitalia", "Skin over the lateral thigh", "Skin over the medial thigh", "Skin over the posterior thigh", "Skin over the lateral leg"], 1, "The lateral femoral cutaneous nerve is purely sensory and supplies skin of the anterolateral and lateral thigh, without motor function.", "LFCN supplies lateral thigh skin.", "The lateral femoral cutaneous nerve is sensory to the lateral thigh.", "🦵 LFCN = LATERAL THIGH feeling.", aid("The lateral femoral cutaneous nerve supplies sensation to the lateral thigh.", "LFCN means lateral thigh feeling.", ["🦵", "↔️"], "Thigh and lateral-direction cues retain the sensory territory.", "NCBI Bookshelf: Lateral Femoral Cutaneous Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK532301/"), "https://www.ncbi.nlm.nih.gov/books/NBK532301/", "NCBI describes LFCN cutaneous sensation to the anterolateral and lateral thigh."),
  r("anatomy-anatomy-all-pdf-p0655-q0044", 655, "ww The iliohypogastric nerve supplies skin over which of the following regions:", ["Posterolateral gluteal region", "Medial thigh 12%", "Lateral thigh 4%", "Posteromedial gluteal region 17%", "Upper anterior thigh 19%"], "The iliohypogastric nerve supplies skin over which region?", ["Posterolateral gluteal region", "Medial thigh", "Lateral thigh", "Posteromedial gluteal region", "Upper anterior thigh"], 0, "The iliohypogastric nerve supplies the lateral gluteal region through its lateral cutaneous branch and also contributes sensation above the pubis through its anterior cutaneous branch.", "Iliohypogastric gives lateral gluteal sensation.", "Iliohypogastric sensory territory includes the posterolateral gluteal region.", "🍑 ILIOHYPO reaches the lateral GLUTEAL skin.", aid("The iliohypogastric nerve provides sensory input to the lateral gluteal area.", "Iliohypo reaches lateral gluteal skin.", ["🍑", "↔️"], "Gluteal and lateral cues retain the cutaneous branch territory.", "NCBI Bookshelf: Lumbar Plexus", "https://www.ncbi.nlm.nih.gov/books/NBK545137/"), "https://www.ncbi.nlm.nih.gov/books/NBK545137/", "NCBI gives the iliohypogastric nerve sensory territory as the lateral gluteal area."),
  r("anatomy-anatomy-all-pdf-p0656-q0045", 656, "wy Which of the following is the most common position of the vermiform appendix:", ["Pre-ileal 2%", "Post-ileal 3%", "Retrocaecal", "Pelvic 4%"], "Which is the most common position of the vermiform appendix?", ["Pre-ileal", "Post-ileal", "Subcaecal", "Retrocaecal", "Pelvic"], 3, "The appendix tip has variable positions, but the retrocaecal position is the most common. A retrocaecal appendix can produce atypical flank or psoas-related symptoms in appendicitis.", "Retrocaecal is the commonest appendix position.", "The retrocaecal position is by far the most common appendix position.", "↩️ Appendix most often hides RETROCAECAL.", aid("The retrocaecal position is the most common appendix position.", "Appendix most often hides retrocaecal.", ["↩️", "🪱"], "Backward-direction and appendix cues retain the common position.", "NCBI Bookshelf: Appendix", "https://www.ncbi.nlm.nih.gov/books/NBK459205/"), "https://www.ncbi.nlm.nih.gov/books/NBK459205/", "NCBI states that retrocaecal is by far the most common appendix position."),
  r("anatomy-anatomy-all-pdf-p0659-q0046", 659, "A 49 year old man presents to ED with a few months history of abdominal pain, weight loss and jaundice. Imaging shows a tumour in the uncinate process of the pancreas. Which of the following structures is most likely compressed by this tumour:", ["Cystic duct", "Main pancreatic duct 23%", "Superior mesenteric artery", "Portal vein 16%"], "A man has a tumour in the uncinate process of the pancreas. Which structure is most likely compressed?", ["Cystic duct", "Main pancreatic duct", "Superior mesenteric artery", "Portal vein", "Splenic artery"], 2, "The uncinate process lies posterior to the superior mesenteric artery. A mass in the uncinate process can therefore affect this adjacent vessel.", "Uncinate process lies behind the superior mesenteric artery.", "The uncinate process is posterior to the superior mesenteric artery.", "🏹 UNCINATE sits behind the SMA.", aid("The uncinate process lies posterior to the superior mesenteric artery.", "Uncinate sits behind the SMA.", ["🏹", "🩸"], "Uncinate-hook and vessel cues retain the relationship.", "NCBI Bookshelf: Superior Mesenteric Artery", "https://www.ncbi.nlm.nih.gov/books/NBK519560/"), "https://www.ncbi.nlm.nih.gov/books/NBK519560/", "NCBI states that the uncinate process lies posterior to the superior mesenteric artery."),
  r("anatomy-anatomy-all-pdf-p0660-q0047", 660, "The lymphatics of the glans penis drain primarily to which of the following lymph nodes:", ["Internal iliac nodes", "External iliac nodes", "Superficial inguinal nodes", "Paraaortic nodes"], "The lymphatics of the glans penis drain primarily to which lymph nodes?", ["Internal iliac nodes", "External iliac nodes", "Superficial inguinal nodes", "Deep inguinal nodes", "Paraaortic nodes"], 3, "Lymphatics from the glans penis drain to the deep inguinal lymph nodes. By contrast, skin of the penis and prepuce drain mainly to superficial inguinal nodes.", "Glans drains deep; penile skin drains superficial.", "The glans penis drains primarily to deep inguinal lymph nodes.", "🔎 GLANS goes DEEP inguinal.", aid("The glans penis drains primarily to deep inguinal lymph nodes.", "Glans goes deep; skin goes superficial.", ["🔎", "⬇️"], "Glans and depth cues distinguish deep from superficial drainage.", "NCBI Bookshelf: Inguinal Lymph Node", "https://www.ncbi.nlm.nih.gov/books/NBK557639/"), "https://www.ncbi.nlm.nih.gov/books/NBK557639/", "NCBI specifies glans-penis drainage to deep inguinal nodes."),
  r("anatomy-anatomy-all-pdf-p0663-q0048", 663, "ww Pain in the jejunum and ileum is typically referred to which of the following regions:", ["Flank 2%", "Epigastrium 1%", "Left upper quadrant 8%", "Umbilical region"], "Pain in the jejunum and ileum is typically referred to which region?", ["Flank", "Epigastrium", "Left upper quadrant", "Right lower quadrant", "Umbilical region"], 4, "Jejunum and ileum are midgut structures. Visceral pain from the midgut is poorly localized and is typically referred to the umbilical region.", "Midgut pain refers to the umbilicus.", "Jejunal and ileal visceral pain refers to the umbilical region.", "🧭 MIDGUT points to the UMBILICUS.", aid("Midgut visceral pain, including jejunal and ileal pain, refers to the umbilicus.", "Midgut points to the umbilicus.", ["🧭", "⭕"], "Midgut-direction and umbilicus cues retain the referral pattern.", "NCBI Bookshelf: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), "https://www.ncbi.nlm.nih.gov/books/NBK553104/", "NCBI states that midgut pain is referred to the umbilicus.")
];

function parse(source) { const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = source.indexOf(prefix); const a = start + prefix.length; const e = source.indexOf("];", a); if (start < 0 || e < 0) throw new Error("OCR draft export not found"); return { a, e, drafts: JSON.parse(source.slice(a, e + 1)) }; }
function guard(draft, item) { if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`); if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`); }

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((d) => [d.id, d]));
const applied = [];
for (const item of restorations) {
  const d = byId.get(item.id);
  guard(d, item);
  const before = { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings ?? [] };
  Object.assign(d, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: { stem: d.stem, options: d.options, correctOption: d.correctOption, status: d.status, askable: d.askable, warnings: d.warnings }, evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}
await writeFile(bankPath, `${source.slice(0, parsed.a)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.e + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-22.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted: [], automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((v) => v.id), restricted: [], automaticApproval: false }, null, 2));
