import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const snapshotPath = path.join(root, "docs", "audit", "anatomy-all-pdf-batch-33-ocr-records.json");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel: "Source-confirmed anatomy fact", sourceLabel, sourceUrl });
const restore = (id, page, stem, options, correctOption, fact, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, stem, options, correctOption, fact, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  restore("anatomy-anatomy-all-pdf-p1033-q0086", 1033, "Which of the following structures is NOT retroperitoneal:", ["Abdominal oesophagus", "Adrenal glands", "Ascending colon", "Descending colon", "Proximal duodenum"], 4, "The proximal first part of the duodenum is intraperitoneal, whereas the more distal duodenal segments are retroperitoneal.", "Proximal D1 is the peritoneal exception.", aid("The proximal first part of the duodenum is intraperitoneal; the remaining duodenum is mostly retroperitoneal.", "D1 starts free before the duodenum fixes.", ["1️⃣", "📍"], "NCBI Bookshelf: Duodenum", "https://www.ncbi.nlm.nih.gov/books/NBK482390/"), "https://www.ncbi.nlm.nih.gov/books/NBK482390/", "NCBI describes the first duodenal portion as the intraperitoneal exception."),
  restore("anatomy-anatomy-all-pdf-p1036-q0087", 1036, "The lumbar plexus is formed predominantly from the anterior rami of:", ["L2 - L3", "L1 - L5", "L1 - L4", "L1 - L2", "L2 - L5"], 2, "The lumbar plexus is formed predominantly by anterior rami of L1–L4, with possible T12 contribution.", "Lumbar plexus: L1 to L4.", aid("The lumbar plexus is predominantly formed by the anterior rami of L1 through L4.", "Lumbar starts at 1 and ends at 4.", ["1️⃣", "4️⃣"], "NCBI Bookshelf: Lumbar Plexus", "https://www.ncbi.nlm.nih.gov/books/NBK564296/"), "https://www.ncbi.nlm.nih.gov/books/NBK564296/", "NCBI identifies L1–L4 anterior rami as the predominant lumbar-plexus roots."),
  restore("anatomy-anatomy-all-pdf-p1040-q0088", 1040, "In men, the external urethral sphincter surrounds which of the following structures:", ["Preprostatic urethra", "Prostatic urethra", "Membranous urethra", "Spongy urethra", "External urethral orifice"], 2, "The male external urethral sphincter surrounds the membranous urethra in the deep perineal region.", "External sphincter grips the membranous urethra.", aid("The external urethral sphincter surrounds the membranous urethra.", "Membranous means muscle-wrapped.", ["💪", "📍"], "NCBI Bookshelf: Male Urethra", "https://www.ncbi.nlm.nih.gov/books/NBK542238/"), "https://www.ncbi.nlm.nih.gov/books/NBK542238/", "NCBI describes skeletal external-sphincter muscle around the membranous urethra."),
  restore("anatomy-anatomy-all-pdf-p1044-q0089", 1044, "A 65 year old lady complains of faecal incontinence. Dysfunction of which of the following structures is most likely a contributing factor to her symptoms:", ["Pectineus muscle", "Puborectalis muscle", "Iliococcygeus muscle", "Transverse perineal muscles", "Coccygeus muscle"], 1, "Puborectalis maintains the anorectal angle and is an important continence mechanism.", "Puborectalis preserves the anorectal angle for continence.", aid("Puborectalis forms the anorectal sling and supports continence by maintaining the anorectal angle.", "Puborectalis pulls the rectum into continence.", ["🔒", "↪️"], "NCBI Bookshelf: Anorectal Anatomy", "https://www.ncbi.nlm.nih.gov/books/NBK459128/"), "https://www.ncbi.nlm.nih.gov/books/NBK459128/", "NCBI and peer-reviewed evidence identify puborectalis as a major continence mechanism."),
  restore("anatomy-anatomy-all-pdf-p1048-q0090", 1048, "A 29 year old rugby player presents to ED complaining of left flank pain. Imaging shows a fracture of the angle of the twelfth rib on the left side. Which of the following organs, based on surface anatomy, is most at risk for injury:", ["Spleen", "Left kidney", "Pancreas", "Stomach", "Transverse colon"], 1, "The upper left kidney is related posteriorly to the twelfth rib, although individual surface relations may vary.", "Twelfth rib: consider the left kidney.", aid("The upper pole of the left kidney lies near the twelfth rib; surface relationships vary between individuals.", "Rib 12 is near the kidney shelf.", ["1️⃣2️⃣", "🫘"], "NCBI Bookshelf: Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385/"), "https://www.ncbi.nlm.nih.gov/books/NBK482385/", "NCBI describes the superior renal pole as commonly crossed by the twelfth rib; the learning aid preserves this as a non-invariant surface relation."),
  restore("anatomy-anatomy-all-pdf-p1050-q0092", 1050, "A 65 year old woman presents to ED complaining of fever, right upper quadrant pain, and jaundice. Imaging shows an obstructing gallstone. Which of the following structures is most likely obstructed by the gallstone:", ["Pancreatic duct", "Cystic duct", "Left hepatic duct", "Common bile duct", "Right hepatic duct"], 3, "A gallstone obstructing the common bile duct can cause obstructive jaundice and cholangitis.", "Common duct blockage causes bile backup.", aid("Choledocholithiasis obstructs the common bile duct and can cause pain, jaundice, and cholangitis.", "Common duct blocked, common bile backs up.", ["🟡", "🚧"], "NCBI Bookshelf: Choledocholithiasis", "https://www.ncbi.nlm.nih.gov/books/NBK441961/"), "https://www.ncbi.nlm.nih.gov/books/NBK441961/", "NCBI identifies common-bile-duct stones and obstruction as causes of jaundice and cholangitis."),
  restore("anatomy-anatomy-all-pdf-p1053-q0093", 1053, "The deep inguinal ring is an 'opening' in which of the following structures:", ["External oblique aponeurosis", "Internal oblique aponeurosis", "Transversus abdominis aponeurosis", "Rectus abdominis aponeurosis", "Transversalis fascia"], 4, "The deep inguinal ring is an opening in the transversalis fascia.", "Deep ring equals transversalis fascia.", aid("The deep inguinal ring is a lateral opening formed by transversalis fascia.", "Deep starts with transversalis.", ["🔓", "📍"], "NCBI Bookshelf: Inguinal Canal", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), "https://www.ncbi.nlm.nih.gov/books/NBK470204/", "NCBI identifies the deep inguinal ring as formed by transversalis fascia."),
  restore("anatomy-anatomy-all-pdf-p1060-q0095", 1060, "Pain in the jejunum and ileum is typically referred to which of the following regions:", ["Flank", "Epigastrium", "Left upper quadrant", "Right lower quadrant", "Umbilical region"], 4, "Jejunal and ileal visceral pain is midgut pain and typically refers to the periumbilical region.", "Midgut pain maps to the umbilicus.", aid("Jejunum and ileum are midgut structures, so visceral pain typically refers to the umbilical region.", "Midgut meets the middle at the umbilicus.", ["⭕", "📍"], "NCBI Bookshelf: Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104/"), "https://www.ncbi.nlm.nih.gov/books/NBK553104/", "NCBI and peer-reviewed peritoneal anatomy describe periumbilical referral from jejunal and ileal midgut pain."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p1057-q0094", page: 1057, stem: "The ureters arise at which of the following vertebral levels:", options: ["T10", "T11", "T12", "L1", "L2"], warning: "Source page reviewed, but current authoritative ureter anatomy places the ureteropelvic junction roughly at L2 rather than the source's L1 key; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532980/", finding: "NCBI places the ureteropelvic junction, where renal pelvis transitions to ureter, roughly at L2." },
  { id: "anatomy-anatomy-all-pdf-p1063-q0096", page: 1063, stem: "The psoas major muscle is innervated by which of the following:", options: ["Iliohypogastric nerve", "Ilioinguinal nerve", "Anterior rami of L1 - L3", "Femoral nerve", "Anterior rami of L2 - L4"], warning: "Source page reviewed, but current authoritative sources conflict between L1–L3 and L1–L4 descriptions of psoas-major innervation; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK535418/", finding: "NCBI psoas-major and iliopsoas references give conflicting root ranges, so the exact isolated L1–L3 key is not restored." },
];

function parse(source) { const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const arrayStart = source.indexOf(prefix) + prefix.length; const end = source.indexOf("];", arrayStart); if (arrayStart < prefix.length || end < 0) throw new Error("OCR draft export not found"); return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) }; }
function snapshot(draft) { return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] }; }
function guard(draft, original, item) { if (!draft || !original || draft.sourcePage !== item.page || original.sourcePage !== item.page || draft.stem !== original.stem || JSON.stringify(draft.options) !== JSON.stringify(original.options)) throw new Error(`Immutable drift check failed: ${item.id}`); }

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const immutable = JSON.parse(await readFile(snapshotPath, "utf8")).records;
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const originals = new Map(immutable.map((record) => [record.id, record]));
const applied = [], restricted = [];
for (const item of restorations) { const draft = byId.get(item.id), original = originals.get(item.id); guard(draft, original, item); const before = snapshot(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.fact, learningNote: item.fact, highYieldNote: item.fact, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] }); delete draft.approved; applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
for (const item of restrictions) { const draft = byId.get(item.id), original = originals.get(item.id); guard(draft, original, item); const before = snapshot(draft); Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] }); delete draft.memoryAid; delete draft.approved; restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } }); }
await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-33.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.length, restricted: restricted.length, automaticApproval: false }, null, 2));
