import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0909-q0056", 909, "A patient is brought to ED following abdominal trauma. Your consultant performs a FAST scan in the department and identifies fluid in Morison's pouch. Where is Morison's pouch located: (x) Left perihepatic space 4%", ["Left subphrenic space", "Right subphrenic space 14%", "Right subhepatic space", "Left infracolic space 2%"], "A patient is brought to ED following abdominal trauma. Your consultant performs a FAST scan in the department and identifies fluid in Morison's pouch. Where is Morison's pouch located:", ["Left perihepatic space", "Left subphrenic space", "Right subphrenic space", "Right subhepatic space", "Left infracolic space"], 3, "Morison's pouch is the hepatorenal recess, a dependent right subhepatic space between the right lobe of the liver and the right kidney.", "Morison's pouch is the right subhepatic hepatorenal recess.", "Morison's pouch: right subhepatic space between liver and right kidney.", "🟫 LIVER meets the RIGHT KIDNEY in Morison's pouch.", aid("Morison's pouch is the right subhepatic hepatorenal recess between the right liver lobe and right kidney.", "Liver meets right kidney in Morison's pouch.", ["🟫", "➡️"], "Liver and right-direction cues retain the hepatorenal location.", "PMC: Morrison's Pouch", "https://pmc.ncbi.nlm.nih.gov/articles/PMC9968550/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC9968550/", "Peer-reviewed radiology review identifies Morison's pouch as the right subhepatic hepatorenal recess between the right liver lobe and right kidney."),
  r("anatomy-anatomy-all-pdf-p0916-q0058", 916, "ww The superior pole of the right kidney reaches as high as which of the following: @", ["Rib 9 5%", "Rib 10 1%", "Rib 11 58%", "rib 12"], "The superior pole of the right kidney reaches as high as which of the following:", ["Rib 8", "Rib 9", "Rib 10", "Rib 11", "Rib 12"], 4, "The right kidney lies slightly lower than the left because of the liver; its upper pole is commonly crossed by the 12th rib.", "Right kidney sits lower than left and reaches the 12th rib.", "Right kidney: lower position, upper pole at rib 12.", "➡️1️⃣2️⃣ RIGHT kidney reaches the TWELFTH rib.", aid("The right kidney sits lower than the left and its upper pole reaches the 12th rib.", "Right equals rib twelve.", ["➡️", "1️⃣2️⃣"], "Right-direction and twelve cues retain the surface relation.", "NCBI Bookshelf: Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385/"), "https://www.ncbi.nlm.nih.gov/books/NBK482385/", "NCBI describes the right kidney as lower and the upper renal poles as frequently crossed by the 12th rib."),
  r("anatomy-anatomy-all-pdf-p0925-q0060", 925, "ww The renal pelvis is continuous with which of the following structures:", ["The minor calyx 54%", "The renal pyramid 2%", "The major calyx 9%", "The renal sinus 1% (v’) The ureter 3496"], "The renal pelvis is continuous with which of the following structures:", ["The minor calyx", "The renal pyramid", "The major calyx", "The renal sinus", "The ureter"], 4, "Minor calyces join to form major calyces, which unite as the renal pelvis; the pelvis funnels into the proximal ureter.", "The renal pelvis funnels into the ureter.", "Collecting system: minor calyx → major calyx → renal pelvis → ureter.", "🔻 PELVIS funnels into the URETER.", aid("The renal pelvis is the funnel-shaped transition from major calyces to the proximal ureter.", "Pelvis funnels to ureter.", ["🔻", "➡️"], "Funnel and flow-direction cues retain the collecting-system sequence.", "NCBI Bookshelf: Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385/"), "https://www.ncbi.nlm.nih.gov/books/NBK482385/", "NCBI states that major calyces unite to form the renal pelvis, which transitions to the proximal ureter."),
  r("anatomy-anatomy-all-pdf-p0936-q0062", 936, "ww The right and left hepatic arteries are derived from which of the following blood vessels:", ["Directly from the aorta 6%", "From the coeliac trunk", "From the superior mesenteric artery 7%", "From the inferior mesenteric artery", "From the gastrosplenic artery 4%"], "The right and left hepatic arteries are derived from which of the following blood vessels:", ["Directly from the aorta", "From the coeliac trunk", "From the superior mesenteric artery", "From the inferior mesenteric artery", "From the gastrosplenic artery"], 1, "The common hepatic artery is a coeliac-trunk branch. It gives rise to the proper hepatic artery, which divides into right and left hepatic arteries.", "Right and left hepatic arteries derive through the common/proper hepatic pathway from the coeliac trunk.", "Hepatic arteries trace back through proper and common hepatic arteries to the coeliac trunk.", "🌳 COELIAC trunk grows the hepatic branches.", aid("The right and left hepatic arteries arise from the proper hepatic artery, which is supplied through the common hepatic artery from the coeliac trunk.", "Coeliac trunk grows hepatic branches.", ["🌳", "🫀"], "Tree and liver cues retain the arterial origin.", "NCBI Bookshelf: Celiac Trunk", "https://www.ncbi.nlm.nih.gov/books/NBK459241/"), "https://www.ncbi.nlm.nih.gov/books/NBK459241/", "NCBI identifies the proper hepatic artery as a common-hepatic branch from the coeliac trunk and its division into right and left hepatic arteries."),
  r("anatomy-anatomy-all-pdf-p0942-q0063", 942, "A 23 year old patient is brought to ED following a road traffic accident. CT imaging demonstrates retroperitoneal injury. Which of the following organs is most likely affected:", ["Appendix Sigmoid colon 6%", "Tail of the pancreas"], "A 23 year old patient is brought to ED following a road traffic accident. CT imaging demonstrates retroperitoneal injury. Which of the following organs is most likely affected:", ["Ascending colon", "Spleen", "Appendix", "Sigmoid colon", "Tail of the pancreas"], 0, "The ascending colon is secondarily retroperitoneal. The spleen, appendix, sigmoid colon, and pancreatic tail have intraperitoneal relations.", "Ascending colon is retroperitoneal.", "Ascending colon is the retroperitoneal option among these abdominal structures.", "⬆️ COLON ascends retroperitoneally.", aid("The ascending colon is a secondarily retroperitoneal portion of the large intestine.", "Ascending colon ascends retroperitoneally.", ["⬆️", "🧱"], "Upward and wall cues retain the retroperitoneal relation.", "NCBI Bookshelf: Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385/"), "https://www.ncbi.nlm.nih.gov/books/NBK482385/", "NCBI lists the ascending colon among retroperitoneal structures and identifies the pancreatic tail as embedded in the splenorenal ligament."),
  r("anatomy-anatomy-all-pdf-p0945-q0064", 945, "we A311 year old man is brought to ED following a road traffic accident in which he was wearing his seatbelt. Imaging shows a fracture of the left ninth and tenth rib with intra-abdominal bleeding. Which of the following organs is most likely injured:", ["Liver 2%", "Pancreas 0% (v’) Spleen 94%", "Left kidney 3%", "Left colic flexure 1%"], "A 31 year old man is brought to ED following a road traffic accident in which he was wearing his seatbelt. Imaging shows a fracture of the left ninth and tenth rib with intra-abdominal bleeding. Which of the following organs is most likely injured:", ["Liver", "Pancreas", "Spleen", "Left kidney", "Left colic flexure"], 2, "The spleen spans ribs 9 to 11 in the left hypochondrium and is vulnerable to rupture from left lower-rib injury.", "Left ribs 9–11 protect the spleen; fractures can injure it.", "Spleen lies under left ribs 9–11 and is vulnerable in left lower-rib trauma.", "9️⃣🔟 LEFT lower ribs can injure the SPLEEN.", aid("The spleen spans ribs 9 to 11 in the left hypochondrium and can be punctured by left-rib fractures.", "Left ribs nine to eleven shelter the spleen.", ["9️⃣", "🔟", "🟣"], "Rib-number and splenic cues retain the trauma relation.", "NCBI Bookshelf: Spleen", "https://www.ncbi.nlm.nih.gov/books/NBK482235/"), "https://www.ncbi.nlm.nih.gov/books/NBK482235/", "NCBI places the spleen between ribs 9 and 11 and notes that left-rib fractures can puncture it."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0913-q0057", page: 913, expectedStem: "The termination of the abdominal aorta can be visualised on the anterior abdominal wall by a point:", expectedOptions: ["About 2.5 cm above the umbilicus", "Halfway between the xiphisternum and the umbilicus", "Halfway between the umbilicus and the pubic symphysis", "About 2.5 cm above the deep inguinal ring"], stem: "The termination of the abdominal aorta can be visualised on the anterior abdominal wall by a point:", options: ["About 2.5 cm above the umbilicus", "About 2.5 cm below the umbilicus", "Halfway between the xiphisternum and the umbilicus", "Halfway between the umbilicus and the pubic symphysis", "About 2.5 cm above the deep inguinal ring"], warning: "Source page reviewed, but CT evidence shows substantial variation in aortic-bifurcation position relative to the umbilicus; the exact fixed 2.5-cm landmark is not corroborated; no correct option is inferred.", sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3924739/", finding: "Peer-reviewed CT data show aortic-bifurcation location relative to the umbilicus varies widely, so the exact fixed 2.5-cm formulation is not sufficiently corroborated." },
  { id: "anatomy-anatomy-all-pdf-p0922-q0059", page: 922, expectedStem: "bd Regarding the ureters, which of the following statements is CORRECT:", expectedOptions: ["The bladder drains into the ureters. 1%", "The ureters are continuously superiorly with the renal medulla. 6%", "The ureters descend on the medial aspect of the psoas major muscles.", "The ureters are intraperitoneal structures. 55%", "The left ureter lies in close proximity to the appendix. 2%"], stem: "Regarding the ureters, which of the following statements is CORRECT:", options: ["The bladder drains into the ureters.", "The ureters are continuously superiorly with the renal medulla.", "The ureters descend on the medial aspect of the psoas major muscles.", "The ureters are intraperitoneal structures.", "The left ureter lies in close proximity to the appendix."], warning: "Source page reviewed, but external anatomy evidence describes the ureter as retroperitoneal and anterior to psoas; the exact medial-aspect formulation is not corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532980/", finding: "NCBI describes ureters as retroperitoneal and anterior to the psoas muscle, not with the source's exact medial-aspect wording." },
  { id: "anatomy-anatomy-all-pdf-p0931-q0061", page: 931, expectedStem: "A 65 year old man with known BPH, presents to ED in severe pain due to urinary retention. What is the location of the neural cell bodies responsible for pain sensation from the urinary bladder:", expectedOptions: ["Dorsal root ganglia of spinal cord levels L1- L4", "anglia inal cord levels S2, S3 and S4 Dorsal root ganglia of spinal cord levels T5 - T9 1%", "Dorsal root ganglia of spinal cord levels 110 - T12"], stem: "A 65 year old man with known BPH, presents to ED in severe pain due to urinary retention. What is the location of the neural cell bodies responsible for pain sensation from the urinary bladder:", options: ["Dorsal root ganglia of spinal cord levels L1 - L4", "Dorsal root ganglia of spinal cord levels S2, S3 and S4", "Dorsal root ganglia of spinal cord levels L4 and L5", "Dorsal root ganglia of spinal cord levels T5 - T9", "Dorsal root ganglia of spinal cord levels T10 - T12"], warning: "Source page reviewed, but external evidence identifies lower-urinary-tract afferent neurons in both S2–S4 and T11–L2 dorsal-root ganglia; the broad pain-sensation formulation is non-unique; no correct option is inferred.", sourceUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3383010/", finding: "Peer-reviewed human lower-urinary-tract evidence identifies afferent neurons in both S2–S4 and T11–L2 dorsal-root ganglia, so the marked option is not uniquely corroborated." },
  { id: "anatomy-anatomy-all-pdf-p0949-q0065", page: 949, expectedStem: "Regarding the internal oblique muscle, which of the following statements is CORRECT:", expectedOptions: ["The lower free border of the internal oblique aponeurosis forms the inguinal ligament. 8%", "The internal oblique lies deep to the transversus abdominis muscle. 5% (x) its fibres run in a inferomedial direction. Ws", "It originates from the medial third of the inguinal ligament. 5%", "It inserts onto the lower 3 - 4 ribs and the pubic crest."], stem: "Regarding the internal oblique muscle, which of the following statements is CORRECT:", options: ["The lower free border of the internal oblique aponeurosis forms the inguinal ligament.", "The internal oblique lies deep to the transversus abdominis muscle.", "Its fibres run in a inferomedial direction.", "It originates from the medial third of the inguinal ligament.", "It inserts onto the lower 3 - 4 ribs and the pubic crest."], warning: "Source page reviewed, but external anatomy evidence describes insertion on lower-five-rib cartilages and pubic tubercle; the exact lower-3–4-rib/pubis-crest formulation is not corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK525975/", finding: "NCBI describes internal-oblique insertion on lower-five-rib cartilages and pubic tubercle, not the exact source option formulation." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  delete draft.approved;
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  delete draft.approved;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-30.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
