import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0741-q0014", 741, "A72 year old man presents to ED with severe abdominal pain and diarrhoea. Imaging shows occlusion of the inferior mesenteric artery. Which of the following structures is most likely affected:", ["Ascending and descending colon", "Ascending and transverse colon", "Caecum and transverse colon"], "A 72-year-old man presents to the ED with severe abdominal pain and diarrhoea. Imaging shows occlusion of the inferior mesenteric artery. Which structures are most likely affected?", ["Ascending and descending colon", "Ascending and transverse colon", "Caecum and transverse colon", "Descending and sigmoid colon", "Caecum and ileum"], 3, "The inferior mesenteric artery supplies hindgut structures, including the descending colon and sigmoid colon. Its left-colic and sigmoid branches supply these segments.", "IMA supplies the descending and sigmoid colon.", "Inferior mesenteric artery supplies the left colon, including descending and sigmoid colon.", "⬅️ IMA feeds the LEFT colon: descending then sigmoid.", aid("The IMA supplies the descending colon through its left-colic branch and the sigmoid colon through sigmoid branches.", "IMA = left-sided colon: descending + sigmoid.", ["⬅️", "🫀"], "Left-direction and vessel cues retain IMA territory.", "NCBI Bookshelf: Inferior Mesenteric Artery", "https://www.ncbi.nlm.nih.gov/books/NBK482156/"), "https://www.ncbi.nlm.nih.gov/books/NBK482156/", "NCBI identifies the left-colic and sigmoid branches of the IMA as supplying descending and sigmoid colon."),
  r("anatomy-anatomy-all-pdf-p0746-q0015", 746, "ww The psoas major muscle attaches distally to which of the following: (x) Pubic tubercle 2%", ["Greater trochanter of the femur 1%", "Lesser trochanter of the femur", "lliac crest 13%", "Anterior superior iliac spine 4%"], "The psoas major muscle attaches distally to which structure?", ["Pubic tubercle", "Greater trochanter of the femur", "Lesser trochanter of the femur", "Iliac crest", "Anterior superior iliac spine"], 2, "Psoas major joins iliacus as the iliopsoas tendon, which inserts onto the lesser trochanter of the femur.", "Psoas major inserts at the lesser trochanter.", "Psoas major and iliacus share insertion at the lesser trochanter.", "🦵 PSOAS goes LOW to the LESSER trochanter.", aid("Psoas major joins iliacus and inserts through the iliopsoas tendon onto the lesser trochanter.", "Psoas goes low to lesser trochanter.", ["🦵", "⬇️"], "Lower-direction and femur cues retain the insertion.", "NCBI Bookshelf: Iliopsoas Muscle", "https://www.ncbi.nlm.nih.gov/books/NBK531508/"), "https://www.ncbi.nlm.nih.gov/books/NBK531508/", "NCBI states that psoas major and iliacus converge to insert onto the lesser trochanter."),
  r("anatomy-anatomy-all-pdf-p0756-q0017", 756, "ww The ductus deferens is derived from which of the following structures:", ["Tunica vaginalis", "Ejaculatory ducts 4%", "Seminal vesicle 8% () Epididymis 68%", "Rete testis 3%"], "The ductus deferens continues from which structure?", ["Tunica vaginalis", "Ejaculatory ducts", "Seminal vesicle", "Epididymis", "Rete testis"], 3, "The ductus deferens is the continuation of the epididymal duct from the tail of the epididymis and carries sperm toward the ejaculatory ducts.", "Ductus deferens continues from the epididymis.", "Ductus deferens begins at the tail of the epididymis.", "➡️ EPIDIDYMIS tail hands sperm to the ductus deferens.", aid("The ductus deferens continues from the tail of the epididymis.", "Epididymis tail to ductus trail.", ["➡️", "🧬"], "Direction and sperm-pathway cues retain continuity.", "NCBI Bookshelf: Testes", "https://www.ncbi.nlm.nih.gov/books/NBK470201/"), "https://www.ncbi.nlm.nih.gov/books/NBK470201/", "NCBI describes the epididymis as the sperm conduit and identifies the vas deferens in the testicular outflow pathway; the source key shows epididymis."),
  r("anatomy-anatomy-all-pdf-p0758-q0018", 758, "ww McBurney's point, the surface projection of the base of the appendix is located at which of the following sites:", ["At the junction of the lateral and middle one-thirds of a line extending from the anterior superior iliac spine to the umbilicus. (x) At the midpoint of a line extending from the anterior superior iliac spine to the umbilicus. 9% At the junction of the medial and middle one-thirds of a line extending from the anterior 14% superior iliac spine to the umbilicus. At the midpoint of a line extending from the anterior superior iliac spine to the pubic 6% symphysis.", "At the midpoint of a line extending from the anterior superior iliac spine to the pubic tubercle. 2%"], "McBurney's point, the surface projection of the appendiceal base, is located at which site?", ["At the junction of the lateral and middle thirds of a line from the anterior superior iliac spine to the umbilicus", "At the midpoint of a line from the anterior superior iliac spine to the umbilicus", "At the junction of the medial and middle thirds of a line from the anterior superior iliac spine to the umbilicus", "At the midpoint of a line from the anterior superior iliac spine to the pubic symphysis", "At the midpoint of a line from the anterior superior iliac spine to the pubic tubercle"], 0, "McBurney point lies one-third of the distance from the right anterior superior iliac spine to the umbilicus, equivalently two-thirds of the distance from the umbilicus to the right anterior superior iliac spine.", "McBurney point is at the lateral and middle-third junction on the ASIS–umbilicus line.", "McBurney point is one-third from ASIS toward the umbilicus.", "1️⃣➡️ McBurney: one-third from ASIS toward umbilicus.", aid("McBurney point is at the junction of the lateral and middle thirds of the line from the right ASIS to the umbilicus.", "One-third from ASIS marks McBurney.", ["1️⃣", "➡️", "📍"], "Fraction, direction, and landmark cues retain the surface point.", "NCBI Bookshelf: Appendix", "https://www.ncbi.nlm.nih.gov/books/NBK459205/"), "https://www.ncbi.nlm.nih.gov/books/NBK459205/", "NCBI places McBurney point two-thirds of the distance from the umbilicus to right ASIS, the same surface point."),
  r("anatomy-anatomy-all-pdf-p0768-q0020", 768, "The genitofemoral nerve innervates which of the following muscles: External anal sphincter 5%", ["Bulbospongiosus muscle (x) Superficial transverse perineal muscle 6%", "Deep transverse perineal muscle"], "The genitofemoral nerve innervates which muscle?", ["External anal sphincter", "Male cremaster muscle", "Bulbospongiosus muscle", "Superficial transverse perineal muscle", "Deep transverse perineal muscle"], 1, "The genital branch of the genitofemoral nerve provides motor innervation to the cremaster muscle. Its femoral branch is sensory to the upper anterior thigh.", "Genitofemoral genital branch innervates cremaster.", "Genitofemoral: genital branch to cremaster muscle.", "♂️ Genitofemoral GENITAL branch moves the CREMASTER.", aid("The genital branch of the genitofemoral nerve supplies motor fibres to the male cremaster muscle.", "Genital branch = cremaster.", ["♂️", "⚡"], "Male-genital and motor cues retain the branch action.", "NCBI Bookshelf: Inguinal Canal", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), "https://www.ncbi.nlm.nih.gov/books/NBK470204/", "NCBI states that the genitofemoral genital branch provides motor function to the cremaster muscle."),
  r("anatomy-anatomy-all-pdf-p0776-q0022", 776, "wy Which of the following is the functional unit of the liver:", ["Hepatocyte 22%", "Lobule", "Portal triad 55%", "Lobe 0%"], "Which structure is the functional unit of the liver?", ["Hepatocyte", "Lobule", "Portal triad", "Lobe", "Acinus"], 1, "The hepatic lobule is the functional unit of the liver. Hepatocyte plates radiate toward a central vein, with portal triads at the lobule periphery.", "Lobule is the functional unit of the liver.", "Liver function is organised into hexagonal lobules.", "⬡ LIVER LOBULE: hexagon with central vein.", aid("The liver lobule is the functional unit, with portal triads at its periphery and a central vein in the middle.", "Lobule = liver’s functional hexagon.", ["⬡", "🫀"], "Hexagon and liver cues retain the microscopic unit.", "NCBI Bookshelf: Liver", "https://www.ncbi.nlm.nih.gov/books/NBK500014/"), "https://www.ncbi.nlm.nih.gov/books/NBK500014/", "NCBI explicitly identifies the liver lobule as the functional unit of the liver."),
  r("anatomy-anatomy-all-pdf-p0782-q0023", 782, "A70 year old undergoes radical prostatectomy for prostate cancer. Postoperatively he complains of urinary incontinence due to paralysis of the external urethral sphincter. Which of the following nerves was most likely injured during surgery:", ["Genitofemoral nerve", "Coccygeal nerve Cie", "lliohypogastric nerve"], "A 70-year-old undergoes radical prostatectomy for prostate cancer. Postoperatively, he has urinary incontinence due to paralysis of the external urethral sphincter. Which nerve was most likely injured?", ["Genitofemoral nerve", "Pudendal nerve", "Coccygeal nerve", "Ilioinguinal nerve", "Iliohypogastric nerve"], 1, "The external urethral sphincter is striated muscle under voluntary control via the pudendal nerve, arising from S2 to S4.", "Pudendal nerve (S2–S4) innervates external urethral sphincter.", "External urethral sphincter: voluntary control through pudendal S2–S4.", "🚽 PUDENDAL S2–S4 holds the external sphincter closed.", aid("The pudendal nerve from S2–S4 innervates the voluntary external urethral sphincter.", "Pudendal S2–S4 protects continence.", ["🚽", "2️⃣", "4️⃣"], "Continence and root-number cues retain sphincter innervation.", "NCBI Bookshelf: Sphincter Urethrae", "https://www.ncbi.nlm.nih.gov/books/NBK482438/"), "https://www.ncbi.nlm.nih.gov/books/NBK482438/", "NCBI states that the pudendal nerve from S2–S4 innervates the external urethral sphincter."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0750-q0016", page: 750, expectedStem: "The portal triad comprises all of the following structures EXCEPT for:", expectedOptions: ["Branches of the hepatic vein", "Branches of the portal vein 9%", "Branches of the hepatic artery 6%", "Vagal parasympathetic nerve fibres 22%"], stem: "The portal triad comprises all of the following structures except which?", options: ["Branches of the hepatic vein", "Branches of the portal vein", "Branches of the hepatic artery", "Bile ducts", "Vagal parasympathetic nerve fibres"], warning: "Source page reviewed, but the strict portal-triad definition leaves more than one potential exception; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK500014/", finding: "NCBI defines the portal triad as hepatic-artery, portal-vein, and bile-duct branches; vagal fibres accompany the triad, so the isolated source key is not restored." },
  { id: "anatomy-anatomy-all-pdf-p0761-q0019", page: 761, expectedStem: "The lower pole of the kidneys occurs around the level of:", expectedOptions: ["The disc between L3 and L4 vertebrae (x) The body of the L2 vertebra 4%", "The body of the L4 vertebra", "The disc between L2 and L3 vertebrae 20%", "The disc between L4 and L5 vertebrae"], stem: "The lower pole of the kidneys occurs around which vertebral level?", options: ["The disc between L3 and L4 vertebrae", "The body of the L2 vertebra", "The body of the L4 vertebra", "The disc between L2 and L3 vertebrae", "The disc between L4 and L5 vertebrae"], warning: "Source page reviewed, but the exact L3–L4 disc landmark is not sufficiently corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482385/", finding: "NCBI places kidneys broadly between T12 and L3 but does not validate the exact L3–L4 disc formulation." },
  { id: "anatomy-anatomy-all-pdf-p0772-q0021", page: 772, expectedStem: "ww The floor of the inguinal canal is formed primarily by which of the following structures:", expectedOptions: ["Transversalis fascia 14%", "Medial one-half of the inguinal ligament", "Lateral one-half of the inguinal ligament 8%", "Psoas major muscle 3%"], stem: "The floor of the inguinal canal is formed primarily by which structure?", options: ["Transversalis fascia", "Medial one-half of the inguinal ligament", "Lateral one-half of the inguinal ligament", "Psoas major muscle", "Pectineus muscle"], warning: "Source page reviewed, but the exact “medial one-half” formulation is not sufficiently corroborated; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470204/", finding: "NCBI identifies the inguinal ligament as the canal floor but does not corroborate the exact medial-one-half wording." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-26.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
