import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0787-q0024", 787, "w The abdominal aorta bifurcates into its terminal branches at which of the following vertebral levels:", ["112 1%", "(Les 8%"], "The abdominal aorta bifurcates into its terminal branches at which vertebral level?", ["T12", "L1", "L2", "L3", "L4"], 4, "The abdominal aorta terminates by dividing into the right and left common iliac arteries at the level of L4.", "Aortic bifurcation is at L4.", "Abdominal aorta bifurcates into the common iliac arteries at L4.", "4️⃣ AORTA ends at L4 before the iliac pair begins.", aid("The abdominal aorta bifurcates into the right and left common iliac arteries at L4.", "Aorta ends at L4.", ["4️⃣", "🫀"], "Number and vessel cues retain the bifurcation level.", "NCBI Bookshelf: Posterior Abdominal Wall Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK532972/"), "https://www.ncbi.nlm.nih.gov/books/NBK532972/", "NCBI states that the abdominal aorta bifurcates at L4 into the right and left common iliac arteries."),
  r("anatomy-anatomy-all-pdf-p0791-q0025", 791, "A 49 year old female patient undergoes surgery for uterine cancer. Whilst attempting to ligate the uterine artery, the surgeon accidentally ligates the structure that the uterine artery crosses anteriorly as it passes from the internal iliac artery to the uterus. Which of the following structures has most likely been injured:", ["Ovarian artery", "Ovarian ligament", "Fallopian tube", "Round ligament of uterus"], "A 49-year-old woman undergoes surgery for uterine cancer. While attempting to ligate the uterine artery, the surgeon accidentally ligates the structure that the uterine artery crosses anteriorly as it passes from the internal iliac artery to the uterus. Which structure has most likely been injured?", ["Ovarian artery", "Ovarian ligament", "Ureter", "Fallopian tube", "Round ligament of uterus"], 2, "Near the cervix, the uterine artery crosses anterior to the ureter. This surgical relation explains the ureteric injury risk during hysterectomy.", "The ureter passes beneath the uterine artery near the cervix.", "Uterine artery crosses anterior to ureter near the cervix.", "💧 UNDER the uterine-artery BRIDGE runs the ureter.", aid("The ureter lies beneath the uterine artery near the cervix, creating a risk of ureteric injury during uterine-artery ligation.", "Water under the uterine bridge.", ["💧", "🌉"], "Water and bridge cues retain the ureter–uterine artery relation.", "NCBI Bookshelf: Ureter", "https://www.ncbi.nlm.nih.gov/books/NBK532980/"), "https://www.ncbi.nlm.nih.gov/books/NBK532980/", "NCBI documents the uterine-artery/ureter crossing at the cervix and its importance in gynaecological ureteric injury."),
  r("anatomy-anatomy-all-pdf-p0795-q0026", 795, "Sensation to the skin over the penis is primarily supplied by which of the following nerves:", ["Coccygeal nerve", "llioinguinal nerve", "lliohypogastric nerve"], "Sensation to the skin over the penis is primarily supplied by which nerve?", ["Genitofemoral nerve", "Pudendal nerve", "Coccygeal nerve", "Ilioinguinal nerve", "Iliohypogastric nerve"], 1, "The dorsal nerve of the penis is a terminal branch of the pudendal nerve and carries sensory afferents from penile skin and glans.", "Pudendal nerve provides the main sensory pathway through the dorsal nerve of the penis.", "Dorsal penile sensory fibres arise from the pudendal nerve.", "⚡ PUDENDAL gives the dorsal penile sensory signal.", aid("The dorsal nerve of the penis is a terminal branch of the pudendal nerve and provides sensory afferents to penile skin and glans.", "Pudendal powers penile sensation.", ["⚡", "🧠"], "Signal and sensory cues retain the nerve pathway.", "NCBI Bookshelf: Penis Dorsal Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK525966/"), "https://www.ncbi.nlm.nih.gov/books/NBK525966/", "NCBI identifies the dorsal nerve of the penis as a terminal pudendal branch with sensory afferents to penile skin and glans."),
  r("anatomy-anatomy-all-pdf-p0802-q0029", 802, "ww The rectus sheath is formed by which of the following:", ["the thoracolumbar fascia 1%", "the aponeuroses of the external and internal oblique 8%", "the aponeuroses of the external oblique, internal oblique and transversus abdominis", "the transversalis fascia 5%", "the tendinous intersections of the rectus abdominis 5%"], "The rectus sheath is formed by which structures?", ["The thoracolumbar fascia", "The aponeuroses of the external and internal oblique", "The aponeuroses of the external oblique, internal oblique, and transversus abdominis", "The transversalis fascia", "The tendinous intersections of rectus abdominis"], 2, "The aponeurotic fascial coverings of external oblique, internal oblique, and transversus abdominis form the rectus sheath.", "Rectus sheath is made from the three flat-muscle aponeuroses.", "External oblique, internal oblique, and transversus aponeuroses form the rectus sheath.", "3️⃣ FLAT layers wrap rectus in its sheath.", aid("The rectus sheath is formed by aponeurotic fascial coverings from external oblique, internal oblique, and transversus abdominis.", "Three flat layers form the sheath.", ["3️⃣", "🧥"], "Layer count and covering cues retain sheath formation.", "NCBI Bookshelf: Rectus Sheath", "https://www.ncbi.nlm.nih.gov/books/NBK537153/"), "https://www.ncbi.nlm.nih.gov/books/NBK537153/", "NCBI states that the external-oblique, internal-oblique, and transversus-abdominis fascial coverings comprise the rectus sheath."),
  r("anatomy-anatomy-all-pdf-p0809-q0031", 809, "A19 year old male is brought to ED having sustained a handlebar injury with blunt trauma to his upper abdomen whilst riding his scooter. Which of the following is the most commonly injured organ: Pancreas 8%", ["Transverse colon", "Duodenum", "Kidney"], "A 19-year-old man is brought to the ED after blunt upper-abdominal handlebar trauma while riding a scooter. Which organ is most commonly injured?", ["Pancreas", "Transverse colon", "Spleen", "Duodenum", "Kidney"], 2, "The spleen is the most frequently injured visceral organ in blunt abdominal trauma because of its fragile, highly vascular structure.", "Spleen is the most frequently injured visceral organ in blunt abdominal trauma.", "Blunt abdominal trauma commonly injures the spleen.", "🩸 BLUNT trauma: think SPLENIC bleed.", aid("The spleen is the most frequently injured visceral organ in blunt abdominal trauma.", "Blunt blow, splenic flow.", ["🩸", "🤕"], "Bleeding and trauma cues retain the organ risk.", "NCBI Bookshelf: Splenic Rupture", "https://www.ncbi.nlm.nih.gov/books/NBK525951/"), "https://www.ncbi.nlm.nih.gov/books/NBK525951/", "NCBI identifies the spleen as the most frequently injured visceral organ in blunt abdominal trauma."),
  r("anatomy-anatomy-all-pdf-p0817-q0033", 817, "ww The gallbladder occupies which of the following regions of the abdomen:", ["Left hypochondrium 1%", "Right hypochondrium", "Right hypochondrium and right flank 4%", "Right hypochondrium and epigastric region 17%", "Epigastric region and umbilicus 1%"], "The gallbladder occupies which region of the abdomen?", ["Left hypochondrium", "Right hypochondrium", "Right hypochondrium and right flank", "Right hypochondrium and epigastric region", "Epigastric region and umbilicus"], 1, "The gallbladder sits in the right upper quadrant, in a fossa on the visceral liver surface between segments IV and V, corresponding to the right hypochondrial region.", "Gallbladder lies in the right hypochondrium.", "Gallbladder lies in the right upper quadrant and right hypochondrium.", "➡️ RIGHT upper quadrant holds the gallbladder.", aid("The gallbladder lies in the right upper quadrant, corresponding to the right hypochondrial region in the nine-region abdominal scheme.", "Gallbladder goes right and high.", ["➡️", "⬆️"], "Rightward and upper-abdominal cues retain the location.", "NCBI Bookshelf: Gallbladder", "https://www.ncbi.nlm.nih.gov/books/NBK459288/"), "https://www.ncbi.nlm.nih.gov/books/NBK459288/", "NCBI places the gallbladder in the right upper quadrant, supporting the keyed right-hypochondrial location."),
  r("anatomy-anatomy-all-pdf-p0820-q0034", 820, "iv e) ww The flat anterior abdominal wall muscles are comprised of which of the following muscles: (x) The external and internal oblique muscles 2%", ["The external, internal and innermost oblique muscles 2%", "The external oblique, internal oblique and rectus abdominis muscles 21%", "The external oblique, internal oblique and transversus abdominis muscles", "The rectus abdominis and transversus abdominis muscles 1%"], "Which muscles form the three flat layers of the anterolateral abdominal wall?", ["External and internal oblique muscles", "External, internal, and innermost oblique muscles", "External oblique, internal oblique, and rectus abdominis muscles", "External oblique, internal oblique, and transversus abdominis muscles", "Rectus abdominis and transversus abdominis muscles"], 3, "The three flat abdominal-wall muscles are external oblique, internal oblique, and transversus abdominis. Rectus abdominis and pyramidalis are the vertical group.", "Three flat abdominal muscles: external oblique, internal oblique, transversus abdominis.", "The flat abdominal layers are external oblique, internal oblique, and transversus abdominis.", "🥞 3 FLAT layers: EO, IO, then TA.", aid("The three flat abdominal-wall muscles are external oblique, internal oblique, and transversus abdominis.", "Three flat layers: EO, IO, TA.", ["🥞", "3️⃣"], "Layer-stack and count cues retain the three muscles.", "NCBI Bookshelf: Anterolateral Abdominal Wall Muscles", "https://www.ncbi.nlm.nih.gov/books/NBK470334/"), "https://www.ncbi.nlm.nih.gov/books/NBK470334/", "NCBI explicitly identifies external oblique, internal oblique, and transversus abdominis as the three flat abdominal-wall muscles."),
  r("anatomy-anatomy-all-pdf-p0823-q0035", 823, "A 45 year old overweight patient presents to ED complaining of fever and severe right upper quadrant pain. The pain radiates to her right shoulder tip. Murphy's sign is positive and you diagnose acute cholecystitis. Which of the following nerves is responsible for the pain referred to the shoulder tip:", ["Vagus nerve 53%", "Greater thoracic splanchnic nerve 4% (x) Intercostal nerves 2%", "Lesser thoracic splanchnic nerve 1%"], "A 45-year-old patient has acute cholecystitis with right upper-quadrant pain radiating to the right shoulder tip. Which nerve is responsible for this referred shoulder pain?", ["Vagus nerve", "Phrenic nerve", "Greater thoracic splanchnic nerve", "Intercostal nerves", "Lesser thoracic splanchnic nerve"], 1, "Inflammation that irritates diaphragmatic peritoneum can refer pain to the right shoulder through the right phrenic nerve, whose roots are C3 to C5.", "Right-shoulder pain from diaphragmatic irritation travels through phrenic nerve.", "Diaphragmatic peritoneal irritation refers to shoulder through the right phrenic nerve.", "🫁 C3–5 PHRENIC refers gallbladder irritation to shoulder.", aid("Diaphragmatic peritoneal irritation from gallbladder inflammation refers pain to the right shoulder through the right phrenic nerve.", "Phrenic C3–5 points pain to the shoulder.", ["🫁", "💢", "➡️"], "Diaphragm, pain, and direction cues retain the referral pathway.", "NCBI Bookshelf: Gallbladder", "https://www.ncbi.nlm.nih.gov/books/NBK459288/"), "https://www.ncbi.nlm.nih.gov/books/NBK459288/", "NCBI identifies diaphragmatic peritoneal irritation as referring pain to the right shoulder via the right phrenic nerve."),
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0805-q0030", page: 805, expectedStem: "A75 year old man presents to ED in acute urinary retention. On examination you note the prostate feels hard and craggy. You suspect prostate cancer. Which structure is most likely affected: (x) Anterior lobe of prostate 2%", expectedOptions: ["Fibromuscular zone of prostate", "Lateral lobe of prostate", "Transitional zone of prostate"], stem: "A 75-year-old man presents to the ED with acute urinary retention. On examination, his prostate feels hard and craggy. You suspect prostate cancer. Which structure is most likely affected?", options: ["Anterior lobe of prostate", "Fibromuscular zone of prostate", "Lateral lobe of prostate", "Posterior lobe of prostate", "Transitional zone of prostate"], warning: "Source page reviewed, but modern external evidence identifies the peripheral zone rather than the exact posterior-lobe formulation; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK540987/", finding: "NCBI distinguishes historical lobes from clinical zones and reports that most carcinomas arise in the peripheral zone, not an exact posterior-lobe formulation." },
  { id: "anatomy-anatomy-all-pdf-p0813-q0032", page: 813, expectedStem: "The deep inguinal ring is located at which of the following sites:", expectedOptions: ["Immediately superficial to the femoral artery", "Superior to a point midway between the iliac crest and the pubic symphysis (x) erior to ar yay between the anterior superior iliac spine and the pubic tubercle 33%", "Just superior to the pubic tubercle"], stem: "The deep inguinal ring is located at which of the following sites?", options: ["Immediately superficial to the femoral artery", "Superior to a point midway between the iliac crest and the pubic symphysis", "Inferior to a point midway between the anterior superior iliac spine and the pubic tubercle", "Just superior to the pubic tubercle", "Superior to the mid-inguinal point"], warning: "Source page reviewed, but external evidence locates the deep ring above the midpoint of the inguinal ligament, not the mid-inguinal point; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK542321/", finding: "NCBI distinguishes the midpoint of the inguinal ligament from the mid-inguinal point and places the deep ring above the former." },
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-27.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
