import { readFile, writeFile } from "node:fs/promises";import path from "node:path";import{fileURLToPath}from"node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const bankPath=path.join(root,"client/src/lib/ocrDraftSections.ts"),snapPath=path.join(root,"docs/audit/anatomy-all-pdf-batch-32-ocr-records.json"),outPath=path.join(root,"docs/audit/applied-anatomy-batch-32.json"),warning="Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const data=[
["anatomy-anatomy-all-pdf-p0990-q0076","A 64 year old man is brought to ED with profuse haematemesis. Endoscopy shows oesophageal varices which are most likely the result of anastomosis of the left gastric vein with which of the following vessels:",["Abdominal aorta","Azygos system of veins","Inferior mesenteric vein","Superior mesenteric vein","Portal vein"],1,"Left gastric vein anastomoses with oesophageal veins draining to the azygos system.","https://pmc.ncbi.nlm.nih.gov/articles/PMC3940321/"],
["anatomy-anatomy-all-pdf-p0994-q0077","The psoas major muscle originates from which of the following:",["The T12 - L5 vertebrae","The 11th and 12th rib","The T11 - T12 vertebrae","The sacrum","The iliac crest"],0,"Psoas major has proximal attachments from T12 through L5.","https://www.ncbi.nlm.nih.gov/books/NBK535418/"],
["anatomy-anatomy-all-pdf-p0998-q0078","Which of the following actions does NOT facilitate defaecation:",["Increased intra-abdominal pressure","Contraction of rectal smooth muscle","Contraction of the puborectalis muscle","Relaxation of the internal anal sphincter","Relaxation of the external anal sphincter"],2,"Puborectalis relaxes to straighten the anorectal angle for defaecation.","https://www.ncbi.nlm.nih.gov/books/NBK539732/"],
["anatomy-anatomy-all-pdf-p1002-q0079","A 40 year old man is undergoing a vasectomy. During the procedure the various layers of the spermatic cord are separated to expose the ductus deferens. The internal spermatic fascia is derived from which of the following:",["External oblique aponeurosis","Internal oblique aponeurosis","Transversalis fascia","Internal oblique muscle","Transversus abdominis muscle"],2,"Internal spermatic fascia derives from transversalis fascia.","https://www.ncbi.nlm.nih.gov/books/NBK557763/"],
["anatomy-anatomy-all-pdf-p1006-q0080","The obturator nerve is formed from the anterior rami of:",["L2 - L4","L1 - L2","L1 - L4","L2 - L3","L3 - L4"],0,"Obturator nerve arises from anterior divisions of L2–L4.","https://www.ncbi.nlm.nih.gov/books/NBK545137/"],
["anatomy-anatomy-all-pdf-p1010-q0081","Which of the following best describes the relationship of the duodenum to the pancreas:",["The first part of the duodenum lies superior to the tail of the pancreas.","The second part of the duodenum lies medial to the head of the pancreas.","The third part of the duodenum lies inferior to the pancreas.","The fourth part of the duodenum lies inferior to the head of the pancreas.","The head of the pancreas lies posterior to the second part of the duodenum."],2,"The horizontal third duodenal part lies inferior to the pancreatic region.","https://www.ncbi.nlm.nih.gov/books/NBK482390/"],
["anatomy-anatomy-all-pdf-p1014-q0082","A 41 year old man presents to ED with a painful, infected abscess on the posterior aspect of the scrotum. Which of the following lymph nodes is most likely to be affected first:",["Internal iliac nodes","External iliac nodes","Superficial inguinal nodes","Deep inguinal nodes","Para-aortic nodes"],2,"Scrotal wall drains to superficial inguinal nodes.","https://www.ncbi.nlm.nih.gov/books/NBK549893/"],
["anatomy-anatomy-all-pdf-p1017-q0083","The superior pole of the left kidney reaches as high as which of the following:",["Rib 8","Rib 9","Rib 10","Rib 11","Rib 12"],3,"The left renal superior margin is near the eleventh rib.","https://www.ncbi.nlm.nih.gov/books/NBK459339/"],
["anatomy-anatomy-all-pdf-p1023-q0084","The stomach lies anterior to all of the following structures EXCEPT for the:",["Pancreas","Transverse mesocolon","Spleen","Left lobe of the liver","Left colic flexure"],3,"The left hepatic lobe lies anterior to the stomach.","https://www.ncbi.nlm.nih.gov/books/NBK482334/"],
["anatomy-anatomy-all-pdf-p1028-q0085","Which of the following parts of the male urethra passes through the urogenital diaphragm:",["Preprostatic urethra","Prostatic urethra","Membranous urethra","Spongy urethra","Urethral crest"],2,"Membranous urethra traverses the deep perineal space and perineal membrane.","https://www.ncbi.nlm.nih.gov/books/NBK542238/"]];
const src=await readFile(bankPath,"utf8"),prefix="export const ocrDraftQuestions: OcrDraftQuestion[] = ",s=src.indexOf(prefix)+prefix.length,e=src.indexOf("];",s),bank=JSON.parse(src.slice(s,e+1)),snap=JSON.parse(await readFile(snapPath,"utf8")).records,by=new Map(bank.map(x=>[x.id,x])),before=[];
for(const[id,stem,options,key,fact,url]of data){const old=snap.find(x=>x.id===id),q=by.get(id);if(!old||!q||q.sourcePage!==old.sourcePage||q.stem!==old.stem||JSON.stringify(q.options)!==JSON.stringify(old.options))throw Error(`Immutable drift check failed: ${id}`);const prior={stem:q.stem,options:q.options,correctOption:q.correctOption};Object.assign(q,{stem,options,correctOption:key,explanation:fact,learningNote:fact,highYieldNote:fact,mnemonic:fact,memoryAid:{coreFact:fact,mnemonic:fact,cueLabel:"Source-confirmed anatomy fact",sourceLabel:"Batch 32 external anatomy reference",sourceUrl:url,emojiCues:["📍"]},status:"ocr_draft",askable:true,needsImage:false,warnings:[warning]});delete q.approved;before.push({id,sourcePage:q.sourcePage,before:prior,after:{stem:q.stem,options:q.options,correctOption:q.correctOption,status:q.status,askable:q.askable},evidence:{externalSource:url,externalFinding:fact}})}
await writeFile(bankPath,src.slice(0,s)+JSON.stringify(bank)+src.slice(e+1));await writeFile(outPath,JSON.stringify({generatedAt:new Date().toISOString(),applied:before,restricted:[],automaticApproval:false,mockEligibility:"No restored OCR draft is mock eligible."},null,2)+"\n");console.log(`Restored ${before.length} Batch 32 OCR drafts without approval.`);
