import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts");
const auditDir = path.join(root, "docs", "audit");
const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const aid = (coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl) => ({ coreFact, mnemonic, emojiCues, cueLabel, sourceLabel, sourceUrl });
const r = (id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding) => ({ id, page, expectedStem, expectedOptions, stem, options, correctOption, explanation, learningNote, highYieldNote, mnemonic, memoryAid, sourceUrl, finding });

const restorations = [
  r("anatomy-anatomy-all-pdf-p0696-q0004", 696, "Which of the following best describes the relationship of the prostate gland and rectum: (x) e prostate gland lies superior to the rectum. 5%", ["The prostate gland lies inferior to the rectum.", "The prostate gland lies posterior to the rectum.", "The prostate gland is not in relation to the rectum."], "Which of the following best describes the relationship of the prostate gland and rectum?", ["The prostate gland lies superior to the rectum.", "The prostate gland lies inferior to the rectum.", "The prostate gland lies anterior to the rectum.", "The prostate gland lies posterior to the rectum.", "The prostate gland is not in relation to the rectum."], 2, "The prostate lies anterior to the rectum, separated from it by Denonvilliers fascia. This posterior rectal relation permits digital rectal examination of the prostate.", "The prostate is anterior to the rectum.", "Prostate lies anterior to the rectum.", "⬅️ PROSTATE is in FRONT of the rectum.", aid("The prostate lies anterior to the rectum and is separated from it by Denonvilliers fascia.", "Prostate in front of rectum.", ["⬅️", "♂️"], "Direction and male-pelvis cues retain the relation.", "NCBI Bookshelf: Prostate", "https://www.ncbi.nlm.nih.gov/books/NBK540987/"), "https://www.ncbi.nlm.nih.gov/books/NBK540987/", "NCBI describes the rectum as a posterior relation of the prostate, separated by Denonvilliers fascia."),
  r("anatomy-anatomy-all-pdf-p0700-q0005", 700, "Ad The parasympathetic supply to the rectum is from which of the following:", ["Superior hypogastric plexus 2%", "Pelvic splanchnic nerves", "Lumbar splanchnic nerves 13% Cee rowvemne", "Sacral splanchnic nerves 19%"], "The parasympathetic supply to the rectum is from which nerves?", ["Superior hypogastric plexus", "Pelvic splanchnic nerves", "Lumbar splanchnic nerves", "Inferior hypogastric nerves", "Sacral splanchnic nerves"], 1, "Pelvic splanchnic nerves arise from S2 to S4 and provide parasympathetic innervation to pelvic viscera, including the rectum.", "Pelvic splanchnic nerves (S2–S4) provide rectal parasympathetic supply.", "Rectal parasympathetic supply is S2–S4 pelvic splanchnic nerves.", "⚡ RECTUM relaxes with S2–S4 pelvic splanch-nics.", aid("Pelvic splanchnic nerves from S2–S4 provide parasympathetic supply to the rectum.", "Rectum: S2–S4 pelvic splanchnics.", ["⚡", "2️⃣", "4️⃣"], "Nerve and root-number cues retain rectal parasympathetic supply.", "NCBI Bookshelf: Splanchnic Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK560504/"), "https://www.ncbi.nlm.nih.gov/books/NBK560504/", "NCBI identifies pelvic splanchnic nerves as parasympathetic nerves supplying the rectum and other pelvic viscera."),
  r("anatomy-anatomy-all-pdf-p0710-q0007", 710, "we Regarding the rectum, which of the following statements is CORRECT:", ["The rectum is continuous with the rectosigmoid junction at the level of vertebra S2. (x) The rectum is connected to the posterior abdominal wall by the sigmoid mesocolon. 5%", "The rectum is the most posterior viscera in the pelvic cavity.", "The rectum lies immediately posterior to the bladder in women. 4%", "The rectum is an intraperitoneal structure. 55%"], "Regarding the rectum, which statement is correct?", ["The rectum is continuous with the rectosigmoid junction at the level of vertebra S2.", "The rectum is connected to the posterior abdominal wall by the sigmoid mesocolon.", "The rectum is the most posterior viscera in the pelvic cavity.", "The rectum lies immediately posterior to the bladder in women.", "The rectum is an intraperitoneal structure."], 2, "The rectum is the most posterior visceral organ in the pelvic cavity. It begins at S3 rather than S2, and its peritoneal covering varies by level.", "Rectum is the most posterior visceral organ in the pelvic cavity.", "Rectum is the pelvic cavity’s most posterior viscus.", "⬅️ RECTUM is the BACK-MOST pelvic viscus.", aid("The rectum is the most posterior visceral organ in the pelvic cavity.", "Rectum: back-most pelvic viscus.", ["⬅️", "📍"], "Posterior-direction and location cues retain the pelvic relation.", "NCBI Bookshelf: Rectum", "https://www.ncbi.nlm.nih.gov/books/NBK537245/"), "https://www.ncbi.nlm.nih.gov/books/NBK537245/", "NCBI explicitly identifies the rectum as the most posterior visceral organ in the pelvic cavity."),
  r("anatomy-anatomy-all-pdf-p0715-q0008", 715, "The uterine visceral afferent fibres usually follow sympathetic efferents to which of the following spinal cord segments:", ["m10-11", "T9-T12 Be", "Li-L3 19%", "L2-L4 20%", "T5-19 we"], "Uterine visceral afferent fibres usually follow sympathetic efferents to which spinal cord segments?", ["T10–L1", "T9–T12", "L1–L3", "L2–L4", "T5–T9"], 0, "Visceral pain afferents from the uterus, adnexa, and cervix travel with sympathetic pathways to thoracolumbar segments, including T10 to L1.", "Uterine visceral afferents commonly refer to T10–L1.", "Uterine visceral pain travels with sympathetic fibres to T10–L1.", "🔟➖1️⃣ UTERUS refers pain to T10–L1.", aid("Uterine visceral afferents accompanying sympathetic pathways reach T10–L1 spinal segments.", "Uterus: T10 to L1.", ["🔟", "1️⃣", "♀️"], "Root-number and female-organ cues retain the afferent level.", "PMC: Neurobiological Mechanisms of Pelvic Pain", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4119661/"), "https://pmc.ncbi.nlm.nih.gov/articles/PMC4119661/", "A peer-reviewed review identifies T10-L1 visceral pain afferents for the uterus, adnexa, and cervix."),
  r("anatomy-anatomy-all-pdf-p0719-q0009", 719, "The posterior wall of the inguinal canal is formed primarily by which of the following structures:", ["Transversus abdominis muscle", "External oblique aponeurosis 8%", "Transversalis fascia 7A%", "External oblique muscle 2%", "Internal oblique muscle 6%"], "The posterior wall of the inguinal canal is formed primarily by which structure?", ["Transversus abdominis muscle", "External oblique aponeurosis", "Transversalis fascia", "External oblique muscle", "Internal oblique muscle"], 2, "Transversalis fascia forms the posterior wall of the inguinal canal. The conjoint tendon reinforces the medial part of this wall.", "Transversalis fascia forms the posterior inguinal-canal wall.", "Posterior inguinal canal = transversalis fascia, reinforced medially by conjoint tendon.", "🧱 POSTERIOR canal wall = TRANSVERSALIS fascia.", aid("Transversalis fascia forms the posterior wall of the inguinal canal, with medial conjoint-tendon reinforcement.", "Posterior canal: transversalis fascia.", ["🧱", "↩️"], "Wall and posterior-direction cues retain the canal boundary.", "NCBI Bookshelf: Inguinal Canal", "https://www.ncbi.nlm.nih.gov/books/NBK470204/"), "https://www.ncbi.nlm.nih.gov/books/NBK470204/", "NCBI identifies the posterior inguinal-canal wall as transversalis fascia with medial conjoint-tendon reinforcement.")
];

const restrictions = [
  { id: "anatomy-anatomy-all-pdf-p0692-q0003", page: 692, expectedStem: "The arterial supply to the jejunum and ileum is derived predominantly from which of the following: Coeliac trunk Superior mesenteric artery Inferior mesenteric artery Renal artery Lumbar artery a Py v2 OX OO —CSsSC“‘(CS", expectedOptions: [], stem: "The arterial supply to the jejunum and ileum is derived predominantly from which artery?", options: ["Coeliac trunk", "Superior mesenteric artery", "Inferior mesenteric artery", "Renal artery", "Lumbar artery"], warning: "Source page reviewed, but no marked answer is displayed; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532972/", finding: "The source screenshot shows no answer mark; no source key is inferred even though external anatomy describes superior-mesenteric supply to the jejunum and ileum." },
  { id: "anatomy-anatomy-all-pdf-p0705-q0006", page: 705, expectedStem: "The ureters enter the bladder through which of the following:", expectedOptions: ["Superior surface", "Inferolateral surface", "Apex", "Inferior base"], stem: "The ureters enter the bladder through which part?", options: ["Superior surface", "Inferolateral surface", "Apex", "Superior base", "Inferior base"], warning: "Source page reviewed, but the exact answer label “superior base” is not sufficiently corroborated by the evidence reviewed.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK531465/", finding: "NCBI describes the bladder base as posteroinferior and the ureterovesical junction, but does not validate the source option wording “superior base.”" },
  { id: "anatomy-anatomy-all-pdf-p0723-q0010", page: 723, expectedStem: "ww The arterial supply to the pancreas is mainly derived from which of the following: oO", expectedOptions: ["Splenic artery", "Hepatic artery 4%", "Renal artery 1%", "Inferior mesenteric artery 52%"], stem: "The arterial supply to the pancreas is mainly derived from which artery?", options: ["Gastric artery", "Splenic artery", "Hepatic artery", "Renal artery", "Inferior mesenteric artery"], warning: "Source page reviewed, but external evidence describes multi-arterial pancreatic supply and does not sufficiently corroborate the isolated source formulation.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532912/", finding: "NCBI identifies pancreatic branches from the splenic artery, superior mesenteric artery, and common hepatic artery; the exact isolated main-source formulation is not restored." },
  { id: "anatomy-anatomy-all-pdf-p0731-q0012", page: 731, expectedStem: "w The kidneys are related posteriorly to all of the following structures EXCEPT for the:", expectedOptions: ["Diaphragm 10%", "Psoas major muscle 4%", "Quadratus lumborum muscle 4%", "lliacus muscle"], stem: "The kidneys are related posteriorly to all of the following structures except which?", options: ["Diaphragm", "Psoas major muscle", "Quadratus lumborum muscle", "Transversus abdominis muscle", "Iliacus muscle"], warning: "Source page reviewed, but the full exact all-except relation is not sufficiently corroborated by the evidence reviewed.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482385/", finding: "NCBI corroborates several posterior kidney relations but does not directly establish the source’s full all-except formulation with iliacus." },
  { id: "anatomy-anatomy-all-pdf-p0737-q0013", page: 737, expectedStem: "Which of the following lies immediately medial to the second part of the duodenum:", expectedOptions: ["Transverse colon", "Spleen (x) Right kidney 3%", "Stomach"], stem: "Which structure lies immediately medial to the second part of the duodenum?", options: ["Transverse colon", "Spleen", "Right kidney", "Head of the pancreas", "Stomach"], warning: "Source page reviewed, but no marked answer is displayed; no correct option is inferred.", sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK532912/", finding: "The source screenshot shows no answer mark; the head of the pancreas is not restored as a key despite external anatomic support." }
];

function parse(source) {
  const prefix = "export const ocrDraftQuestions: OcrDraftQuestion[] = ";
  const start = source.indexOf(prefix);
  const arrayStart = start + prefix.length;
  const end = source.indexOf("];", arrayStart);
  if (start < 0 || end < 0) throw new Error("OCR draft export not found");
  return { arrayStart, end, drafts: JSON.parse(source.slice(arrayStart, end + 1)) };
}

function guard(draft, item) {
  if (!draft || draft.sourcePage !== item.page) throw new Error(`Source-page drift for ${item.id}`);
  if (draft.stem !== item.expectedStem || JSON.stringify(draft.options) !== JSON.stringify(item.expectedOptions)) throw new Error(`OCR drift for ${item.id}; refusing update.`);
}

function snapshot(draft) {
  return { stem: draft.stem, options: draft.options, correctOption: draft.correctOption, status: draft.status, askable: draft.askable, needsImage: draft.needsImage, warnings: draft.warnings ?? [] };
}

const source = await readFile(bankPath, "utf8");
const parsed = parse(source);
const byId = new Map(parsed.drafts.map((draft) => [draft.id, draft]));
const applied = [];

for (const item of restorations) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: item.correctOption, explanation: item.explanation, learningNote: item.learningNote, highYieldNote: item.highYieldNote, mnemonic: item.mnemonic, memoryAid: item.memoryAid, status: "ocr_draft", askable: true, needsImage: false, warnings: [reviewedWarning] });
  applied.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

const restricted = [];
for (const item of restrictions) {
  const draft = byId.get(item.id);
  guard(draft, item);
  const before = snapshot(draft);
  Object.assign(draft, { stem: item.stem, options: item.options, correctOption: null, explanation: item.finding, learningNote: "", highYieldNote: "", mnemonic: "", status: "needs_review", askable: false, needsImage: false, warnings: [item.warning] });
  delete draft.memoryAid;
  restricted.push({ id: item.id, sourcePage: item.page, before, after: snapshot(draft), evidence: { externalSource: item.sourceUrl, externalFinding: item.finding } });
}

await writeFile(bankPath, `${source.slice(0, parsed.arrayStart)}${JSON.stringify(parsed.drafts)}${source.slice(parsed.end + 1)}`);
await mkdir(auditDir, { recursive: true });
await writeFile(path.join(auditDir, "applied-anatomy-batch-25.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), applied, restricted, automaticApproval: false, mockEligibility: "No restored OCR draft is mock eligible." }, null, 2)}\n`);
console.log(JSON.stringify({ restored: applied.map((row) => row.id), restricted: restricted.map((row) => row.id), automaticApproval: false }, null, 2));
