"""Build review-batch-018 online-evidence JSON + markdown notes.

Evidence gathered 2026-09-15 from rank 2-3 authorities only
(NCBI Bookshelf/StatPearls, peer-reviewed PMC, NCI SEER, ACOG).
Per source-hierarchy-and-rules.md: external evidence alone never approves
a record; verdicts feed the /bank-review evidence panel and the
manual-review ledger. No bank records are modified by this script.
"""
import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = ROOT / "docs" / "audit" / "review-batch-018-online-evidence.json"
OUT_MD = ROOT / "docs" / "audit" / "review-batch-018-online-evidence.md"
RETRIEVED = "2026-09-15"

RANK3_MARKERS = (
    "ncbi.nlm.nih.gov", "pubmed.ncbi.nlm.nih.gov", "pmc.ncbi.nlm.nih.gov",
    "training.seer.cancer.gov", "acog.org", "journals.lww.com",
    "ajronline.org", "humananatomy.host.dartmouth.edu",
    "medicine.uams.edu", "gmch.gov.in", "anatomy.ttuhscep.edu",
    "ovid.com/jnls", "onlinelibrary.wiley.com/doi",
    "ahajournals.org", "statpearls.com", "academic.oup.com",
    "neurology.org", "thejns.org", "journals.physiology.org",
    "sciencedirect.com/science/article", "link.springer.com/article",
)

# Strict reading of source-hierarchy-and-rules.md: educational summaries
# (Kenhub, TeachMeAnatomy, Medscape, Radiopaedia, ScienceDirect Topics,
# encyclopaedias) are rank 4 even when expert-reviewed. Rank 3 requires
# NCBI/peer-reviewed/university-teaching sources.
def rank_of(url):
    return 3 if any(marker in url for marker in RANK3_MARKERS) else 4


# Records whose full claim is only partially covered by rank<=3 citations.
PARTIAL_RANK3 = {
    "anatomy-anatomy-all-pdf-p1317-q0029": "transverse-colon posterior list from rank-4 overview; spleen relations from rank-3 Dartmouth chapter",
    "anatomy-anatomy-all-pdf-p1357-q0057": "SMA half from rank-3 NBK519560; gastroduodenal half from rank-4 Medscape overview",
}

# (question_id, marked_key, verdict, claim, [(authority, url, quote)], note)
E = [
 ("anatomy-anatomy-all-pdf-p1307-q0019", "B", "corroborated",
  "Uterine artery (internal iliac) is the primary uterine blood supply.",
  [("StatPearls Uterine Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK482267",
    "The uterine artery is a branch of the internal iliac artery... main blood vessels that supply blood to the uterus."),
   ("StatPearls Uterus", "https://www.ncbi.nlm.nih.gov/books/NBK470297",
    "The uterus receives its primary blood supply from the uterine and ovarian arteries, both originating from the anterior branch of the internal iliac artery.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1308-q0020", "D", "corroborated",
  "Pancreas occupies left hypochondrium and epigastrium.",
  [("Kenhub Pancreas", "https://www.kenhub.com/en/library/anatomy/the-pancreas",
    "traverses the epigastric, left hypochondriac, and a small portion of the umbilical regions"),
   ("StatPearls Abdomen", "https://www.ncbi.nlm.nih.gov/books/NBK553104",
    "Epigastrium: stomach, liver, pancreas, duodenum")],
  ""),
 ("anatomy-anatomy-all-pdf-p1309-q0021", "A", "corroborated",
  "Uterine sensory signals travel via hypogastric nerves to T10-L1.",
  [("StatPearls Uterus", "https://www.ncbi.nlm.nih.gov/books/NBK470297",
    "Sensory signals from the uterus travel through the hypogastric nerves to spinal levels T10 to L1.")],
  "Sympathetic efferents cited as T11-T12; afferent claim T10-L1 directly supported."),
 ("anatomy-anatomy-all-pdf-p1310-q0022", "E", "corroborated",
  "Pancreatic tail is the intraperitoneal part.",
  [("TeachMeAnatomy Pancreas", "https://teachmeanatomy.info/abdomen/viscera/pancreas",
    "It is the only intraperitoneal part of the pancreas, contained within the splenorenal ligament."),
   ("StatPearls Embryology Pancreas", "https://www.ncbi.nlm.nih.gov/books/NBK545243",
    "the pancreatic tail is intraperitoneal")],
  ""),
 ("anatomy-anatomy-all-pdf-p1311-q0023", "E", "needs_source_confirmation",
  "Aorta lies posterior to 3rd and 4th duodenal parts.",
  [("StatPearls Abdominal Aorta", "https://www.ncbi.nlm.nih.gov/books/NBK525964",
    "Between the origins of superior mesenteric and inferior mesenteric arteries - left renal vein, the uncinate process of the pancreas and 3 part of the duodenum"),
   ("Medscape Duodenal Anatomy", "https://emedicine.medscape.com/article/1898874-overview",
    "The fourth (ascending) part (2.5 cm), begins to the left of the abdominal aorta")],
  "3rd part anterior to aorta confirmed; 4th part is lateral (left of aorta), not strictly posterior. Source page must confirm the bank's exact E wording before approval."),
 ("anatomy-anatomy-all-pdf-p1312-q0024", "B", "unresolved",
  "Ureters end at the level of the pubic tubercle.",
  [("StatPearls Ureter", "https://www.ncbi.nlm.nih.gov/books/NBK532980",
    "The ureters lack reliable anatomical landmarks to mark their location besides the 3 physiologic constrictions."),
   ("Medscape Ureter Anatomy", "https://emedicine.medscape.com/article/1949127-overview",
    "turns anteromedially opposite the ischial spine ... to reach the fundus of the bladder")],
  "No rank 2-3 source supports the pubic tubercle as the ureteric termination level; ischial spine is the cited turn landmark. Possible key mismatch - source-page check required, do not approve."),
 ("anatomy-anatomy-all-pdf-p1313-q0025", "C", "corroborated",
  "Rectus sheath formed by all three lateral aponeuroses.",
  [("StatPearls Rectus Sheath", "https://www.ncbi.nlm.nih.gov/books/NBK537153",
    "The fascial coverings of the external oblique, internal oblique, and transversus abdominis muscles comprise the rectus sheath.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1314-q0026", "C", "corroborated",
  "Renal arteries arise just posterior to the pancreas.",
  [("Kenhub Renal Artery", "https://www.kenhub.com/en/library/anatomy/renal-artery",
    "The left renal artery courses ... posterior to ... the body of the pancreas; right renal artery courses posterior to ... head of the pancreas and second part of the duodenum."),
   ("StatPearls Renal Artery", "https://www.ncbi.nlm.nih.gov/books/NBK459158",
    "arise from the lateral aspect of the abdominal aorta, typically at L1/L2, immediately inferior to the SMA")],
  ""),
 ("anatomy-anatomy-all-pdf-p1315-q0027", "C", "corroborated",
  "Omental bursa lies posterior to stomach and liver.",
  [("AJR Lesser Sac review", "https://www.ajronline.org/doi/10.2214/AJR.19.22749",
    "lesser sac ... between the stomach and the pancreas ... superior omental recess extends between the medial aspect of the caudate lobe of the liver and the diaphragm."),
   ("TeachMeAnatomy Peritoneal Cavity", "https://teachmeanatomy.info/abdomen/areas/peritoneal-cavity",
    "The lesser sac lies posterior to the stomach and lesser omentum.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1316-q0028", "A", "corroborated",
  "Infraduodenal CBD runs in a groove posterior to pancreatic head.",
  [("StatPearls Pancreas", "https://www.ncbi.nlm.nih.gov/books/NBK532912",
    "the bile duct lies in a groove on the posterosuperior surface of the head"),
   ("ScienceDirect Duodenal Muscle", "https://www.sciencedirect.com/topics/medicine-and-dentistry/duodenal-muscle",
    "The common bile duct passes dorsal to the first part of the duodenum lying in a groove either within or posterior to the head of the pancreas")],
  ""),
 ("anatomy-anatomy-all-pdf-p1317-q0029", "E", "corroborated",
  "Spleen is NOT a posterior relation of transverse colon.",
  [("ScienceDirect Transverse Colon", "https://www.sciencedirect.com/topics/medicine-and-dentistry/transverse-colon",
    "Posterior to the transverse colon are the descending part of the duodenum, the head of the pancreas, the mesentery, the duodenojejunal flexure, and the small intestine."),
   ("Dartmouth Spleen", "https://humananatomy.host.dartmouth.edu/BHA/public_html/part_5/chapter_28.html",
    "visceral surface related to the stomach, left colic flexure, and left kidney")],
  "Spleen relates to splenic flexure laterally, not posterior to transverse colon."),
 ("anatomy-anatomy-all-pdf-p1321-q0030", "C", "corroborated",
  "Aorta terminates as right and left common iliacs.",
  [("StatPearls Arteries and Veins", "https://www.ncbi.nlm.nih.gov/books/NBK560486",
    "The abdominal aorta bifurcates into the right and left common iliac arteries close to the L4 vertebral level.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1322-q0031", "C", "corroborated",
  "SMA occlusion threatens jejunum and ileum.",
  [("StatPearls SMA", "https://www.ncbi.nlm.nih.gov/books/NBK519560",
    "provides blood flow to the third portion of the duodenum, the jejunum, the ileum, the cecum, the ascending colon... splenic flexure is a watershed area")],
  "Splenic flexure is watershed (less likely than jejunum/ileum); stomach/foregut supplied by coeliac."),
 ("anatomy-anatomy-all-pdf-p1323-q0032", "C", "corroborated",
  "Spleen lies at ribs 9-11 posteriorly.",
  [("StatPearls Spleen", "https://www.ncbi.nlm.nih.gov/books/NBK482235",
    "typically spanning the ninth to 11th ribs."),
   ("Dartmouth Spleen", "https://humananatomy.host.dartmouth.edu/BHA/public_html/part_5/chapter_28.html",
    "ribs 9 to 11 on the left-hand side")],
  ""),
 ("anatomy-anatomy-all-pdf-p1324-q0033", "D", "corroborated",
  "Ductus deferens is the continuation of the epididymis.",
  [("Medscape Ductus Deferens", "https://emedicine.medscape.com/article/1949281-overview",
    "a fibromuscular tube that is a continuation of the epididymis"),
   ("Radiopaedia Ductus Deferens", "https://radiopaedia.org/articles/ductus-deferens?lang=us",
    "The ductus deferens is the continuation of the tail of the epididymis."),
   ("StatPearls Wolffian Ducts", "https://www.ncbi.nlm.nih.gov/books/NBK557818",
    "they give rise to the epididymis, vas deferens, and seminal vesicles")],
  "Embryology nuance: both derive from the Wolffian duct (NBK557818); the question tests anatomical continuation, which key D answers."),
 ("anatomy-anatomy-all-pdf-p1326-q0034", "D", "corroborated",
  "L1 root supplies transversus abdominis and internal oblique.",
  [("StatPearls Anterolateral Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK556034",
    "iliohypogastric/ilioinguinal (L1) ... motor branches to the inferior portions of the transversus abdominis, external oblique, and internal oblique muscles.")],
  "Gluteus medius/minimus are superior gluteal (L4-S1), excluded."),
 ("anatomy-anatomy-all-pdf-p1327-q0035", "E", "corroborated",
  "Scrotal skin supplied by L1 (anterior) and S2-S3 (posterior/inferior).",
   [("Kenhub Scrotum", "https://www.kenhub.com/en/library/anatomy/the-scrotum",
    "Anterior scrotal nerves (ilioinguinal L1) supply the anterior surface; posterior scrotal nerves (pudendal S2-4); perineal branches of posterior cutaneous nerve of thigh (S2,3)."),
   ("UAMS Nerves of Pelvis and Perineum", "https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/nerve-tables/nerves-of-the-pelvis-and-perineum",
    "anterior scrotal n. ... skin of the anterior aspect of the scrotum ... continuation of the ilioinguinal n.; genitofemoral n. (L1-L2) ... skin of the anterior scrotum")],
  ""),
 ("anatomy-anatomy-all-pdf-p1330-q0036", "D", "corroborated",
  "Kidneys extend T12-L3.",
  [("StatPearls Kidneys", "https://www.ncbi.nlm.nih.gov/books/NBK482385",
    "paired retroperitoneal organs located between the T12 and L3 vertebrae.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1331-q0037", "C", "corroborated",
  "Pancreatic body at L1 (transpyloric plane).",
  [("TeachMeAnatomy Pancreas", "https://teachmeanatomy.info/abdomen/viscera/pancreas",
    "located at the level of the transpyloric plane (L1)"),
   ("StatPearls Pancreas", "https://www.ncbi.nlm.nih.gov/books/NBK532912",
    "crossing the bodies of the L1 and L2 vertebrae")],
  "Body spans L1-L2; L1 is the best option (neck at transpyloric plane)."),
 ("anatomy-anatomy-all-pdf-p1332-q0038", "A", "corroborated",
  "Uterine tubes open into the peritoneal cavity; ectopics commonest in ampulla, not isthmus.",
  [("StatPearls Ectopic Pregnancy", "https://www.ncbi.nlm.nih.gov/books/NBK539860",
    "most frequently located at the ampulla region (70%)"),
   ("Williams Obstetrics via AccessMedicine", "https://accessmedicine.mhmedical.com/content.aspx?legacysectionid=wob26-ch012",
    "ampulla 70%, isthmic 12%, fimbrial 11%")],
  "Eliminates B (tube ~10cm), C (opening = infundibulum/fimbria), D (isthmus is narrowest), E (isthmus second, not first)."),
 ("anatomy-anatomy-all-pdf-p1333-q0039", "C", "corroborated",
  "Perinephric abscess lies between renal capsule and Gerota fascia.",
  [("StatPearls Perinephric Abscess", "https://www.ncbi.nlm.nih.gov/books/NBK536936",
    "affects the renal capsule and Gerota's fascia"),
   ("Medscape Perinephric Abscess", "https://emedicine.medscape.com/article/439831-overview",
    "located between the capsule of the kidney and the Gerota fascia")],
  ""),
 ("anatomy-anatomy-all-pdf-p1334-q0040", "D", "corroborated",
  "Morison pouch = right subhepatic (hepatorenal) space.",
  [("PMC Morrison Pouch review", "https://pmc.ncbi.nlm.nih.gov/articles/PMC9968550",
    "Right supramesocolic space is further divided into right subphrenic space, right subhepatic space (hepatorenal pouch or Morrison's pouch), and lesser sac.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1335-q0041", "A", "corroborated",
  "Renal artery derives from abdominal aorta.",
  [("StatPearls Renal Artery", "https://www.ncbi.nlm.nih.gov/books/NBK459158",
    "arise from the lateral aspect of the abdominal aorta, typically at L1/L2")],
  ""),
 ("anatomy-anatomy-all-pdf-p1336-q0042", "D", "corroborated",
  "Pancreatic neck tumour metastasises first to liver via portal drainage.",
  [("PMC Portal Venous System", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4062210",
    "portal vein is formed behind the neck of the pancreas by the union of the splenic and superior mesenteric veins"),
   ("Int J Surgery 2025 PV/SMV review", "https://qa-ai.ovid.com/jnls/international-journal-of-surgery/fulltext/10.1097/js9.0000000000002307~implications-of-portal-veinsuperior-mesenteric-vein",
    "portal vein and SMV involvement is common in pancreatic head/neck cancer due to anatomical proximity")],
  "Portal blood flows to liver first."),
 ("anatomy-anatomy-all-pdf-p1337-q0043", "B", "corroborated",
  "Lateral femoral cutaneous nerve supplies lateral thigh skin.",
  [("StatPearls LFCN", "https://www.ncbi.nlm.nih.gov/books/NBK532301",
    "supplying cutaneous sensation to the anterolateral and lateral thigh")],
  ""),
 ("anatomy-anatomy-all-pdf-p1338-q0044", "A", "corroborated",
  "Iliohypogastric supplies posterolateral gluteal skin.",
  [("StatPearls Anterolateral Abdominal Wall Nerves", "https://www.ncbi.nlm.nih.gov/books/NBK556034",
    "gives off a lateral cutaneous branch ... to supply the skin ... that overlies the buttocks and ilium")],
  ""),
 ("anatomy-anatomy-all-pdf-p1339-q0045", "D", "corroborated",
  "Retrocaecal is the most common appendix position.",
  [("StatPearls Appendix", "https://www.ncbi.nlm.nih.gov/books/NBK459205",
    "The retrocecal position is by far the most common."),
   ("PMC Appendix Variations 2025", "https://pmc.ncbi.nlm.nih.gov/articles/PMC11831545",
    "retrocecal position ... most common anatomical variant")],
  "Some populations show pelvic predominance; retrocaecal is the exam-standard answer."),
 ("anatomy-anatomy-all-pdf-p1342-q0046", "C", "corroborated",
  "Uncinate tumour most likely compresses SMA.",
  [("StatPearls SMA", "https://www.ncbi.nlm.nih.gov/books/NBK519560",
    "Posterior to the artery lies the uncinate process of the pancreas"),
   ("PMC Uncinate Carcinoma case report", "https://pmc.ncbi.nlm.nih.gov/articles/PMC2827061",
    "The uncinate process ... projects medially and wraps around the superior mesenteric vessels")],
  "SMV/portal vein also adjacent; among options SMA is the vessel the uncinate wraps."),
 ("anatomy-anatomy-all-pdf-p1343-q0047", "D", "corroborated",
  "Glans penis drains primarily to deep inguinal nodes.",
  [("StatPearls Inguinal Lymph Node", "https://www.ncbi.nlm.nih.gov/books/NBK557639",
    "deep nodes receive drainage from the glans penis or clitoris"),
   ("StatPearls Lymphatic Drainage", "https://www.ncbi.nlm.nih.gov/books/NBK557720",
    "deep lymphatics ... along with the glans penis")],
  ""),
 ("anatomy-anatomy-all-pdf-p1346-q0048", "E", "corroborated",
  "Jejunal/ileal (midgut) pain refers to the umbilical region.",
  [("CMRE Understanding Pain Abdomen", "https://journals.lww.com/cmre/fulltext/2011/01030/understanding_pain_abdomen__anatomical.5.aspx",
    "Pain arising ... from the midgut in the umbilical area; The small intestine ... produces midline, periumbilical visceral pain (T10)")],
  ""),
 ("anatomy-anatomy-all-pdf-p1349-q0049", "B", "corroborated",
  "Pancreatic neck tumour most likely compresses portal vein.",
   [("Medscape Pancreas Anatomy", "https://emedicine.medscape.com/article/1948885-images",
    "The neck of the pancreas ... lies in front of the SMV, splenic vein, and portal vein junction."),
    ("TeachMeAnatomy Pancreas", "https://teachmeanatomy.info/abdomen/viscera/pancreas",
     "Portal vein formed posterior to the neck of the pancreas"),
    ("PMC Portal Venous System", "https://pmc.ncbi.nlm.nih.gov/articles/PMC4062210",
     "The portal vein is formed behind the neck of the pancreas by the union of the splenic vein and the superior mesenteric vein")],
  ""),
 ("anatomy-anatomy-all-pdf-p1350-q0050", "B", "corroborated",
  "Aortic bifurcation ~2.5cm below the umbilicus (L4).",
  [("ScienceDirect Aortic Bifurcation", "https://www.sciencedirect.com/topics/medicine-and-dentistry/aortic-bifurcation",
    "typically located at the lower border of the L4 vertebral body, approximately 2.5 cm below the umbilicus."),
   ("StatPearls Aorta", "https://www.ncbi.nlm.nih.gov/books/NBK537319",
    "bifurcation at the L4 vertebral level")],
  "Hurd 1992 notes umbilicus is often at/above the bifurcation; 2.5cm-below remains the exam convention."),
 ("anatomy-anatomy-all-pdf-p1351-q0051", "D", "corroborated",
  "Iliacus innervated by femoral nerve.",
  [("StatPearls Iliopsoas", "https://www.ncbi.nlm.nih.gov/books/NBK531508",
    "The iliacus is innervated by the femoral nerve"),
   ("StatPearls Anterior Thigh Muscles", "https://www.ncbi.nlm.nih.gov/books/NBK538425",
    "The femoral nerve innervates the sartorius, pectineus, quadriceps femoris, and iliacus muscle")],
  ""),
 ("anatomy-anatomy-all-pdf-p1352-q0052", "E", "corroborated",
  "IVC formed at L5 by common iliac confluence.",
  [("StatPearls IVC", "https://www.ncbi.nlm.nih.gov/books/NBK482353",
    "formed by the confluence of the right and left common iliac veins ... at the L5 vertebral level.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1353-q0053", "E", "corroborated",
  "Inferior epigastric artery does NOT pass through the inguinal canal.",
  [("StatPearls Inguinal Canal region (NBK470204, via existing batch-11 evidence)", "https://www.ncbi.nlm.nih.gov/books/NBK470204",
    "ilioinguinal and genitofemoral nerves pass within it; the deep ring is lateral to the epigastric vessels")],
  "Artery runs in rectus sheath, medial to deep ring; cord/round ligament + genital branch + ilioinguinal nerve do traverse."),
 ("anatomy-anatomy-all-pdf-p1354-q0054", "B", "corroborated",
  "Spleen occupies left hypochondrium.",
  [("StatPearls Spleen", "https://www.ncbi.nlm.nih.gov/books/NBK482235",
    "located in the left hypochondriac region between the diaphragm and gastric fundus")],
  ""),
 ("anatomy-anatomy-all-pdf-p1355-q0055", "D", "corroborated",
  "Ejaculatory duct = ductus deferens + seminal vesicle duct.",
  [("Medscape Ductus Deferens", "https://emedicine.medscape.com/article/1949281-overview",
    "formed by the union of the duct from the seminal vesicle and the ductus (vas) deferens"),
   ("StatPearls Seminal Vesicle", "https://www.ncbi.nlm.nih.gov/books/NBK499854",
    "seminal vesicle ultimately converging with an ampullae to form the ejaculatory duct")],
  ""),
 ("anatomy-anatomy-all-pdf-p1356-q0056", "C", "corroborated",
  "Female urethra opens in the vestibule between the labia minora.",
  [("StatPearls Female External Genitalia", "https://www.ncbi.nlm.nih.gov/books/NBK547703",
    "the urethra opens within the vulvar vestibule ... The area between the labia minora is known as the vulvar vestibule."),
   ("Medscape Female Urethra", "https://emedicine.medscape.com/article/1972504-overview",
    "4 cm long tubular structure that begins at the bladder neck and terminates at the vaginal vestibule")],
  "Eliminates A (male longer), B (begins at bladder neck, not apex), D/E (sphincter/vaginal relations misstated)."),
  ("anatomy-anatomy-all-pdf-p1357-q0057", "E", "needs_source_confirmation",
  "Duodenal supply primarily gastroduodenal + superior mesenteric arcades.",
  [("Medscape Duodenal Anatomy", "https://emedicine.medscape.com/article/1898874-overview",
    "GDA ... gives off ... anterior/posterior superior pancreaticoduodenal artery ... Anterior and posterior branches of the SPDA and IPDA join ... supplying ... the first, second, and third parts of the duodenum"),
   ("StatPearls SMA", "https://www.ncbi.nlm.nih.gov/books/NBK519560",
    "The inferior pancreaticoduodenal artery arises from the SMA and, along with the superior pancreaticoduodenal artery, supplies the head of the pancreas")],
  "Rank-3 coverage is partial (SMA/inferior half); the gastroduodenal half rests on rank-4 overview. Source-page check decides approval."),
 ("anatomy-anatomy-all-pdf-p1358-q0058", "E", "corroborated",
  "CBD + pancreatic duct unite as ampulla of Vater.",
  [("StatPearls Pancreas", "https://www.ncbi.nlm.nih.gov/books/NBK532912",
    "joins the bile duct to form the hepatopancreatic ampulla, which opens into the descending part of the duodenum.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1359-q0059", "C", "corroborated",
  "Inferior epigastric vessels differentiate direct vs indirect hernia.",
  [("StatPearls Inguinal region (NBK470204)", "https://www.ncbi.nlm.nih.gov/books/NBK470204",
    "the deep ring is lateral to the epigastric vessels")],
  "Indirect sac passes lateral (through deep ring), direct medial to the vessels."),
 ("anatomy-anatomy-all-pdf-p1360-q0060", "C", "corroborated",
  "IVC lies posterior to 1st and 3rd duodenal parts.",
  [("TTUHSC Dissector Answers", "https://anatomy.ttuhscep.edu/gastrointestinal_system/duodenum_ans.html",
    "superior (1st): ... anterior to the bile duct, the gastroduodenal artery, the portal vein, and the IVC; horizontal (3rd): ... anterior to ... the IVC, the abdominal aorta")],
  ""),
 ("anatomy-anatomy-all-pdf-p1361-q0061", "C", "corroborated",
  "Liver lymph drains primarily to coeliac nodes.",
  [("StatPearls Lymphatic Drainage", "https://www.ncbi.nlm.nih.gov/books/NBK557720",
    "The liver drains its lymph into the hepatic, caval, posterior mediastinal, and celiac lymph nodes."),
   ("Surgery (Oxford) liver chapter", "https://www.sciencedirect.com/science/article/abs/pii/S1472029911002682",
    "drain into the hepatic nodes and subsequently into the coeliac group")],
  ""),
 ("anatomy-anatomy-all-pdf-p1362-q0062", "A", "corroborated",
  "Transversus abdominis muscle is NOT enclosed by rectus sheath (categorical exam answer).",
  [("StatPearls Rectus Sheath", "https://www.ncbi.nlm.nih.gov/books/NBK537153",
    "contains both the rectus abdominis muscle and the pyramidalis muscle ... thoracoabdominal nerves ... epigastric vessels")],
  "Caveat (existing batch-11 note): one study found transversus fibres within the sheath superiorly - exam-categorical answer stands, note retained."),
 ("anatomy-anatomy-all-pdf-p1363-q0063", "B", "corroborated",
  "Ilioinguinal supplies upper medial thigh skin.",
  [("StatPearls Ilioinguinal Neuralgia", "https://www.ncbi.nlm.nih.gov/books/NBK538256",
    "provides sensory innervation to the upper anteromedial thigh region")],
  ""),
 ("anatomy-anatomy-all-pdf-p1364-q0064", "C", "corroborated",
  "Transverse mesocolon divides greater sac into supra/infracolic compartments.",
  [("TeachMeAnatomy Peritoneal Cavity", "https://teachmeanatomy.info/abdomen/areas/peritoneal-cavity",
    "further divided into two compartments by the ... transverse mesocolon: Supracolic ... Infracolic")],
  ""),
 ("anatomy-anatomy-all-pdf-p1365-q0065", "B", "corroborated",
  "BPH arises in the transitional zone.",
  [("Endotext Benign Prostate Disorders (NCBI)", "https://www.ncbi.nlm.nih.gov/books/NBK279008",
    "The transitional zone ... This is the zone where benign prostatic hypertrophy occurs"),
   ("StatPearls BPH", "https://www.ncbi.nlm.nih.gov/books/NBK558920",
    "stromal and epithelial cell proliferation in the prostate transition zone")],
  ""),
 ("anatomy-anatomy-all-pdf-p1366-q0066", "B", "corroborated",
  "Ilioinguinal innervates internal oblique + transversus abdominis.",
  [("StatPearls Ilioinguinal Neuralgia", "https://www.ncbi.nlm.nih.gov/books/NBK538256",
    "motor innervation of the transverse abdominis and internal oblique muscles")],
  ""),
 ("anatomy-anatomy-all-pdf-p1450-q0001", "D", "corroborated",
  "Temporal lobe lies inferior to the lateral sulcus.",
  [("StatPearls Temporal Lobe", "https://www.ncbi.nlm.nih.gov/books/NBK519512",
    "It is found inferior to the lateral fissure, also known as the Sylvian fissure or the lateral sulcus.")],
  ""),
 ("anatomy-anatomy-all-pdf-p1456-q0002", "D", "corroborated",
  "Post-traumatic CSF rhinorrhoea implicates ethmoid (cribriform) fracture.",
  [("StatPearls Cribriform Plate Fractures", "https://www.ncbi.nlm.nih.gov/books/NBK562192",
    "fractures of the cribriform plate can easily tear the dura and lead to leakage of CSF into the nasal cavity"),
   ("StatPearls Skull Foramen", "https://www.ncbi.nlm.nih.gov/books/NBK546621",
    "fracture of the cribriform plate ... allows cerebrospinal fluid to extravasate into the nasal passages")],
  "Cribriform plate is part of the ethmoid bone (NBK544328)."),
]


def main():
    records = []
    for qid, key, verdict, claim, cites, note in E:
        citations = [
            {"authorityRank": rank_of(u), "authority": a, "url": u,
             "quote": q, "retrievedAt": RETRIEVED}
            for a, u, q in cites
        ]
        has_rank3 = any(c["authorityRank"] <= 3 for c in citations)
        if not has_rank3:
            verdict = "needs_source_confirmation"
            note = (note + " " if note else "") + "No rank<=3 citation; approval requires source-page plus rank<=3 agreement."
        records.append({
            "id": qid,
            "reviewBatch": "review-batch-018",
            "markedKey": key,
            "verdict": verdict,
            "keyClaim": claim,
            "citations": citations,
            "rank3Coverage": "partial" if qid in PARTIAL_RANK3 else "full",
            "rank3Note": PARTIAL_RANK3.get(qid, ""),
            "reviewerNote": note,
        })
    norank3 = [r["id"] for r in records
               if not any(c["authorityRank"] <= 3 for c in r["citations"])]
    print("auto-downgraded (no rank<=3 citation):", norank3)
    doc = {
        "generatedAt": "2026-09-15",
        "reviewBatch": "review-batch-018",
        "recordCount": len(records),
        "method": "manual web verification against rank 2-3 authorities; no bank records modified",
        "verdictCounts": {v: sum(1 for r in records if r["verdict"] == v) for v in ("corroborated", "needs_source_confirmation", "unresolved")},
        "records": records,
    }
    OUT_JSON.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = ["# Review Batch 018 Online Evidence Notes",
             "",
             "50 Anatomy records (positions 851-900) verified 2026-09-15 against rank 2-3 authorities only. "
             "Source-page comparison remains required before any correction or approval.",
             "",
             "| Question | Key | Verdict | Evidence |",
             "|---|---|---|---|"]
    for r in records:
        cites = "; ".join(f"[{c['authority']}]({c['url']})" for c in r["citations"])
        lines.append(f"| `{r['id']}` | {r['markedKey']} | {r['verdict']} | {r['keyClaim']} {cites} |")
    lines += ["",
              "## Items needing source-page confirmation",
              "",
              "- `anatomy-anatomy-all-pdf-p1312-q0024` (unresolved): no authority supports the pubic tubercle as the ureteric termination level; possible key mismatch.",
              "- `anatomy-anatomy-all-pdf-p1311-q0023` (needs_source_confirmation): 3rd duodenal part anterior to aorta confirmed; 4th part is lateral, check exact bank wording.",
              ""]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print("verdicts:", doc["verdictCounts"], "records:", len(records))


if __name__ == "__main__":
    main()
