"""Build review-batch-020 (cranial nerves + visual recap) online-evidence JSON + notes.

Same method as batch 018/019 builders. Special cases:
- p1585-q0058 / p1586-q0058 share an identical stem (possible duplicate).
- p1661-q0014 refers to an image unavailable to this audit.
"""
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_batch018_evidence import RANK3_MARKERS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT_JSON = ROOT / "docs" / "audit" / "review-batch-020-online-evidence.json"
OUT_MD = ROOT / "docs" / "audit" / "review-batch-020-online-evidence.md"
RETRIEVED = "2026-09-15"


def rank_of(url):
    return 3 if any(m in url for m in RANK3_MARKERS) else 4


# (id, key, verdict, claim, [(authority, url, quote)], note)
E = [
 ("anatomy-anatomy-all-pdf-p1582-q0055", "C", "corroborated",
  "Homonymous hemianopia with macular sparing is least expected in frontal lesion (occipital sign).",
  [("StatPearls Homonymous Hemianopsia", "https://www.ncbi.nlm.nih.gov/books/NBK558929",
    "Lesions that affect the occipital lobe will result in contralateral hemianopia with macular sparing")],
  "Frontal features (primitive reflexes, leg weakness, incontinence, executive loss) all typical."),
 ("anatomy-anatomy-all-pdf-p1583-q0056", "B", "corroborated",
  "Pituitary adenoma most likely cause of bitemporal hemianopia among options.",
  [("StatPearls Bitemporal Hemianopsia", "https://www.ncbi.nlm.nih.gov/books/NBK545213",
    "commonly results from a tumor or lesion impinging on the optic chiasm")],
  "Chiasm lies superior to pituitary (same source)."),
 ("anatomy-anatomy-all-pdf-p1584-q0057", "D", "corroborated",
  "Basilar terminates as posterior cerebral arteries.",
  [("StatPearls Brain Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK549894",
    "the basilar artery bifurcates into its 2 terminal branches, the posterior cerebral arteries")]),
 ("anatomy-anatomy-all-pdf-p1585-q0058", "C", "corroborated",
  "Extracranial optic nerve supplied by ophthalmic artery.",
  [("StatPearls Homonymous Hemianopsia", "https://www.ncbi.nlm.nih.gov/books/NBK558929",
    "optic nerve is supplied by the internal carotid artery, specifically the superior hypophyseal and ophthalmic arteries")],
  "Identical stem to p1586-q0058: possible duplicate record, flag for bank dedup."),
 ("anatomy-anatomy-all-pdf-p1586-q0058", "C", "corroborated",
  "Extracranial optic nerve supplied by ophthalmic artery.",
  [("StatPearls Homonymous Hemianopsia", "https://www.ncbi.nlm.nih.gov/books/NBK558929",
    "optic nerve is supplied by the internal carotid artery, specifically the superior hypophyseal and ophthalmic arteries")],
  "Identical stem to p1585-q0058: possible duplicate record, flag for bank dedup."),
 ("anatomy-anatomy-all-pdf-p1587-q0059", "D", "corroborated",
  "Temporal (Meyer loop) lesion causes contralateral superior quadrantanopia.",
  [("StatPearls Superior Quadrantanopia", "https://www.ncbi.nlm.nih.gov/books/NBK558982",
    "right-sided Meyer loop damage would cause vision loss in the superior-left quadrant bilaterally")]),
 ("anatomy-anatomy-all-pdf-p1588-q0060", "C", "corroborated",
  "Resting tremor is NOT cerebellar (parkinsonian); intention tremor is.",
  [("StatPearls Cerebellum", "https://www.ncbi.nlm.nih.gov/books/NBK538167",
    "tremor is observed at the end of the movement, called intention tremor"),
   ("StatPearls Substantia Nigra", "https://www.ncbi.nlm.nih.gov/books/NBK536995",
    "nigrostriatal pathway ... critically involved in the motor deficits observed in Parkinson disease")],
  ""),
 ("anatomy-anatomy-all-pdf-p1591-q0061", "C", "corroborated",
  "Two-point discrimination loss is parietal, least expected in frontal lesion.",
  [("StatPearls Postcentral Gyrus", "https://www.ncbi.nlm.nih.gov/books/NBK549825",
    "contains the primary somatosensory cortex ... touch, pressure, temperature, and pain")],
  ""),
 ("anatomy-anatomy-all-pdf-p1592-q0062", "D", "corroborated",
  "Lateral ventricles join the 3rd via foramen of Monro, not the aqueduct.",
  [("StatPearls Hydrocephalus", "https://www.ncbi.nlm.nih.gov/books/NBK560875",
    "from the lateral ventricle to the third ventricle via the foramen of Monro, from third to the fourth ventricle via the cerebral aqueduct")],
  "Options A/B/C/E all true (130-150mL; lateral-dominant production; temporal horn; 4th ventricle in brainstem)."),
 ("anatomy-anatomy-all-pdf-p1593-q0063", "C", "corroborated",
  "Vertebral artery branches from subclavian.",
  [("StatPearls Brain Arteries", "https://www.ncbi.nlm.nih.gov/books/NBK549894",
    "paired vertebral arteries ... arise from the corresponding subclavian arteries")]),
 ("anatomy-anatomy-all-pdf-p1594-q0064", "A", "corroborated",
  "Internal capsule primarily carries projection fibres.",
  [("StatPearls Lateral Corticospinal", "https://www.ncbi.nlm.nih.gov/books/NBK534818",
    "impulse ... passes through the posterior limb of the internal capsule ... to the anterior horn (lower motor neuron)")],
  "Corticospinal/corticobulbar/thalamocortical projection traffic; association/U-fibres run cortico-cortically."),
 ("anatomy-anatomy-all-pdf-p1595-q0065", "D", "corroborated",
  "Broca damage causes expressive dysphasia.",
  [("StatPearls Broca Area", "https://www.ncbi.nlm.nih.gov/books/NBK526096",
    "Also known as expressive aphasia, it is non-fluent aphasia")]),
 ("anatomy-anatomy-all-pdf-p1596-q0066", "E", "corroborated",
  "Trochlear nucleus is midbrain, not pons.",
  [("StatPearls Trochlear CN4", "https://www.ncbi.nlm.nih.gov/books/NBK537244",
    "trochlear nuclei within the medial midbrain at the level of the inferior colliculus")],
  "Facial/abducens/trigeminal/vestibulocochlear nuclei are pontine."),
 ("anatomy-anatomy-all-pdf-p1597-q0067", "C", "corroborated",
  "Past-pointing + heel-shin failure + nystagmus + slurred speech = cerebellum.",
  [("StatPearls Cerebellum", "https://www.ncbi.nlm.nih.gov/books/NBK538167",
    "ataxia, intention tremor, nystagmus, slurred/scanning speech, hypotonia")],
  ""),
 ("anatomy-anatomy-all-pdf-p1598-q0068", "B", "corroborated",
  "Right parietal (dorsal) lesion causes left inferior quadrantanopia.",
  [("StatPearls Superior Quadrantanopia", "https://www.ncbi.nlm.nih.gov/books/NBK558982",
    "partial inferior defects occur from damage to the superior parts of the pathway including the superior optic radiation in the parietal lobe")]),
 ("anatomy-anatomy-all-pdf-p1599-q0069", "D", "corroborated",
  "CRAO cherry-red spot emboli usually from carotid plaque.",
  [("StatPearls Cherry Red Spot", "https://www.ncbi.nlm.nih.gov/books/NBK539841",
    "The embolus usually originates from the carotid plaque")],
  ""),
 ("anatomy-anatomy-all-pdf-p1600-q0070", "B", "corroborated",
  "Parietal optic radiation lesion causes contralateral inferior quadrantanopia.",
  [("StatPearls Superior Quadrantanopia", "https://www.ncbi.nlm.nih.gov/books/NBK558982",
    "Dorsal fibers ... travel through the posterior temporal lobe and the parietal lobe ... transmit ... inferior visual field")],
  ""),
 ("anatomy-anatomy-all-pdf-p1601-q0071", "B", "corroborated",
  "Anterolateral tract transection loses pain and temperature.",
  [("StatPearls Spinothalamic Tract", "https://www.ncbi.nlm.nih.gov/books/NBK507824",
    "lateral spinothalamic tract carries information about pain and temperature")],
  "Proprioception/vibration are dorsal-column modalities."),
 ("anatomy-anatomy-all-pdf-p1602-q0072", "C", "corroborated",
  "Right homonymous hemianopia with macular sparing implicates PCA.",
  [("Medscape PCA Stroke", "https://emedicine.medscape.com/article/2128100-clinical",
    "Homonymous hemianopia is a key finding that distinguishes PCA strokes"),
   ("NCBI Cerebral Ischemia cortex", "https://www.ncbi.nlm.nih.gov/books/NBK575742",
    "macular area receives dual blood supply ... In thrombosis of the posterior cerebral artery, the macular area is spared")],
  ""),
 ("anatomy-anatomy-all-pdf-p1603-q0073", "B", "corroborated",
  "Isolated leg weakness/numbness stroke implicates ACA (medial frontal/parietal leg area).",
  [("PMC Cerebral circulation", "https://pmc.ncbi.nlm.nih.gov/articles/PMC8446242",
    "ACAs supply all of the medial surfaces of the frontal and parietal lobe ... primary motor, primary sensory cortices")],
  "Leg motor homunculus lies on the medial hemispheric surface in ACA territory."),
 ("anatomy-anatomy-all-pdf-p1604-q0074", "C", "corroborated",
  "Triceps reflex is primarily C7.",
  [("WikiEM Cervical Exam", "https://wikem.org/wiki/Cervical_radiculopathy",
    "C7 | Triceps & Wrist flexion | Index/Middle/Ring Paresthesia | Triceps"),
   ("StatPearls Cervical Radiculopathy", "https://www.ncbi.nlm.nih.gov/books/NBK441828",
    "Motor strength testing ... C7 (triceps)")],
  ""),
 ("anatomy-anatomy-all-pdf-p1605-q0075", "A", "corroborated",
  "Primary visual cortex in occipital lobe.",
  [("PMC Cerebral circulation", "https://pmc.ncbi.nlm.nih.gov/articles/PMC8446242",
    "PCAs supply the occipital lobe, which includes the visual areas")],
  ""),
 ("anatomy-anatomy-all-pdf-p1606-q0076", "E", "corroborated",
  "Visual cortex lesion causes contralateral HH with macular sparing.",
  [("StatPearls Homonymous Hemianopsia", "https://www.ncbi.nlm.nih.gov/books/NBK558929",
    "Lesions that affect the occipital lobe will result in contralateral hemianopia with macular sparing")],
  ""),
 ("anatomy-anatomy-all-pdf-p1607-q0001", "A", "corroborated",
  "Diplopia on reading/downstairs implicates trochlear (superior oblique).",
  [("StatPearls Superior Oblique", "https://www.ncbi.nlm.nih.gov/sites/books/NBK537152",
    "difficulty looking downwards ... reading a book ... descending stairs")],
  ""),
 ("anatomy-anatomy-all-pdf-p1611-q0002", "D", "corroborated",
  "Absent consensual blink with intact direct = efferent (facial) lesion on the unresponsive side.",
  [("StatPearls Trigeminal CN5", "https://www.ncbi.nlm.nih.gov/books/NBK482283",
    "Afferent input from the ophthalmic division ... stimulate the orbicularis oculi muscles bilaterally")],
  "Direct left intact proves left afferent + left efferent work; absent right consensual isolates right VII."),
 ("anatomy-anatomy-all-pdf-p1617-q0003", "C", "corroborated",
  "Pupil-sparing CN III palsy is typically diabetic microvascular.",
  [("StatPearls CN III Palsy", "https://www.ncbi.nlm.nih.gov/books/NBK526112",
    "Microvascular ischemia ... is the most common etiology in adults ... ischemic injury typically sparing parasympathetic fibers"),
   ("AAFP Diplopia and Ptosis", "https://www.aafp.org/afp/2010/0715/p187",
    "Diabetic third nerve palsy ... pupil-sparing ... microvascular infarction")],
  "Aneurysmal compression typically dilates the pupil."),
 ("anatomy-anatomy-all-pdf-p1621-q0004", "D", "corroborated",
  "Glossopharyngeal palsy abolishes the gag reflex (afferent limb).",
  [("StatPearls Gag Reflex", "https://www.ncbi.nlm.nih.gov/books/NBK554502",
    "If the glossopharyngeal (IX) nerve is damaged ... there is no response when touched")],
  "Tongue fasciculations = XII; uvular deviation = X; jaw jerk = V; hoarseness = X."),
 ("anatomy-anatomy-all-pdf-p1625-q0005", "B", "corroborated",
  "Glossopharyngeal is the gag afferent; vagus the efferent.",
  [("StatPearls Gag Reflex", "https://www.ncbi.nlm.nih.gov/books/NBK554502",
    "glossopharyngeal (CN IX) and vagus (CN X) nerves, which serve as the afferent (sensory) and the efferent (motor) limbs")],
  ""),
 ("anatomy-anatomy-all-pdf-p1629-q0006", "C", "corroborated",
  "Cerebellopontine-angle tumours most often involve VIII (acoustic neuroma).",
  [("StatPearls Acoustic Neuroma", "https://www.ncbi.nlm.nih.gov/books/NBK470177",
    "commonly located in the cerebellopontine angle, near the cochlear and vestibular nerves")],
  "Vestibular schwannoma = 75-85% of CPA tumours (CPA Cancer, NBK559116)."),
 ("anatomy-anatomy-all-pdf-p1634-q0007", "E", "corroborated",
  "Abducens palsy leaves medial rectus unopposed causing convergent squint.",
  [("StatPearls Abducens CN6", "https://www.ncbi.nlm.nih.gov/books/NBK430711",
    "innervate the lateral rectus muscle, which then abducts the eye"),
   ("StatPearls Oculomotor CN3", "https://www.ncbi.nlm.nih.gov/books/NBK537126",
    "down-and-out eye position due to the unopposed action of the lateral rectus ... and superior oblique")],
  "A/B/C/D all false (SO=IV; horizontal not vertical diplopia; nucleus in pons; enters via superior orbital fissure)."),
 ("anatomy-anatomy-all-pdf-p1638-q0008", "B", "corroborated",
  "Internal auditory meatus contains VII and VIII.",
  [("StatPearls CN8", "https://www.ncbi.nlm.nih.gov/books/NBK537359",
    "commonly involve the cerebellopontine angle (CPA), the internal auditory canal (IAC), or the inner ear"),
   ("Mayo Acoustic Neuroma", "https://www.mayoclinic.org/diseases-conditions/acoustic-neuroma/symptoms-causes/syc-20356127",
    "grows between the vestibulocochlear nerve and the facial nerve inside the inner ear canal")],
  ""),
 ("anatomy-anatomy-all-pdf-p1640-q0009", "C", "corroborated",
  "Depressed-abducted eye with ptosis = CN III palsy (unopposed LR + SO).",
  [("StatPearls CN III Palsy", "https://www.ncbi.nlm.nih.gov/books/NBK526112",
    "characteristic down-and-out eye position ... Ptosis occurs due to paralysis of the levator palpebrae superioris")],
  ""),
 ("anatomy-anatomy-all-pdf-p1644-q0010", "B", "corroborated",
  "Trochlear nerve innervates superior oblique only.",
  [("StatPearls Trochlear CN4", "https://www.ncbi.nlm.nih.gov/books/NBK537244",
    "The only muscle the trochlear nerve innervates, the superior oblique muscle")],
  ""),
 ("anatomy-anatomy-all-pdf-p1647-q0011", "C", "corroborated",
  "Spinal accessory innervates SCM and trapezius.",
  [("StatPearls Accessory CN11", "https://www.ncbi.nlm.nih.gov/books/NBK507722",
    "innervates the sternocleidomastoid (SCM) and trapezius muscles through its spinal root")],
  ""),
 ("anatomy-anatomy-all-pdf-p1651-q0012", "A", "corroborated",
  "Facial nerve divides into five terminal branches within the parotid.",
  [("StatPearls Facial Nerve Anatomy", "https://www.ncbi.nlm.nih.gov/books/NBK554569",
    "enters the parotid gland ... five branches emerge"),
   ("Iowa Head and Neck Protocols", "https://iowaprotocols.medicine.uiowa.edu/protocols/facial-nerve-cranial-nerve-vii-general-information",
    "Within the parotid gland, the facial nerve divides into five branches: Temporal, Zygomatic, Buccal, Marginal mandibular, Cervical")],
  ""),
 ("anatomy-anatomy-all-pdf-p1657-q0013", "C", "corroborated",
  "Glossopharyngeal is NOT the gag efferent (vagus is); all other statements true.",
  [("StatPearls Gag Reflex", "https://www.ncbi.nlm.nih.gov/books/NBK554502",
    "afferent (sensory) and the efferent (motor) limbs ... CN IX ... CN X"),
   ("StatPearls Glossopharyngeal CN9", "https://www.ncbi.nlm.nih.gov/books/NBK539877",
    "supply motor innervation to the stylopharyngeus muscle ... parasympathetic innervation to the parotid glands")],
  ""),
 ("anatomy-anatomy-all-pdf-p1661-q0014", "B", "needs_source_confirmation",
  "Bank key says abducens, but the stem references an image unavailable to this audit.",
  [],
  "Image-dependent question: the eye position cannot be inspected. Do not approve without the source page/image."),
 ("anatomy-anatomy-all-pdf-p1665-q0015", "D", "corroborated",
  "Facial nerve traverses the internal acoustic meatus.",
  [("StatPearls Facial Nerve Anatomy", "https://www.ncbi.nlm.nih.gov/books/NBK554569",
    "pass through the posterior cranial fossa along with the vestibulocochlear nerve ... entering the internal acoustic meatus")],
  "It exits the skull via the stylomastoid foramen; IAM is its transit, matching key D among options."),
 ("anatomy-anatomy-all-pdf-p1671-q0016", "D", "corroborated",
  "Masseter wasting + jaw-opening weakness + anterior-tongue numbness = mandibular nerve (V3).",
  [("StatPearls Mandibular Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK507820",
    "mandibular nerve ... carries both afferent and efferent fibers ... muscles of mastication ... anterior two-thirds of the tongue")],
  ""),
 ("anatomy-anatomy-all-pdf-p1676-q0017", "D", "corroborated",
  "Mandibular nerve does NOT innervate orbicularis oculi (facial nerve does).",
  [("StatPearls Mandibular Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK507820",
    "motor muscular branches to the medial pterygoid, tensor tympani, and tensor veli palatini ... mastication muscles")],
  "A/B/C/E all true (infratemporal course, foramen ovale, anterior tongue sensory, mixed nerve)."),
 ("anatomy-anatomy-all-pdf-p1677-q0018", "D", "corroborated",
  "Oculomotor nerve runs in the lateral wall of the cavernous sinus.",
  [("StatPearls Cavernous Sinus", "https://www.ncbi.nlm.nih.gov/books/NBK459244",
    "enters the cavernous sinus, where it runs on the roof and lateral wall")],
  "A/B/C/E false (mixed? no - pure motor + parasymp; not all EOMs; constricts pupil; enters via superior orbital fissure)."),
 ("anatomy-anatomy-all-pdf-p1681-q0019", "B", "corroborated",
  "Uvula deviates away from a vagal lesion, so rightward deviation implicates the left vagus.",
  [("StatPearls Vagus CN10", "https://www.ncbi.nlm.nih.gov/books/NBK537171",
    "uvula deviation (towards the opposite side of the lesion)")],
  ""),
 ("anatomy-anatomy-all-pdf-p1686-q0020", "B", "corroborated",
  "Mandibular division spares the upper lip (maxillary territory).",
  [("StatPearls Trigeminal POC", "https://www.statpearls.com/point-of-care/862",
    "maxillary branch ... upper lip ... mandibular branch ... external ear, chin, lower lip, anterior two-thirds of the tongue")],
  ""),
 ("anatomy-anatomy-all-pdf-p1687-q0021", "C", "corroborated",
  "Vagus carries visceral afferents from aortic arch baroreceptors.",
  [("StatPearls Vagus CN10", "https://www.ncbi.nlm.nih.gov/books/NBK537171",
    "inferior ganglion of X provides afferent general visceral fibers to the carotid and aortic bodies")],
  "A/B/D/E false (foramen ovale=V3; oropharynx general sensation=V; parotid=IX; gag afferent=IX)."),
 ("anatomy-anatomy-all-pdf-p1688-q0022", "D", "corroborated",
  "Maxillary division spares the external ear (mandibular territory).",
  [("StatPearls Trigeminal POC", "https://www.statpearls.com/point-of-care/862",
    "maxillary branch ... superior palate, upper lip, upper molar ... nasal cavity ... lower eyelid")],
  "External ear supplied via mandibular (auriculotemporal)."),
 ("anatomy-anatomy-all-pdf-p1691-q0023", "D", "corroborated",
  "Hyperacusis (stapedius dysfunction) occurs in facial palsy.",
  [("PMC Trigeminal/Facial nerves", "https://pmc.ncbi.nlm.nih.gov/articles/PMC2848459",
    "hyperacusis ... due the stapedius muscle ... being affected")],
  "Ptosis/ophthalmoplegia are oculomotor; facial sensory loss is trigeminal."),
 ("anatomy-anatomy-all-pdf-p1693-q0024", "B", "corroborated",
  "Lingual nerve carries touch (not taste) from anterior tongue; chorda tympani carries taste/salivation.",
  [("StatPearls Lingual Nerve", "https://www.ncbi.nlm.nih.gov/books/NBK546652",
    "innervates the mucous membrane of the anterior two-thirds ... chorda tympani ... responsible for taste perception ... and secretory/motor innervation of glands")],
  "Taste + salivation intact isolates the lingual (general sensory) division."),
 ("anatomy-anatomy-all-pdf-p1694-q0025", "E", "corroborated",
  "Inability to raise the eyelid (levator/CN III) is NOT a facial palsy feature; lagophthalmos is.",
  [("StatPearls CN III Palsy", "https://www.ncbi.nlm.nih.gov/books/NBK526112",
    "Ptosis occurs due to paralysis of the levator palpebrae superioris muscle")],
  "A-D (hyperacusis, reduced salivation/lacrimation, taste loss) are all VII features."),
 ("anatomy-anatomy-all-pdf-p1695-q0026", "B", "corroborated",
  "Tongue deviation toward the lesion is hypoglossal (XII), not vagal.",
  [("StatPearls Hypoglossal CN12", "https://www.ncbi.nlm.nih.gov/books/NBK532869",
    "the tongue, when protruded, deviates towards the damaged nerve")],
  "A/C/D/E (uvula away, hoarseness, gag loss, dysphagia) are vagal."),
 ("anatomy-anatomy-all-pdf-p1696-q0027", "E", "corroborated",
  "Glossopharyngeal provides parotid parasympathetics.",
  [("StatPearls Glossopharyngeal CN9", "https://www.ncbi.nlm.nih.gov/books/NBK539877",
    "provide parasympathetic innervation to the parotid glands")],
  "A-D false (efferent=vagus; exits via jugular foramen; taste post-third; tensor veli palatini=V3)."),
]


def main():
    records = []
    for row in E:
        qid, key, v0, claim, cites = row[0], row[1], row[2], row[3], row[4]
        note = row[5] if len(row) > 5 else ""
        citations = [
            {"authorityRank": rank_of(u), "authority": a, "url": u,
             "quote": q, "retrievedAt": RETRIEVED}
            for a, u, q in cites
        ]
        verdict = v0
        if not cites:
            verdict = "needs_source_confirmation"
            note = (note + " " if note else "") + "No online evidence retrievable (image-dependent)."
        elif not any(c["authorityRank"] <= 3 for c in citations):
            verdict = "needs_source_confirmation"
            note = (note + " " if note else "") + "No rank<=3 citation."
        records.append({
            "id": qid, "reviewBatch": "review-batch-020", "markedKey": key,
            "verdict": verdict, "keyClaim": claim, "citations": citations,
            "rank3Coverage": "full", "rank3Note": "", "reviewerNote": note,
        })
    norank3 = [r["id"] for r in records
               if r["verdict"] == "corroborated"
               and not any(c["authorityRank"] <= 3 for c in r["citations"])]
    assert not norank3, norank3
    doc = {
        "generatedAt": "2026-09-15", "reviewBatch": "review-batch-020",
        "recordCount": len(records),
        "method": "manual web verification against rank 2-3 authorities; no bank records modified",
        "verdictCounts": {v: sum(1 for r in records if r["verdict"] == v)
                          for v in ("corroborated", "needs_source_confirmation", "unresolved")},
        "records": records,
    }
    OUT_JSON.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    lines = ["# Review Batch 020 Online Evidence Notes", "",
             "50 cranial-nerve/visual records (positions 951-1000) verified 2026-09-15 against rank 2-3 authorities only. "
             "Source-page comparison remains required before any correction or approval.", "",
             "| Question | Key | Verdict | Evidence |", "|---|---|---|---|"]
    for r in records:
        cites = "; ".join(f"[{c['authority']}]({c['url']})" for c in r["citations"]) or "no retrievable citation"
        lines.append(f"| `{r['id']}` | {r['markedKey']} | {r['verdict']} | {r['keyClaim']} {cites} |")
    lines += ["",
              "## Flags",
              "",
              "- `p1585-q0058` / `p1586-q0058`: identical stems, possible duplicate bank records.",
              "- `p1661-q0014`: image-dependent (eye photograph unavailable); needs source page.",
              ""]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print("verdicts:", doc["verdictCounts"], "records:", len(records))


if __name__ == "__main__":
    main()
