import { readFile, writeFile } from "node:fs/promises";
const root = "/home/ubuntu/mrcem-offline-revision";
const base = JSON.parse(await readFile(`${root}/docs/audit/anatomy-all-pdf-batch-63-ocr-records.json`, "utf8"));
const data = {
1763:["The chorda tympani branch of the facial nerve carries which of the following:",["Taste from the posterior one-third of the tongue","Sensation from the posterior one-third of the tongue","Parasympathetic innervation of the parotid gland","Taste from the anterior two-thirds of the tongue","Sensation from the anterior two-thirds of the tongue"],3,"Chorda tympani carries taste from the anterior two-thirds; V3 carries general sensation there and IX carries posterior taste and sensation.","VII taste anterior; IX taste posterior.","https://www.ncbi.nlm.nih.gov/books/NBK545236/"],
1764:["Regarding the hypoglossal nerve, which of the following statements is CORRECT:",["The hypoglossal nerve emerges from the cranial cavity via the jugular foramen.","The hypoglossal nerve innervates all of the muscles of the tongue.","In hypoglossal nerve palsy, the tongue deviates away from the affected side on protrusion.","Hypoglossal nerve palsy results in weakness of the ipsilateral tongue.","Hypoglossal nerve palsy results in loss of the gag reflex."],3,"CN XII exits through the hypoglossal canal, supplies the tongue except palatoglossus, and causes ipsilateral weakness with deviation toward the affected side.","XII points toward the weak side.","https://www.ncbi.nlm.nih.gov/books/NBK537167/"],
1765:["A patient presenting with nerve injury has sparing of the upper half of the orbicularis oculi muscle but not the lower half. The lower half of the orbicularis oculi is supplied by which branch of the facial nerve:",["Temporal branch","Cervical branch","Zygomatic branch","Buccal branch","Mandibular branch"],2,"The zygomatic branch supplies the orbicularis oculi region; facial nerve terminal branches have distinct territories.","Zygomatic closes the eye.","https://www.ncbi.nlm.nih.gov/books/NBK470353/"],
1766:["The maxillary division of the trigeminal nerve exits the skull through the:",["Foramen rotundum","Foramen ovale","Superior orbital fissure","Internal acoustic meatus","Jugular foramen"],0,"The maxillary division, V2, exits through foramen rotundum.","V2 rotundum; V3 ovale.","https://www.ncbi.nlm.nih.gov/books/NBK470353/"],
1767:["The glossopharyngeal nerve carries all of the following EXCEPT for:",["Visceral afferent fibres from the carotid body and sinus","Sensory afferent fibres from the posterior one-third of the tongue","Sensory afferent fibres from the lower teeth and associated gingivae","Afferent taste fibres from the posterior one-third of the tongue","Motor fibres to the stylopharyngeus muscle"],2,"Lower-teeth and gingival sensation is carried by the mandibular division of the trigeminal nerve, not CN IX.","IX: carotid, posterior tongue, taste, stylopharyngeus. V3: lower teeth.","https://www.ncbi.nlm.nih.gov/books/NBK470353/"],
1768:["Which of the following nerves is the efferent pathway of the pupillary light reflex:",["Facial nerve","Ophthalmic nerve","Optic nerve","Oculomotor nerve","Abducens nerve"],3,"The optic nerve is afferent and the oculomotor nerve carries the efferent parasympathetic pathway.","II in; III constricts.","https://www.ncbi.nlm.nih.gov/books/NBK553169/"],
1769:["Which of the following muscles is NOT supplied by the facial nerve:",["Occipitofrontalis muscle","Posterior belly of the digastric muscle","Stapedius muscle","Stylohyoid muscle","Masseter muscle"],4,"The facial nerve supplies the other listed muscles; masseter is supplied by V3.","VII expresses; V3 chews.","https://www.ncbi.nlm.nih.gov/books/NBK470353/"],
1770:["A 28 year old male man is brought to ED having been hit in the head by a cricket ball. Imaging shows a fracture of the foramen rotundum. Which of the following nerves would most likely be injured:",["Ophthalmic nerve","Maxillary nerve","Mandibular nerve","Facial nerve","Glossopharyngeal nerve"],1,"The maxillary nerve runs through foramen rotundum.","V2 rotundum.","https://www.ncbi.nlm.nih.gov/books/NBK470353/"],
1771:["Which of the following is NOT a typical feature of trochlear nerve palsy:",["Patient head tilts to side of affected eye","Patient has weakness of downward gaze","Patient has vertical diplopia","Patient has difficulty walking downstairs","Eye is extorted and elevated"],0,"Trochlear palsy causes weakness of downward gaze, vertical diplopia, difficulty downstairs, and an extorted/elevated eye; compensatory head tilt is away from the affected side.","CN IV: down and in, with head tilt away.","https://www.ncbi.nlm.nih.gov/books/NBK565850/"],
1772:["A 49 year old man presents to ED complaining of visual disturbance in his right eye. On examination you note when you shine a light in his right eye, neither his right or left pupil constricts. When you shine a light in his left eye, both his left and right pupil constrict. Which of the following nerves is most likely affected:",["Oculomotor nerve","Optic nerve","Trochlear nerve","Abducens nerve","Ophthalmic nerve"],1,"A right optic-nerve afferent lesion abolishes direct and consensual responses to right-eye illumination while responses to left-eye illumination remain intact.","II is the afferent limb; III is the efferent limb.","https://www.ncbi.nlm.nih.gov/books/NBK553169/"]
};
const plan = base.records.map((r) => { const d = data[r.sourcePage]; if (!d) throw new Error(`Missing source mapping ${r.sourcePage}`); return {id:r.id,page:r.sourcePage,stem:d[0],options:d[1],correctOption:d[2],fact:d[3],mnemonic:d[4],emojiCues:["🧠","👁️","⚡"],sourceLabel:"NCBI authoritative source",sourceUrl:d[5],finding:"Displayed source key and option order directly verified on the original rendered page."}; });
await writeFile(`${root}/docs/audit/anatomy-batch-63-restorations.json`, JSON.stringify(plan,null,2)+"\n");
console.log(JSON.stringify({batch:63,records:plan.length},null,2));
