import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); const bankPath = path.join(root, "client", "src", "lib", "ocrDraftSections.ts"); const artifactPath = path.join(root, "docs", "audit", "applied-anatomy-batch-21.json"); const reviewedWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft.";
const restored = new Map([["anatomy-anatomy-all-pdf-p0638-q0030", [638, 2]], ["anatomy-anatomy-all-pdf-p0639-q0031", [639, 2]], ["anatomy-anatomy-all-pdf-p0640-q0032", [640, 2]], ["anatomy-anatomy-all-pdf-p0641-q0033", [641, 3]], ["anatomy-anatomy-all-pdf-p0643-q0034", [643, 3]], ["anatomy-anatomy-all-pdf-p0647-q0036", [647, 3]], ["anatomy-anatomy-all-pdf-p0649-q0038", [649, 0]]]); const restricted = new Map([["anatomy-anatomy-all-pdf-p0634-q0029", 634], ["anatomy-anatomy-all-pdf-p0644-q0035", 644], ["anatomy-anatomy-all-pdf-p0648-q0037", 648]]);
function drafts(source) { const p = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const s = source.indexOf(p); const a = s + p.length; const e = source.indexOf("];", a); if (s < 0 || e < 0) throw new Error("OCR draft export not found"); return JSON.parse(source.slice(a, e + 1)); }
const [bank, artifactText] = await Promise.all([readFile(bankPath, "utf8"), readFile(artifactPath, "utf8")]); const byId = new Map(drafts(bank).map((d) => [d.id, d])); const artifact = JSON.parse(artifactText);
if (artifact.automaticApproval !== false || artifact.mockEligibility !== "No restored OCR draft is mock eligible.") throw new Error("Audit artifact lacks required approval or mock-exclusion safeguards."); if (artifact.applied.length !== restored.size || artifact.restricted.length !== restricted.size) throw new Error("Batch 21 artifact count mismatch.");
for (const row of artifact.applied) { const expect = restored.get(row.id); const d = byId.get(row.id); if (!expect || !d || d.sourcePage !== expect[0] || row.sourcePage !== expect[0]) throw new Error(`Unexpected restored record ${row.id}.`); if (d.status !== "ocr_draft" || !d.askable || d.approved === true || d.needsImage || d.correctOption !== expect[1] || d.correctOption < 0 || d.correctOption >= d.options.length) throw new Error(`${row.id} restoration state invalid.`); if (!Array.isArray(d.warnings) || d.warnings.length !== 1 || d.warnings[0] !== reviewedWarning) throw new Error(`${row.id} lacks exact review warning.`); if (d.options.length !== 5 || d.options.some((o) => !o?.trim()) || !d.highYieldNote?.trim() || !d.mnemonic?.trim() || !d.memoryAid?.coreFact?.trim() || !d.memoryAid?.mnemonic?.trim() || !d.memoryAid?.cueLabel?.trim() || !d.memoryAid?.sourceLabel?.trim() || !d.memoryAid?.sourceUrl?.startsWith("https://") || !Array.isArray(d.memoryAid.emojiCues) || d.memoryAid.emojiCues.length < 1 || d.memoryAid.emojiCues.length > 3 || d.memoryAid.emojiCues.some((c) => !c?.trim())) throw new Error(`${row.id} learning-aid state invalid.`); if (!row.evidence?.externalSource?.startsWith("https://") || !row.evidence?.externalFinding?.trim()) throw new Error(`${row.id} lacks evidence.`); }
for (const row of artifact.restricted) { const page = restricted.get(row.id); const d = byId.get(row.id); if (!page || !d || d.sourcePage !== page || row.sourcePage !== page) throw new Error(`Unexpected restricted record ${row.id}.`); if (d.status !== "needs_review" || d.askable || d.correctOption !== null || d.approved === true || d.needsImage || d.learningNote || d.highYieldNote || d.mnemonic || d.memoryAid) throw new Error(`${row.id} restriction state invalid.`); if (!Array.isArray(d.warnings) || d.warnings.length !== 1 || !d.warnings[0].startsWith("Source page reviewed,") || d.options.length !== 5 || d.options.some((o) => !o?.trim()) || !row.evidence?.externalSource?.startsWith("https://") || !row.evidence?.externalFinding?.trim()) throw new Error(`${row.id} restriction safeguards invalid.`); }
console.log(JSON.stringify({ restoredVerified: artifact.applied.length, restrictedVerified: artifact.restricted.length, approvedRecordsCreated: 0, result: "pass" }, null, 2));
