import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."); const source = await readFile(path.join(root, "client", "src", "lib", "ocrDraftSections.ts"), "utf8"); const artifact = JSON.parse(await readFile(path.join(root, "docs", "audit", "applied-anatomy-batch-40.json"), "utf8")); const token = "export const ocrDraftQuestions: OcrDraftQuestion[] = "; const start = source.indexOf(token) + token.length; const end = source.indexOf("];", start); if (start < token.length || end < 0) throw new Error("OCR draft export not found"); const byId = new Map(JSON.parse(source.slice(start, end + 1)).map((item) => [item.id, item])); const exactWarning = "Source page and external anatomy reference reviewed; remains an unapproved OCR draft."; const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const restored = [
  ["p1241-q0158", 1241, 2, "The oesophagus passes through the diaphragm at which vertebral level:", ["T8", "T9", "T10", "T11", "T12"], "https://www.ncbi.nlm.nih.gov/books/NBK482513/"], ["p1244-q0159", 1244, 1, "A direct inguinal hernia is due to weakness in which of the following layers:", ["External oblique aponeurosis", "Transversalis fascia", "Transversus abdominis muscle", "Internal oblique muscle", "Lacunar ligament"], "https://www.ncbi.nlm.nih.gov/books/NBK470204/"], ["p1246-q0160", 1246, 3, "The following structures are all found in the spermatic cord EXCEPT for the:", ["Pampiniform plexus of veins", "Cremasteric artery", "Remnants of the processus vaginalis", "Pudendal nerve", "Testicular artery"], "https://www.ncbi.nlm.nih.gov/books/NBK554736/"], ["p1249-q0161", 1249, 2, "A 55 year old woman presents to ED complaining of abdominal pain and profuse vomiting. Imaging shows part of the bowel is being compressed between the abdominal aorta and the superior mesenteric artery. Which part of the bowel is most likely being affected:", ["First part of the duodenum", "Second part of the duodenum", "Third part of the duodenum", "Ileum", "Jejunum"], "https://www.ncbi.nlm.nih.gov/books/NBK482209/"], ["p1250-q0162", 1250, 1, "The inferior vena cava leaves the abdomen at which of the following vertebral levels:", ["T6", "T8", "T10", "T12", "L1"], "https://www.ncbi.nlm.nih.gov/books/NBK482353/"], ["p1254-q0163", 1254, 1, "A 75 year old man presents to ED complaining of abdominal pain radiating to his back, anorexia and weight loss. Imaging shows a large tumour of the neck of the pancreas. Which of the following structures is most likely compressed by the tumour:", ["Inferior mesenteric artery", "Portal vein", "First part of the duodenum", "Ureter", "Coeliac trunk"], "https://pmc.ncbi.nlm.nih.gov/articles/PMC4062210/"], ["p1255-q0164", 1255, 4, "The following structures are all found in the spermatic cord except for the:", ["Ductus deferens", "Branch of the inferior vesical artery", "Cremasteric vein", "Branch of the genitofemoral nerve", "Inferior epigastric artery"], "https://www.ncbi.nlm.nih.gov/books/NBK470335/"], ["p1258-q0167", 1258, 3, "The sacrospinous ligament spans between which of the following structures:", ["The anterior superior iliac spine to the sacrum and coccyx", "The posterior superior iliac spine to the sacrum and coccyx", "The ischial tuberosity to the sacrum and coccyx", "The ischial spine to the sacrum and coccyx", "The pubic arch to the sacrum and coccyx"], "https://www.ncbi.nlm.nih.gov/books/NBK493215/"]
];
const restricted = [["p1256-q0165", 1256, "The quadratus lumborum muscle is innervated by which of the following:", ["Iliohypogastric nerve", "Ilioinguinal nerve", "Anterior rami of L2 - L4", "Anterior rami of T9 - T12", "Anterior rami of T12 - L4"]], ["p1257-q0166", 1257, "Visceral afferent fibres from the pancreas travel to which of the following spinal cord levels:", ["T1 - T2", "T4 - T6", "T6 - T10", "T10 - T12", "T12 - L2"]]];
if (artifact.automaticApproval !== false || artifact.mockEligibility !== "No restored OCR draft is mock eligible." || artifact.applied?.length !== 8 || artifact.restricted?.length !== 2 || new Set(artifact.applied.map((x) => x.id)).size !== 8 || new Set(artifact.restricted.map((x) => x.id)).size !== 2) throw new Error("Invalid Batch 40 artifact controls.");
for (const [suffix, page, key, stem, options, sourceUrl] of restored) { const id = `anatomy-anatomy-all-pdf-${suffix}`; const draft = byId.get(id); const row = artifact.applied.find((x) => x.id === id); const cues = draft?.memoryAid?.emojiCues; if (!draft || !row || draft.sourcePage !== page || row.sourcePage !== page || draft.stem !== stem || !same(draft.options, options) || draft.correctOption !== key || draft.status !== "ocr_draft" || !draft.askable || draft.approved === true || draft.needsImage !== false || draft.warnings?.length !== 1 || draft.warnings[0] !== exactWarning || !draft.explanation?.trim() || !draft.learningNote?.trim() || !draft.highYieldNote?.trim() || !draft.mnemonic?.trim() || !draft.memoryAid?.coreFact?.trim() || !draft.memoryAid?.mnemonic?.trim() || !draft.memoryAid?.cueLabel?.trim() || !draft.memoryAid?.sourceLabel?.trim() || !draft.memoryAid?.sourceUrl?.startsWith("https://") || !Array.isArray(cues) || cues.length < 1 || cues.length > 3 || !cues.every((x) => typeof x === "string" && x.trim()) || !row.before || !row.after || row.after.stem !== stem || !same(row.after.options, options) || row.after.correctOption !== key || row.after.status !== "ocr_draft" || row.after.askable !== true || row.after.warnings?.[0] !== exactWarning || row.evidence?.externalSource !== sourceUrl || !row.evidence?.externalFinding?.trim()) throw new Error(`Invalid restored Batch 40 record: ${suffix}`); }
for (const [suffix, page, stem, options] of restricted) { const id = `anatomy-anatomy-all-pdf-${suffix}`; const draft = byId.get(id); const row = artifact.restricted.find((x) => x.id === id); if (!draft || !row || draft.sourcePage !== page || row.sourcePage !== page || draft.stem !== stem || !same(draft.options, options) || draft.status !== "needs_review" || draft.askable || draft.approved === true || draft.correctOption !== null || draft.learningNote || draft.highYieldNote || draft.mnemonic || draft.memoryAid || draft.warnings?.length !== 1 || !draft.warnings[0].startsWith("Source page reviewed,") || !row.before || !row.after || row.after.correctOption !== null || row.after.status !== "needs_review" || row.after.askable !== false || !row.evidence?.externalSource?.startsWith("https://") || !row.evidence?.externalFinding?.trim()) throw new Error(`Invalid restricted Batch 40 record: ${suffix}`); }
console.log(JSON.stringify({ restoredVerified: 8, restrictedVerified: 2, approvedRecordsCreated: 0, result: "pass" }, null, 2));

